
import {
  Content,
  File,
  cmp,
  configDefinition,
  configReprSetting,
  each,
  isAuthActive,
  isConfigData,
} from '@voxgig/sdkgen'


import {
  KIT,
  Model,
  getModelPath,
} from '@voxgig/apidef'


import {
  formatZigValue,
} from './utility_zig'


// core/config.zig: make_config() builds the embedded API model as a Value;
// make_feature(name) is the N-feature-safe factory the client uses to
// instantiate features named in the options (mirrors go/rust Config).
const Config = cmp(async function Config(props: any) {
  const ctx$ = props.ctx$
  const target = props.target

  const model: Model = ctx$.model

  const feature = getModelPath(model, `main.${KIT}.feature`)

  // The canonical config OBJECT and its JSON, from the shared helper. Both
  // representations render from the same `def`, so they cannot describe
  // different configs - and this target picks up `options.server` (the
  // OpenAPI server-variable defaults), which the hand-rolled build here
  // omitted entirely. Passing target.name opts this target into the main
  // slug/version/target identity fields (read by station's descriptor -
  // see configDefinition).
  const { def: config, json: configJson } = configDefinition(model, target.name)
  const asData = isConfigData(configJson, configReprSetting(model))

  File({ name: 'config.' + target.ext }, () => {

    // ABOVE THE THRESHOLD: emit the model as DATA.
    //
    // The literal is one nested expression that Zig's comptime evaluator has
    // to walk in full at every build; a string constant is one token, and
    // `json_parse` (std.json at the boundary, then fromStdJson) builds the
    // same Value at runtime.
    //
    // The escaping is JSON.stringify's, which is valid Zig: it escapes every
    // backslash, so the JSON's own `\uXXXX` reaches the file as `\\uXXXX` and
    // no Zig escape sequence is ever formed from it.
    if (asData) {
      Content(`// Generated API configuration (mirrors go/rust core/config).

const std = @import("std");
const h = @import("helpers.zig");
const types = @import("types.zig");
const jsonparse = @import("../utility/jsonparse.zig");
const Value = h.Value;
const Feature = types.Feature;

/// THE API MODEL, EMBEDDED AS DATA (sdkgen rung L1).
///
/// Emitted only above a size threshold, or when \`main.kit.config.repr\` pins
/// it: for a small model the literal is smaller and far easier to read when
/// debugging.
const CONFIG_DATA: []const u8 = ${JSON.stringify(configJson)};

pub fn make_config() Value {
    // Unreachable on error: the constant is generated by a JSON serialiser and
    // never edited by hand. Panicking beats returning an empty config, which
    // would fail far from the cause.
    return jsonparse.json_parse(CONFIG_DATA) catch
        @panic("${model.const.Name}: embedded config is not valid JSON");
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Value nodes are arena-allocated and reference-stable, so the shared value is
// genuinely one structure, not a copy.
var shared_config_val: ?Value = null;

/// The process-wide config, built once on first use.
///
/// The returned Value SHARES its nodes: treat it as read-only. Callers that
/// need to mutate should use make_config, which always returns a fresh copy.
pub fn shared_config() Value {
    if (shared_config_val) |c| return c;
    const c = make_config();
    shared_config_val = c;
    return c;
}

pub fn make_feature(name: []const u8) Feature {
`)
    }
    else {

    Content(`// Generated API configuration (mirrors go/rust core/config).

const std = @import("std");
const h = @import("helpers.zig");
const types = @import("types.zig");
const Value = h.Value;
const Feature = types.Feature;

pub fn make_config() Value {
    return ${formatZigValue(config, 1)};
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Value nodes are arena-allocated and reference-stable, so the shared value is
// genuinely one structure, not a copy.
var shared_config_val: ?Value = null;

/// The process-wide config, built once on first use.
///
/// The returned Value SHARES its nodes: treat it as read-only. Callers that
/// need to mutate should use make_config, which always returns a fresh copy.
pub fn shared_config() Value {
    if (shared_config_val) |c| return c;
    const c = make_config();
    shared_config_val = c;
    return c;
}

pub fn make_feature(name: []const u8) Feature {
`)
    }

    // The factory must be able to instantiate any built-in feature by name,
    // not just the ones the current API model configures — a caller can enable
    // a shipped feature (e.g. netsim) purely through runtime options even when
    // the API def does not list it. The built-in set mirrors the feature
    // templates in tm/zig/feature/ (excluding `base`, the fallback, and
    // `support`, a helper module). Any model feature not already built in is
    // appended so bespoke features still resolve.
    const builtinFeatures = [
      'audit', 'cache', 'clienttrack', 'debug', 'idempotency', 'log',
      'metrics', 'netsim', 'paging', 'proxy', 'ratelimit', 'rbac',
      'retry', 'streaming', 'telemetry', 'test', 'timeout',
    ]

    const featureNames: string[] = [...builtinFeatures]
    each(feature, (f: any) => {
      if (f.name !== 'base' && !featureNames.includes(f.name)) {
        featureNames.push(f.name)
      }
    })

    featureNames.forEach((name: string) => {
      const fname = name.charAt(0).toUpperCase() + name.slice(1)
      Content(`    if (std.mem.eql(u8, name, "${name}")) return @import("../feature/${name}.zig").${fname}Feature.make();
`)
    })

    Content(`    return @import("../feature/base.zig").BaseFeature.make();
}
`)
  })
})


export {
  Config
}
