
import {
  Content,
  File,
  Folder,
  cmp,
  configDefinition,
  configReprSetting,
  each,
  isAuthActive,
  isConfigData,
  targetFeatures,
} from '@voxgig/sdkgen'


import {
  KIT,
  Model,
  getModelPath,
} from '@voxgig/apidef'


import {
  formatZigValue,
} from './utility_zig'


// core/config.zig: make_config() builds the embedded API model as a Value;
// make_feature(name) is the N-feature-safe factory the client uses to
// instantiate features named in the options (mirrors go/rust Config).
const Config = cmp(async function Config(props: any) {
  const ctx$ = props.ctx$
  const target = props.target

  const model: Model = ctx$.model

  // Gated by the applicability tags, so this target never imports or
  // registers a feature it has no source for. One rule, one place:
  // helpers/applicability.
  const feature = targetFeatures(model, target)

  // The canonical config OBJECT and its JSON, from the shared helper. Both
  // representations render from the same `def`, so they cannot describe
  // different configs - and this target picks up `options.server` (the
  // OpenAPI server-variable defaults), which the hand-rolled build here
  // omitted entirely. Passing target.name opts this target into the main
  // slug/version/target identity fields (read by station's descriptor -
  // see configDefinition).
  const { def: config, json: configJson } = configDefinition(model, target.name)
  const asData = isConfigData(configJson, configReprSetting(model))

  File({ name: 'config.' + target.ext }, () => {

    // ABOVE THE THRESHOLD: emit the model as DATA.
    //
    // The literal is one nested expression that Zig's comptime evaluator has
    // to walk in full at every build; a string constant is one token, and
    // `json_parse` (std.json at the boundary, then fromStdJson) builds the
    // same Value at runtime.
    //
    // The escaping is JSON.stringify's, which is valid Zig: it escapes every
    // backslash, so the JSON's own `\uXXXX` reaches the file as `\\uXXXX` and
    // no Zig escape sequence is ever formed from it.
    if (asData) {
      Content(`// Generated API configuration (mirrors go/rust core/config).

const std = @import("std");
const h = @import("helpers.zig");
const types = @import("types.zig");
const jsonparse = @import("../utility/jsonparse.zig");
const Value = h.Value;
const Feature = types.Feature;

/// THE API MODEL, EMBEDDED AS DATA (sdkgen rung L1).
///
/// Emitted only above a size threshold, or when \`main.kit.config.repr\` pins
/// it: for a small model the literal is smaller and far easier to read when
/// debugging.
const CONFIG_DATA: []const u8 = ${JSON.stringify(configJson)};

pub fn make_config() Value {
    // Unreachable on error: the constant is generated by a JSON serialiser and
    // never edited by hand. Panicking beats returning an empty config, which
    // would fail far from the cause.
    return jsonparse.json_parse(CONFIG_DATA) catch
        @panic("${model.const.Name}: embedded config is not valid JSON");
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Value nodes are arena-allocated and reference-stable, so the shared value is
// genuinely one structure, not a copy.
var shared_config_val: ?Value = null;

/// The process-wide config, built once on first use.
///
/// The returned Value SHARES its nodes: treat it as read-only. Callers that
/// need to mutate should use make_config, which always returns a fresh copy.
pub fn shared_config() Value {
    if (shared_config_val) |c| return c;
    const c = make_config();
    shared_config_val = c;
    return c;
}

pub fn make_feature(name: []const u8) Feature {
`)
    }
    else {

    Content(`// Generated API configuration (mirrors go/rust core/config).

const std = @import("std");
const h = @import("helpers.zig");
const types = @import("types.zig");
const Value = h.Value;
const Feature = types.Feature;

pub fn make_config() Value {
    return ${formatZigValue(config, 1)};
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Value nodes are arena-allocated and reference-stable, so the shared value is
// genuinely one structure, not a copy.
var shared_config_val: ?Value = null;

/// The process-wide config, built once on first use.
///
/// The returned Value SHARES its nodes: treat it as read-only. Callers that
/// need to mutate should use make_config, which always returns a fresh copy.
pub fn shared_config() Value {
    if (shared_config_val) |c| return c;
    const c = make_config();
    shared_config_val = c;
    return c;
}

pub fn make_feature(name: []const u8) Feature {
`)
    }

    // The factory must be able to instantiate any built-in feature by name,
    // not just the ones the current API model configures — a caller can enable
    // a shipped feature (e.g. netsim) purely through runtime options even when
    // the API def does not list it. The built-in set mirrors the feature
    // templates in tm/zig/feature/ (excluding `base`, the fallback, and
    // `support`, a helper module). Any model feature not already built in is
    // appended so bespoke features still resolve - and so does a GATED one
    // (`secrets`), whose source ships with the tree but whose `@import`s name
    // build modules that exist only when the model activates it: naming it
    // here unconditionally would make every zig SDK fail to build.
    const featureNames: string[] = [...BUILTIN_FEATURES]
    each(feature, (f: any) => {
      if (f.name !== 'base' && !featureNames.includes(f.name)) {
        featureNames.push(f.name)
      }
    })

    featureNames.forEach((name: string) => {
      const fname = name.charAt(0).toUpperCase() + name.slice(1)
      Content(`    if (std.mem.eql(u8, name, "${name}")) return @import("../feature/${name}.zig").${fname}Feature.make();
`)
    })

    Content(`    return @import("../feature/base.zig").BaseFeature.make();
}
`)
  })
})


// The features tm/zig/feature/ ships UNGATED: every zig SDK has their source
// and root.zig exports their types statically, so Config's factory can name
// them whatever the model says. Shared with Main_zig, which uses the same
// list to decide which ACTIVE features still need a root.zig export.
const BUILTIN_FEATURES = [
  'audit', 'cache', 'clienttrack', 'cost', 'debug', 'idempotency', 'log',
  'metrics', 'netsim', 'paging', 'proxy', 'ratelimit', 'rbac',
  'retry', 'streaming', 'telemetry', 'test', 'timeout',
]


// THE PLUGIN DEFINITIONS, as the root of the `sekretoplugins` build module:
// feature/<name>/plugins.zig (the zig peer of Config_go's featurePlugins map
// and of the plugins.rs index Main_rust emits).
//
// Upstream sekreto's contract since its registry was retired: a provider
// kind not handed to the constructor is unknown to that Sekreto. So this
// file IS the SDK's provider vocabulary - and in zig it is also what makes
// the plugin trim REAL: a module root reaches only what it names, so a kind
// missing here is neither in the vocabulary nor compiled, and a kind named
// here whose file the trim removed is a compile error rather than a silent
// one. That is exactly the shape upstream recommends for a lean consumer
// (plugins/all.zig: "roots its plugins module at the one file it needs").
//
// It sits one level ABOVE the vendored `plugins/` directory, deliberately:
// the vendoring guard fails any non-vendored file inside a vendored dir, and
// a zig module root reaches its whole SUBTREE, so `plugins/<kind>.zig` is
// within reach from here while the file itself is outside the guarded tree.
//
// Emitted only for a feature that is ACTIVE for this target (targetFeatures),
// which is also exactly when build.zig declares the module that roots here -
// an inactive model gets neither, so nothing dangles.
const FeaturePlugins = cmp(async function FeaturePlugins(props: any) {
  const ctx$ = props.ctx$
  const target = props.target
  const model: Model = ctx$.model

  const feature = targetFeatures(model, target)

  each(feature, (feat: any) => {
    // `only_active: false`, the subtlety pluginExcludesFor documents: the
    // feature object a component is handed has already been filtered, so a
    // feature whose plugins are ALL inactive would arrive with nothing here
    // and the module root build.zig points at would not be emitted at all.
    const declared = getModelPath(model,
      `main.${KIT}.feature.${feat.name}.plugin`,
      { required: false, only_active: false }) || {}

    if (0 === Object.keys(declared).length) {
      return
    }

    // symbol -> the file (target-root-relative) that exports it.
    const defs: Record<string, string> = {}

    each(declared, (plugin: any) => {
      // Filter on `active` HERE (Config_go's note): getting this wrong names
      // a file the trim just removed, which is a compile error.
      if (true !== plugin.active) return

      for (const [sym, one] of Object.entries(plugin.def?.zig || {})) {
        defs[sym] = String(one)
      }
    })

    Folder({ name: 'feature' }, () => {
      Folder({ name: feat.name }, () => {
        File({ name: 'plugins.' + target.ext }, () => {
          Content(`// The plugin definitions the model selected for the \`${feat.name}\`
// feature (generated - see Config_zig FeaturePlugins). The ROOT of the
// \`sekretoplugins\` build module: zig analyses only what a module root
// reaches, so a kind this file does not name is neither in the provider
// vocabulary nor compiled - this file IS the plugin trim.
//
// Upstream sekreto's contract since its registry was retired: a provider
// kind not handed to the constructor is unknown to that Sekreto.

const sekreto = @import("sekreto");

// The shared HTTP round-trip the vault kinds import by relative path, and
// the exchange's fetch of last resort (feature/${feat.name}.zig). In NO
// plugin group, so it is always reachable from here - which is what
// upstream's own all.zig does.
pub const httpjson = @import("plugins/httpjson.zig");

`)
          const syms = Object.keys(defs).sort()

          for (const sym of syms) {
            // 'feature/secrets/plugins/aws.zig' -> 'plugins/aws.zig', relative
            // to this file's directory (feature/<name>/).
            const rel = defs[sym].replace(new RegExp('^feature/' +
              feat.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '/'), '')
            Content(`pub const ${sym} = @import("${rel}").${sym};
`)
          }

          if (0 < syms.length) {
            Content(`
pub const SELECTED = [_]sekreto.Definition{
`)
            for (const sym of syms) {
              Content(`    ${sym},
`)
            }
            Content(`};
`)
          }
          else {
            Content(`// No plugin group is active: the chain can name the four built-in kinds
// (env, memory, dotenv, file) and nothing else.
pub const SELECTED = [_]sekreto.Definition{};
`)
          }
        })
      })
    })
  })
})


export {
  Config,
  FeaturePlugins,
  BUILTIN_FEATURES,
}
