
import * as Path from 'node:path'

import {
  cmp, each,
  File, Copy, Folder, Fragment,
} from '@voxgig/sdkgen'


import type {
  ModelEntity
} from '@voxgig/apidef'


import {
  KIT,
  getModelPath
} from '@voxgig/apidef'


import { Config } from './Config_zig'
import { Gitignore } from './Gitignore_zig'
import { MainEntity } from './MainEntity_zig'
import { Package } from './Package_zig'


const Main = cmp(async function Main(props: any) {

  const { target } = props
  const { model } = props.ctx$

  const entity: ModelEntity = getModelPath(model, `main.${KIT}.entity`)

  // build.zig.zon — the package manifest, stamped with the model package name.
  Package({ target })

  Gitignore({})

  // Copy tm/zig files with replacements. The tm src/ subtree only stages the
  // per-feature custom-source dirs (target add), so it is excluded here
  // exactly like the go/rust targets. build.zig.zon is generated by Package
  // (above), so it is excluded from the verbatim copy. The SDK source lives at
  // the tree root (core/, feature/, utility/, entity/, test/) — Zig's
  // idiomatic src/ is not used, to keep the exclude rule identical to the
  // reference targets.
  Copy({
    from: 'tm/' + target.name,
    exclude: [/src\//, /build\.zig\.zon$/],
    replace: {
      ...props.ctx$.stdrep,
    }
  })

  // Generated core files: the client (sdk.zig) and the API config. The
  // branded error type (error.zig) is a plain template (copied above).
  Folder({ name: 'core' }, () => {

    File({ name: 'sdk.' + target.ext }, () => {

      Fragment(
        {
          from: Path.normalize(__dirname + '/../../../src/cmp/zig/fragment/Main.fragment.zig'),
          replace: {
            ...props.ctx$.stdrep,
          }
        },

        // Entity accessors - injected at SLOT
        () => {
          each(entity, (ent: ModelEntity) => {
            MainEntity({ target, entity: ent })
          })
        })
    })

    Config({ target })
  })

})


export {
  Main
}
