import {
  Content,
  File,
  cmp,
  entitySpecMap,
  optionSpec,
} from '@voxgig/sdkgen'


import {
  Model,
} from '@voxgig/apidef'


// THE GENERATED SCHEMA MODULE: the model's schemas, as data the SDK can run.
//
// The zig peer of src/cmp/ts/Schema_ts.ts. Same two members, same source:
// optspec from `main.kit.optspec` plus each feature's own `config.options`,
// entityspec from the entity field sentinels — both built by the shared
// helpers, so what zig validates against and what ts validates against cannot
// drift.
//
// EMBEDDED AS JSON, PARSED AT LOAD, where ts emits an object literal: JSON is
// a subset of TypeScript's own literal syntax and is not a subset of zig's.
// A string constant, exactly as config.zig carries its data rep above the
// size threshold, and for the same reason — a nested `h.jo(...)` literal is
// one expression zig's comptime evaluator walks in full at every build. The
// spec has no threshold of its own because it is bounded by the option list
// and the feature set rather than by the API.
//
// The escaping is JSON.stringify's, which is valid Zig: it escapes every
// backslash, so the JSON's own `\uXXXX` reaches the file as `\\uXXXX` and no
// Zig escape sequence is ever formed from it.
//
// The round-trip is exact because the spec holds only strings and booleans:
// pinned by "strings and booleans only, so the JSON round-trip is lossless"
// in ts/test/optspec.test.ts.
const Schema = cmp(async function Schema(props: any) {
  const ctx$ = props.ctx$
  const target = props.target

  const model: Model = ctx$.model

  const optspec = optionSpec(model, target.name)
  const entityspec = entitySpecMap(model, target.name) || {}

  // Beside config.zig, in core, and for the same reason: core owns the
  // generated data, so nothing in utility or feature has to reach up for it.
  File({ name: 'schema.' + target.ext }, () => {

    Content(`// ${model.const.Name} SDK: generated schemas. Do not edit.
//
// Built from the model: \`main.kit.optspec\` and each feature's
// \`config.options\` for the option spec; entity \`fields[].type\` for the
// entity specs.

const h = @import("helpers.zig");
const jsonparse = @import("../utility/jsonparse.zig");
const Value = h.Value;

const OPTSPEC_DATA: []const u8 = ${JSON.stringify(JSON.stringify(optspec))};

const ENTITYSPEC_DATA: []const u8 = ${JSON.stringify(JSON.stringify(entityspec))};

/// The option spec make_options validates client options against.
///
/// Unreachable on error: the constant is generated by a JSON serialiser and
/// never edited by hand. Panicking beats returning an empty spec, which would
/// validate everything and fail far from the cause.
pub fn make_optspec() Value {
    return jsonparse.json_parse(OPTSPEC_DATA) catch
        @panic("${model.const.Name}: embedded option spec is not valid JSON");
}

/// Per-entity data and request specs, keyed by entity name.
pub fn make_entityspec() Value {
    return jsonparse.json_parse(ENTITYSPEC_DATA) catch
        @panic("${model.const.Name}: embedded entity spec is not valid JSON");
}

// SHARED SPECS, the shape config.shared_config uses and for the same reasons:
// the spec is read on every client construction and never mutated, so a
// per-call parse would be pure waste. Value nodes are arena-allocated and
// reference-stable, so the shared value is genuinely one structure.
//
// The returned Values SHARE their nodes: treat them as read-only.
// make_options validates AGAINST the spec and writes into the options, never
// into the spec.
var shared_optspec_val: ?Value = null;
var shared_entityspec_val: ?Value = null;

/// The process-wide option spec, built once on first use.
pub fn shared_optspec() Value {
    if (shared_optspec_val) |s| return s;
    const s = make_optspec();
    shared_optspec_val = s;
    return s;
}

/// The process-wide entity specs, built once on first use.
pub fn shared_entityspec() Value {
    if (shared_entityspec_val) |s| return s;
    const s = make_entityspec();
    shared_entityspec_val = s;
    return s;
}
`)
  })
})


export {
  Schema
}
