import { cmp, Content, File } from '@voxgig/sdkgen'

import {
  KIT,
  getModelPath,
} from '@voxgig/apidef'


// Emits lua/test/readme_examples_test.lua — a busted spec that (1) syntax
// checks every ```lua block in the module README AND the per-language
// REFERENCE.md with load(), and (2)
// EXECUTES every runnable block offline against the mock transport. Every
// client constructor in a block is rewritten to the seeded test-mode form
//   sdk.test({ entity = { <ent> = { test01 = { id = "test01" } } } })
// and fragments that only reference `client` get a seeded test client
// injected — so the documented call actually runs. A wrong example (a
// lowercase entity accessor after the API capitalised it, or any missing
// method) raises "call a nil value" at run and FAILS the test. Entity ops
// return a (value, err) tuple, so a fixture miss surfaces as a tolerated
// not-found domain error (e.g. "request: 404"), not a raised Lua error.
const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { ctx$: { model } } = props

  // Every active entity, keyed by its lowercase model name, is seeded with a
  // `test01` fixture whose id is `test01` — so a load({ id = "test01" }) in
  // the README resolves offline. Bracket-string keys keep the literal valid
  // for any entity name.
  const entity = getModelPath(model, `main.${KIT}.entity`) || {}
  const entnames = Object.values(entity)
    .filter((e: any) => e && e.active !== false)
    .map((e: any) => e.name)

  const seedEntries = entnames
    .map((n: string) => `["${n}"] = { ["test01"] = { id = "test01" } }`)
    .join(', ')
  const seedLiteral = `{ entity = { ${seedEntries} } }`

  File({ name: 'readme_examples_test.lua' }, () => {
    Content(`-- README lua example snippets check. Generated by @voxgig/sdkgen.
--
-- Two checks over every \`\`\`lua block in the module README and the
-- per-language REFERENCE.md:
--   1. Syntax: each block must compile with Lua's load() — catches
--      malformed example code (missing end, bad token, ...).
--   2. Offline run: every runnable block (one that builds a client or
--      references \`client\`) is EXECUTED with the mock transport (no
--      network). Each client constructor is rewritten to the seeded
--      test-mode form, and fragments that only use \`client\` get a seeded
--      test client injected. A call to a method that does not exist — e.g.
--      a lowercase entity accessor after the API capitalised it to
--      client:Entity() — raises "call a nil value" and FAILS the test.
--      Entity operations return a (value, err) tuple, so a seeded-fixture
--      miss surfaces as a normal (nil, err) not-found domain error, not a
--      raised Lua error, and is tolerated.

local SDK_MODULE = "${model.name}_sdk"

-- A test-mode client seeded with a fixture for every entity. The constructor
-- of each runnable snippet is rewritten to this form so the offline mock has
-- data to return.
local TEST_SEED = '${seedLiteral}'
local TEST_CTOR = "sdk.test(" .. TEST_SEED .. ")"

local function script_dir()
  local src = debug.getinfo(1, "S").source
  local path = src:sub(1, 1) == "@" and src:sub(2) or src
  return path:match("^(.*)[/\\\\][^/\\\\]*$") or "."
end

local function read_doc(filename)
  local dir = script_dir()
  local candidates = {
    dir .. "/../" .. filename,
    filename,
    "../" .. filename,
  }
  for _, p in ipairs(candidates) do
    local f = io.open(p, "r")
    if f then
      local data = f:read("*a")
      f:close()
      return data, p
    end
  end
  return nil
end

local function trim(s)
  return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

local function extract_blocks(md, lang)
  local blocks = {}
  local open = "\`\`\`" .. lang
  local in_block = false
  local cur = {}
  for line in (md .. "\\n"):gmatch("([^\\n]*)\\n") do
    local t = trim(line)
    if not in_block then
      if t == open then
        in_block = true
        cur = {}
      end
    else
      if t == "\`\`\`" then
        table.insert(blocks, table.concat(cur, "\\n"))
        in_block = false
      else
        table.insert(cur, line)
      end
    end
  end
  return blocks
end

-- A block is runnable if it builds a client (sdk.new / sdk.test) or uses one
-- (references \`client\`). Pure prose/other blocks are only syntax-checked.
local function is_runnable(block)
  return block:find("sdk%s*%.%s*new") ~= nil
    or block:find("sdk%s*%.%s*test") ~= nil
    or block:find("client") ~= nil
end

-- Transform a README block into an executable offline snippet: rewrite any
-- client constructor to the seeded test-mode form, inject a seeded client for
-- bare fragments, and ensure \`sdk\` is in scope.
local function make_runnable(block)
  local src = block

  local constructs = block:find("sdk%s*%.%s*new") ~= nil
    or block:find("sdk%s*%.%s*test") ~= nil

  if constructs then
    -- %b() matches a balanced ( ... ) argument list, so nested tables/parens
    -- in the original constructor call are replaced wholesale.
    src = src:gsub("sdk%s*%.%s*new%s*%b()", function() return TEST_CTOR end)
    src = src:gsub("sdk%s*%.%s*test%s*%b()", function() return TEST_CTOR end)
  end

  local prelude = {}
  if not src:find("require%s*%(") then
    table.insert(prelude, 'local sdk = require("' .. SDK_MODULE .. '")')
  end
  if not constructs and src:find("client") then
    table.insert(prelude, "local client = " .. TEST_CTOR)
  end

  if #prelude > 0 then
    src = table.concat(prelude, "\\n") .. "\\n" .. src
  end
  return src
end

-- Both docs are checked identically: the module README and the
-- per-language REFERENCE.md. Every \`\`\`lua block in each is syntax-checked,
-- and every runnable block is executed offline in test mode.
local DOCS = {
  { label = "README", file = "README.md" },
  { label = "REFERENCE", file = "REFERENCE.md" },
}

for _, doc in ipairs(DOCS) do
  describe("lua doc examples (" .. doc.label .. ")", function()
    local md = read_doc(doc.file)

    it(doc.file .. " is present", function()
      assert.is_not_nil(md, "could not read module " .. doc.file)
    end)

    if not md then
      return
    end

    local blocks = extract_blocks(md, "lua")

    it("has lua example blocks", function()
      assert.is_true(#blocks > 0, "no lua code blocks found in " .. doc.file)
    end)

    it("every lua block is syntactically valid", function()
      for i, block in ipairs(blocks) do
        local chunk, err = load(block, "=" .. doc.file .. "-lua-" .. i)
        assert.is_not_nil(chunk,
          doc.file .. " lua block #" .. i .. " has a syntax error: " ..
          tostring(err) .. "\\n----\\n" .. block .. "\\n----")
      end
    end)

    it("every runnable lua block runs offline in test mode", function()
      local ran = 0
      for i, block in ipairs(blocks) do
        if is_runnable(block) then
          local src = make_runnable(block)
          local chunk, err = load(src, "=" .. doc.file .. "-run-" .. i)
          assert.is_not_nil(chunk,
            doc.file .. " runnable block #" .. i .. " failed to compile: " ..
            tostring(err) .. "\\n----\\n" .. src .. "\\n----")
          local ok, e = pcall(chunk)
          if not ok then
            local msg = tostring(e)
            -- A nil accessor / missing method / bad index is a real doc
            -- bug: the documented call does not exist.
            if msg:find("nil value") or msg:find("attempt to call")
              or msg:find("attempt to index") then
              assert.is_true(false,
                doc.file .. " runnable block #" .. i .. " hit a runtime " ..
                "error (missing method / nil call): " .. msg ..
                "\\n----\\n" .. src .. "\\n----")
            end
            -- Other runtime errors (a seeded-fixture miss surfaces as a
            -- tolerated not-found domain error, e.g. "request: 404: Not
            -- found") are expected offline and tolerated.
          end
          ran = ran + 1
        end
      end
      assert.is_true(ran > 0,
        "expected at least one runnable lua block in " .. doc.file)
    end)
  end)
end
`)
  })

})


export {
  ReadmeExamplesTest
}
