import { cmp, Content, File } from '@voxgig/sdkgen'


// Emits lua/test/readme_examples_test.lua — a busted spec that (1) syntax
// checks every ```lua block in the module README via load(), and (2)
// runs the offline (sdk.test()) snippets. A wrong example — a lowercase
// entity accessor after the API capitalised it, or any missing method —
// raises "call a nil value" at run and fails the test. Entity ops return
// (value, err) tuples, so a missing fixture is a normal return, tolerated.
const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { ctx$: { model } } = props

  File({ name: 'readme_examples_test.lua' }, () => {
    Content(`-- README lua example snippets check. Generated by @voxgig/sdkgen.
--
-- Two checks over every \`\`\`lua block in the module README:
--   1. Syntax: each block must compile with Lua's load() — catches
--      malformed example code (missing end, bad token, ...).
--   2. Offline run: blocks that build a test-mode client (sdk.test())
--      are executed with the mock transport (no network). A call to a
--      method that does not exist — e.g. a lowercase entity accessor
--      after the API capitalised it to client:Entity() — raises "call a
--      nil value" and fails the test. Entity operations return a
--      (value, err) tuple, so a missing fixture is a normal nil+err
--      return, not a raised error, and is tolerated.

local SDK_MODULE = "${model.name}_sdk"

local function script_dir()
  local src = debug.getinfo(1, "S").source
  local path = src:sub(1, 1) == "@" and src:sub(2) or src
  return path:match("^(.*)[/\\\\][^/\\\\]*$") or "."
end

local function read_readme()
  local dir = script_dir()
  local candidates = {
    dir .. "/../README.md",
    "README.md",
    "../README.md",
  }
  for _, p in ipairs(candidates) do
    local f = io.open(p, "r")
    if f then
      local data = f:read("*a")
      f:close()
      return data, p
    end
  end
  return nil
end

local function trim(s)
  return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

local function extract_blocks(md, lang)
  local blocks = {}
  local open = "\`\`\`" .. lang
  local in_block = false
  local cur = {}
  for line in (md .. "\\n"):gmatch("([^\\n]*)\\n") do
    local t = trim(line)
    if not in_block then
      if t == open then
        in_block = true
        cur = {}
      end
    else
      if t == "\`\`\`" then
        table.insert(blocks, table.concat(cur, "\\n"))
        in_block = false
      else
        table.insert(cur, line)
      end
    end
  end
  return blocks
end

describe("README lua examples", function()
  local md = read_readme()

  it("README is present", function()
    assert.is_not_nil(md, "could not read module README.md")
  end)

  if not md then
    return
  end

  local blocks = extract_blocks(md, "lua")

  it("has lua example blocks", function()
    assert.is_true(#blocks > 0, "no lua code blocks found in README")
  end)

  it("every lua block is syntactically valid", function()
    for i, block in ipairs(blocks) do
      local chunk, err = load(block, "=readme-lua-" .. i)
      assert.is_not_nil(chunk,
        "lua block #" .. i .. " has a syntax error: " .. tostring(err) ..
        "\\n----\\n" .. block .. "\\n----")
    end
  end)

  it("test-mode snippets run offline", function()
    local ran = 0
    for i, block in ipairs(blocks) do
      if block:find("sdk%.test%s*%(") then
        local src = block
        if not block:find("require%s*%(") then
          src = 'local sdk = require("' .. SDK_MODULE .. '")\\n' .. block
        end
        local chunk, err = load(src, "=readme-run-" .. i)
        assert.is_not_nil(chunk,
          "test-mode block #" .. i .. " failed to compile: " .. tostring(err))
        local ok, e = pcall(chunk)
        if not ok then
          local msg = tostring(e)
          -- A nil accessor / missing method is a real README bug.
          if msg:find("nil value") or msg:find("attempt to call")
            or msg:find("attempt to index") then
            assert.is_true(false,
              "test-mode block #" .. i .. " called a missing method: " ..
              msg .. "\\n----\\n" .. src .. "\\n----")
          end
          -- Other runtime errors (missing fixture, offline transport)
          -- are tolerated: the snippet's call shape is still valid.
        end
        ran = ran + 1
      end
    end
    assert.is_true(ran > 0,
      "expected at least one offline (sdk.test()) snippet in the README")
  end)
end)
`)
  })

})


export {
  ReadmeExamplesTest
}
