
import { cmp, File, Content } from '@voxgig/sdkgen'

import { kotlinPackage } from './utility_kotlin'


// Emits test/ReadmeExamplesTest.kt — a JUnit PRESENCE + STRUCTURE gate over
// every ```kotlin fenced block in the repository ROOT README.md, the
// per-language kotlin/README.md, AND the per-language kotlin/REFERENCE.md.
//
// SCOPE NOTE (deliberate, documented): the Python/TS/Go equivalents EXECUTE and
// type-check every documented block. That is infeasible here — the generated
// Kotlin SDK compiles with Gradle/kotlinc only (no in-process Kotlin compiler
// dependency wired into the test classpath), so a test cannot compile-and-run
// arbitrary doc snippets at test time. This gate therefore guarantees the
// weaker-but-real invariant that keeps the docs honest as the generator evolves:
//   1. every doc exists and contains at least one ```kotlin block (nothing was
//      dropped);
//   2. every ```kotlin block is structurally well-formed — its braces,
//      parentheses and brackets balance (catches a truncated or malformed
//      generated snippet).
// A per-doc summary line makes the coverage visible in the test output.
//
// The emitted Kotlin is written WITHOUT literal backticks (the fence marker is
// built at runtime as 96.toChar().toString().repeat(3)) so this TS template
// literal stays clean.
const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { target, ctx$: { model } } = props

  const Name = model.const.Name
  const kotlinpackage = props.kotlinpackage || kotlinPackage(model)

  File({ name: 'ReadmeExamplesTest.' + target.ext }, () => {
    Content(`package ${kotlinpackage}.sdktest

// ${Name} SDK — documentation kotlin-examples PRESENCE + STRUCTURE gate.
//
// GUARANTEE (see ReadmeExamplesTest_kotlin.ts for why this is a structure gate
// and not an execute gate): every kotlin example in the docs is accounted for.
// This JUnit class is a completeness gate over every ${'```'}kotlin fenced code
// block in three documents:
//   - the repository ROOT README.md (one directory above this module),
//   - the per-language kotlin/README.md,
//   - the per-language kotlin/REFERENCE.md.
//
// Checks, PER DOCUMENT:
//   1. PRESENCE: the doc exists and holds at least one kotlin block.
//   2. STRUCTURE: every kotlin block's braces / parens / brackets balance, so a
//      truncated or malformed generated snippet fails loudly.
//
// GENERATED by @voxgig/sdkgen — do not edit by hand.

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths

class ReadmeExamplesTest {

  // The three documents to scan, resolved relative to the Gradle module
  // directory (the working directory when the test task runs). Each row is
  // {label, relative path}.
  private fun docs(): Array<Array<String>> {
    return arrayOf(
      arrayOf("root README", ".." + File.separator + "README.md"),
      arrayOf("kotlin README.md", "README.md"),
      arrayOf("kotlin REFERENCE.md", "REFERENCE.md"),
    )
  }

  // Extract every kotlin fenced block. Split on the triple-backtick fence:
  // odd-indexed segments are the inside of a fenced block (info string on the
  // first line, then the code). Only blocks whose info string is exactly
  // "kotlin" are returned.
  private fun kotlinBlocks(text: String): List<String> {
    val fence = 96.toChar().toString().repeat(3)
    val parts = text.split(fence)
    val blocks = mutableListOf<String>()
    var i = 1
    while (i < parts.size) {
      val seg = parts[i]
      val nl = seg.indexOf('\\n')
      val info = (if (nl < 0) seg else seg.substring(0, nl)).trim()
      if (info == "kotlin") {
        blocks.add(if (nl < 0) "" else seg.substring(nl + 1))
      }
      i += 2
    }
    return blocks
  }

  private fun readDoc(path: Path, label: String): String {
    assertTrue(Files.exists(path), label + " not found: " + path)
    return Files.readString(path)
  }

  // True when every open/close delimiter balances (ignores the subtlety of
  // delimiters inside string literals — a generated snippet never nests an
  // unbalanced delimiter in a string, and this catches truncation).
  private fun balanced(block: String): Boolean {
    val stack = ArrayDeque<Char>()
    val pairs = mapOf('(' to ')', '[' to ']', '{' to '}')
    for (ch in block) {
      if (pairs.containsKey(ch)) {
        stack.addLast(pairs[ch]!!)
      }
      else if (ch == ')' || ch == ']' || ch == '}') {
        if (stack.isEmpty() || stack.removeLast() != ch) {
          return false
        }
      }
    }
    return stack.isEmpty()
  }

  @Test
  fun rootReadmeHasKotlinBlocks() {
    val doc = docs()[0]
    val blocks = kotlinBlocks(readDoc(Paths.get(doc[1]), doc[0]))
    assertTrue(blocks.size > 0, "expected at least one kotlin block in " + doc[0])
  }

  @Test
  fun localReadmeHasKotlinBlocks() {
    val doc = docs()[1]
    val blocks = kotlinBlocks(readDoc(Paths.get(doc[1]), doc[0]))
    assertTrue(blocks.size > 0, "expected at least one kotlin block in " + doc[0])
  }

  @Test
  fun referenceHasKotlinBlocks() {
    val doc = docs()[2]
    val blocks = kotlinBlocks(readDoc(Paths.get(doc[1]), doc[0]))
    assertTrue(blocks.size > 0, "expected at least one kotlin block in " + doc[0])
  }

  @Test
  fun allKotlinBlocksAreStructurallyBalanced() {
    val failures = mutableListOf<String>()
    for (doc in docs()) {
      val path = Paths.get(doc[1])
      if (!Files.exists(path)) {
        continue
      }
      val blocks = kotlinBlocks(readDoc(path, doc[0]))
      var balancedCount = 0
      for (i in blocks.indices) {
        if (balanced(blocks[i])) {
          balancedCount++
        }
        else {
          failures.add(doc[0] + " kotlin block #" + i +
              " has unbalanced delimiters:\\n\\n" + blocks[i])
        }
      }
      println(
          "[readme-examples] " + doc[0] + " kotlin blocks: total=" +
          blocks.size + " balanced=" + balancedCount)
    }
    assertTrue(failures.isEmpty(), failures.joinToString("\\n\\n"))
  }
}
`)
  })
})


export {
  ReadmeExamplesTest
}
