;; ProjectName SDK client (generated by @voxgig/sdkgen).
;;
;; The client is a plain map holding atoms for its mutable slots (features,
;; mode, options, per-feature tracking store, root context). This lets it be
;; shared by reference through the pipeline context while its slots mutate in
;; place. make-sdk / test-sdk construct it; direct / prepare are the raw-HTTP
;; escape hatch.

(ns sdk.client
  (:require [sdk.core :as core]
            [sdk.features :as features]
            [sdk.config :as config]
            [voxgig.struct :as vs]
            [clojure.string :as str]))

(defn make-sdk [options]
  (let [options (or options (vs/jm))
        utility (core/make-utility)
        cfg (config/make-config)
        client {:features (atom []) :mode (atom "live") :store (atom {})
                :options (atom (vs/jm)) :root-ctx (atom nil) :utility utility}
        rootctx (core/make-context
                 (vs/jm "client" client "utility" utility "config" cfg "options" options "shared" (vs/jm)) nil)
        validated ((core/uget rootctx :make-options) rootctx)]
    (reset! (:root-ctx client) rootctx)
    (reset! (:options client) validated)
    (when (= true (vs/getpath validated "feature.test.active"))
      (reset! (:mode client) "test"))
    (core/oset! rootctx :options validated)
    ;; Add features in the resolved order (make-options records an explicit
    ;; array order, else defaults to test-first). Ordering matters: the `test`
    ;; feature installs the base mock transport and the transport features
    ;; (retry/cache/netsim/proxy/ratelimit) wrap whatever is current, so
    ;; `test` must be added before them to sit at the base of the chain.
    (let [feature-opts (let [f (core/to-map (vs/getprop validated "feature"))] (or f (vs/jm)))
          feature-order (let [o (vs/getpath validated "__derived__.featureorder")]
                          (if (vs/islist o) (vec o) []))]
      (doseq [fname feature-order]
        (let [fopts (core/to-map (vs/getprop feature-opts fname))]
          (when (and fopts (= true (vs/getprop fopts "active")))
            ((core/uget rootctx :feature-add) rootctx (features/make-feature fname))))))
    ;; Extension features (feature atoms supplied via options.extend).
    (let [extend-val (vs/getprop validated "extend")]
      (when (vs/islist extend-val)
        (doseq [f (vec extend-val)]
          (when (instance? clojure.lang.Atom f)
            ((core/uget rootctx :feature-add) rootctx f)))))
    ;; Initialise features (init only fires for active ones).
    (doseq [f (deref (:features client))]
      ((core/uget rootctx :feature-init) rootctx f))
    ((core/uget rootctx :feature-hook) rootctx "PostConstruct")
    client))

(defn options-map [client] (core/client-options-map client))
(defn get-utility [client] (core/get-utility client))
(defn get-root-ctx [client] (core/client-root-ctx client))

(defn prepare [client fetchargs]
  (let [utility (core/client-utility client)
        fetchargs (or fetchargs (vs/jm))
        ctrl (let [c (core/to-map (vs/getprop fetchargs "ctrl"))] (if c c (vs/jm)))
        ctx (core/make-context (vs/jm "opname" "prepare" "ctrl" ctrl) (core/client-root-ctx client))
        opts (deref (:options client))
        path0 (vs/getprop fetchargs "path")
        path (if (string? path0) path0 "")
        method0 (vs/getprop fetchargs "method")
        method (if (string? method0) method0 "GET")
        params (let [p (core/to-map (vs/getprop fetchargs "params"))] (if p p (vs/jm)))
        query (let [q (core/to-map (vs/getprop fetchargs "query"))] (if q q (vs/jm)))
        headers ((core/uget ctx :prepare-headers) ctx)
        gstr (fn [k] (let [v (vs/getprop opts k)] (if (string? v) v "")))
        spec (core/make-spec (vs/jm "base" (gstr "base") "prefix" (gstr "prefix") "suffix" (gstr "suffix")
                                    "path" path "method" method "params" params "query" query
                                    "headers" headers "body" (vs/getprop fetchargs "body") "step" "start"))]
    (core/oset! ctx :spec spec)
    (let [uh (vs/getprop fetchargs "headers")]
      (when (vs/ismap uh)
        (doseq [item (or (vs/items uh) [])]
          (.put ^java.util.Map (core/oget spec :headers) (vs/getprop item 0) (vs/getprop item 1)))))
    (let [[_ err] ((core/uget ctx :prepare-auth) ctx)]
      (when err (core/sdk-throw err)))
    (let [[fetchdef fd-err] ((core/uget ctx :make-fetch-def) ctx)]
      (when fd-err (core/sdk-throw fd-err))
      fetchdef)))

(defn direct [client fetchargs]
  (let [utility (core/client-utility client)
        fetchargs (or fetchargs (vs/jm))
        pr (try {:fd (prepare client fetchargs)}
                (catch clojure.lang.ExceptionInfo e {:err (core/ex->sdk e)}))]
    (if (:err pr)
      (vs/jm "ok" false "err" (:err pr))
      (let [fetchdef (:fd pr)
            ctrl (let [c (core/to-map (vs/getprop fetchargs "ctrl"))] (if c c (vs/jm)))
            ctx (core/make-context (vs/jm "opname" "direct" "ctrl" ctrl) (core/client-root-ctx client))
            url (or (vs/getprop fetchdef "url") "")
            [fetched fetch-err] ((core/uget ctx :fetcher) ctx url fetchdef)]
        (cond
          fetch-err (vs/jm "ok" false "err" fetch-err)
          (nil? fetched) (vs/jm "ok" false "err" (core/ctx-error ctx "direct_no_response" "response: undefined"))
          (vs/ismap fetched)
          (let [status (core/to-int (vs/getprop fetched "status"))
                headers (or (vs/getprop fetched "headers") (vs/jm))
                content-length (when (vs/ismap headers) (vs/getprop headers "content-length"))
                no-body (or (= status 204) (= status 304) (= (str content-length) "0"))
                json-data (when-not no-body
                            (let [jf (vs/getprop fetched "json")]
                              (when (fn? jf) (try (jf) (catch Throwable _ nil)))))]
            (vs/jm "ok" (and (>= status 200) (< status 300)) "status" status "headers" headers "data" json-data))
          :else (vs/jm "ok" false "err" (core/ctx-error ctx "direct_invalid" "invalid response type")))))))

(defn test-sdk [testopts sdkopts]
  (let [sdkopts (let [c (vs/clone (or sdkopts (vs/jm)))] (if (vs/ismap c) c (vs/jm)))
        testopts (let [c (vs/clone (or testopts (vs/jm)))] (if (vs/ismap c) c (vs/jm)))]
    (.put ^java.util.Map testopts "active" true)
    (vs/setpath sdkopts "feature.test" testopts)
    (let [sdk (make-sdk sdkopts)]
      (core/client-set-mode! sdk "test")
      sdk)))
