;; ProjectName SDK core runtime (generated by @voxgig/sdkgen).
;;
;; Clojure is functional with immutable values, but the operation pipeline is
;; a shared-mutable-state machine: feature hooks observe and modify the
;; context, result and control across pipeline stages, and transport-wrapping
;; features replace the fetcher in place. That shared mutable state is modelled
;; with atoms — the context and every mutable sub-object (control, spec,
;; result, response, operation, the `out` short-circuit map, the utility
;; object and the client) are atoms wrapping a map. The DATA those atoms carry
;; (options, config, headers, request/response bodies, match/data) are struct
;; value nodes (java.util.LinkedHashMap / ArrayList) built and manipulated by
;; the vendored voxgig.struct library, exactly as the reference SDK uses
;; mutable hashes/arrays.

(ns sdk.core
  (:require [voxgig.struct :as vs]
            [sdk.schema :as schema]
            [clojure.string :as str]))

(def SDK-NAME "ProjectName")

;; ---------------------------------------------------------------------------
;; Minimal JSON reader -> struct nodes (LinkedHashMap / ArrayList / Long /
;; Double / String / Boolean / nil). Shared by the live transport and tests.
;; ---------------------------------------------------------------------------

(defn json-parse [^String s]
  (let [n (count s) pos (int-array 1)]
    (letfn [(peek-c [] (when (< (aget pos 0) n) (.charAt s (aget pos 0))))
            (next-c [] (let [c (.charAt s (aget pos 0))] (aset pos 0 (inc (aget pos 0))) c))
            (skip-ws [] (while (and (< (aget pos 0) n) (Character/isWhitespace (.charAt s (aget pos 0))))
                          (aset pos 0 (inc (aget pos 0)))))
            (parse-val []
              (skip-ws)
              (let [c (peek-c)]
                (cond (= c \{) (parse-obj) (= c \[) (parse-arr) (= c \") (parse-str)
                      (or (= c \t) (= c \f)) (parse-bool) (= c \n) (parse-null) :else (parse-num))))
            (parse-obj []
              (next-c)
              (let [m (java.util.LinkedHashMap.)]
                (skip-ws)
                (if (= (peek-c) \}) (do (next-c) m)
                    (loop [] (skip-ws)
                      (let [k (parse-str)] (skip-ws) (next-c)
                        (.put m k (parse-val)) (skip-ws)
                        (if (= (next-c) \,) (recur) m))))))
            (parse-arr []
              (next-c)
              (let [a (java.util.ArrayList.)]
                (skip-ws)
                (if (= (peek-c) \]) (do (next-c) a)
                    (loop [] (.add a (parse-val)) (skip-ws)
                      (if (= (next-c) \,) (recur) a)))))
            (parse-str []
              (next-c)
              (let [sb (StringBuilder.)]
                (loop []
                  (let [c (next-c)]
                    (cond
                      (= c \") (.toString sb)
                      (= c \\) (let [e (next-c)]
                                 (case e
                                   \" (.append sb \") \\ (.append sb \\) \/ (.append sb \/)
                                   \n (.append sb \newline) \t (.append sb \tab) \r (.append sb \return)
                                   \b (.append sb \backspace) \f (.append sb \formfeed)
                                   \u (let [hex (subs s (aget pos 0) (+ (aget pos 0) 4))]
                                        (aset pos 0 (+ (aget pos 0) 4))
                                        (.append sb (char (Integer/parseInt hex 16))))
                                   (.append sb e))
                                 (recur))
                      :else (do (.append sb c) (recur)))))))
            (parse-bool []
              (if (= (peek-c) \t) (do (aset pos 0 (+ (aget pos 0) 4)) true)
                  (do (aset pos 0 (+ (aget pos 0) 5)) false)))
            (parse-null [] (aset pos 0 (+ (aget pos 0) 4)) nil)
            (parse-num []
              (let [start (aget pos 0)]
                (while (and (< (aget pos 0) n)
                            (let [c (.charAt s (aget pos 0))]
                              (or (Character/isDigit c) (= c \-) (= c \+) (= c \.) (= c \e) (= c \E))))
                  (aset pos 0 (inc (aget pos 0))))
                (let [tok (subs s start (aget pos 0))]
                  (if (or (.contains tok ".") (.contains tok "e") (.contains tok "E"))
                    (Double/parseDouble tok)
                    ;; A JSON integer may exceed the signed 64-bit range - an
                    ;; OpenAPI `default`/`example` can carry any integer. The
                    ;; Clojure reader gives the literal branch a BigInt for
                    ;; such a token, so parseLong alone would make the two
                    ;; representations disagree by throwing on input the
                    ;; literal accepts.
                    (try (Long/parseLong tok)
                         (catch NumberFormatException _
                           (bigint (java.math.BigInteger. tok))))))))]
      (parse-val))))

;; The option spec, parsed ONCE. sdk.schema holds the raw JSON and nothing
;; else — it cannot parse its own data without requiring this namespace,
;; which would close a cycle — so the parse lives here, behind a delay so it
;; happens on first use rather than at load.
;;
;; sdk.schema also carries `entityspec-data`, the per-entity field specs the
;; `validate` feature checks payloads against. Parsed here for the same
;; reason and behind the same delay; `entityspec` is public because the
;; feature module reads it, and it is READ-ONLY — validate rebuilds the tree
;; for `strict` rather than mutating this one.
(def ^:private optspec-parsed (delay (json-parse schema/optspec-data)))
(def ^:private entityspec-parsed (delay (json-parse schema/entityspec-data)))

(defn entityspec [] @entityspec-parsed)

;; ---------------------------------------------------------------------------
;; Atom-object helpers. Every mutable "object" is an atom wrapping a map.
;; ---------------------------------------------------------------------------

(defn oget
  ([a k] (get (deref a) k))
  ([a k d] (let [v (get (deref a) k)] (if (nil? v) d v))))

(defn oset! [a k v] (swap! a assoc k v) v)
(defn oupd! [a k f & args] (swap! a (fn [m] (assoc m k (apply f (get m k) args)))))

;; Read a value from a java.util.Map (both clojure maps and LinkedHashMap
;; implement java.util.Map, so this is uniform for struct nodes and literals).
(defn mget
  ([m k] (when (instance? java.util.Map m) (.get ^java.util.Map m k)))
  ([m k d] (let [v (mget m k)] (if (nil? v) d v))))

(defn to-map [v] (when (vs/ismap v) v))
(defn to-int [v] (if (number? v) (long v) -1))

;; ---------------------------------------------------------------------------
;; SDK error. Represented as a plain map flowing through [value err] tuples;
;; raised (where the reference implementation raises) via ex-info carrying the
;; error map under ::sdk-error.
;; ---------------------------------------------------------------------------

;; The context rides in the map's METADATA, not as a key: the error is data
;; and `pr-str`/`ex-data` print every key, and the context holds the live
;; spec and options. Reachable through `err-ctx` for a debugger, invisible to
;; every printer.
(defn make-error-obj
  ([code msg] (make-error-obj code msg nil))
  ([code msg ctx]
   (with-meta {:sdk-error true :sdk SDK-NAME :code (or code "") :msg (or msg "")
               :result nil :spec nil}
     {:ctx ctx})))

(defn sdk-error? [x] (and (map? x) (true? (:sdk-error x))))
(defn err-ctx [e] (when (sdk-error? e) (:ctx (meta e))))
(defn err-msg [e]
  (cond
    (sdk-error? e) (:msg e)
    (instance? Throwable e) (.getMessage ^Throwable e)
    ;; A plain error map carrying a message — what a response body or a
    ;; caller-supplied err looks like. The neutral contract spells it
    ;; "message"; without this it fell to (str e) and result-basic reported
    ;; "{message=Foo}: request: 400: BAD" where ts reports "Foo: request: ...".
    ;; java.util.Map, not just clojure's — a struct map is a LinkedHashMap, so
    ;; `map?` is false for exactly the values the corpus supplies.
    (instance? java.util.Map e)
    (let [m (or (.get ^java.util.Map e "message") (.get ^java.util.Map e "msg")
                (get e :message) (get e :msg))]
      ;; An error map with no message IS an unknown error; stringifying it gave
      ;; "{}" where every other target reports "unknown error".
      (if (and (some? m) (not= "" (str m))) (str m) "unknown error"))
    :else (str e)))
(defn err-code [e] (when (sdk-error? e) (:code e)))
(defn sdk-throw [e] (throw (ex-info (err-msg e) {::sdk-error (if (sdk-error? e) e (make-error-obj "" (str e)))})))
(defn ex->sdk [t] (::sdk-error (ex-data t)))

;; ctx.make_error(code, msg)
(defn ctx-error [ctx code msg] (make-error-obj code msg ctx))

;; ---------------------------------------------------------------------------
;; Client accessors. A client is a plain map holding atoms (so it is shared by
;; reference; the atoms carry the mutable slots).
;; ---------------------------------------------------------------------------

(defn client-mode [client] (deref (:mode client)))
(defn client-set-mode! [client m] (reset! (:mode client) m))
(defn client-features [client] (:features client)) ;; atom of vector
(defn client-options-map [client]
  (let [o (vs/clone (deref (:options client)))] (if (vs/ismap o) o (vs/jm))))
(defn client-track [client k] (get (deref (:store client)) k))
(defn client-track-set! [client k v] (swap! (:store client) assoc k v) v)
(defn client-track-update! [client k f] (swap! (:store client) update k f))
(defn client-root-ctx [client] (deref (:root-ctx client)))
(defn client-utility [client] (:utility client))

;; ---------------------------------------------------------------------------
;; Utility object: an atom wrapping a map of pipeline functions plus :struct,
;; :custom and the swappable :fetcher. Sibling functions are always looked up
;; through the atom (uget) so a feature-wrapped fetcher or an overridden member
;; is honoured.
;; ---------------------------------------------------------------------------

(declare base-utility-map)

(defn make-utility []
  (atom (assoc (base-utility-map) :struct (vs/struct-utility) :custom (vs/jm))))

(defn utility-copy [u]
  (let [m (deref u)]
    (atom (assoc m :custom (let [c (:custom m)] (if (vs/ismap c) (vs/clone c) (vs/jm)))))))

;; get_utility: entity clients operate through a private copy of the utility.
(defn get-utility [client] (utility-copy (:utility client)))

(defn uget [ctx k] (get (deref (oget ctx :utility)) k))
(defn ucall [ctx k & args] (apply (uget ctx k) ctx args))

;; ---------------------------------------------------------------------------
;; Operation (atom-map): entity, name, input, points, alias.
;; ---------------------------------------------------------------------------

(defn make-operation [opmap]
  (let [opmap (or opmap (vs/jm))
        e (vs/getprop opmap "entity")
        n (vs/getprop opmap "name")
        i (vs/getprop opmap "input")
        raw-points (vs/getprop opmap "points")
        raw-alias (vs/getprop opmap "alias")]
    (atom {:entity (if (and (string? e) (seq e)) e "_")
           :name   (if (and (string? n) (seq n)) n "_")
           :input  (if (and (string? i) (seq i)) i "_")
           :points (cond (vs/islist raw-points)
                         (let [a (vs/jt)] (doseq [t raw-points] (when (vs/ismap t) (.add ^java.util.List a t))) a)
                         :else (vs/jt))
           :alias  (when (vs/ismap raw-alias) raw-alias)})))

(defn op-name [op] (when op (:name (deref op))))
(defn op-entity [op] (when op (:entity (deref op))))
(defn op-input [op] (when op (:input (deref op))))
(defn op-points [op] (when op (:points (deref op))))
(defn op-alias [op] (when op (:alias (deref op))))

;; ---------------------------------------------------------------------------
;; Spec (atom-map).
;; ---------------------------------------------------------------------------

(defn make-spec [specmap]
  (let [m (or specmap (vs/jm))
        g (fn [k d] (let [v (mget m k)] (if (nil? v) d v)))]
    (atom {:parts   (g "parts" (vs/jt))
           :headers (g "headers" (vs/jm))
           :alias   (g "alias" (vs/jm))
           :base    (g "base" "")
           :prefix  (g "prefix" "")
           :suffix  (g "suffix" "")
           :params  (g "params" (vs/jm))
           :query   (g "query" (vs/jm))
           :step    (g "step" "start")
           :method  (g "method" "GET")
           :body    (g "body" nil)
           :url     (g "url" "")
           :path    (g "path" "")
           ;; The query parameters prepare-auth placed: the credential, which
           ;; the request sends and the entity's match leaves out.
           :authquery (g "authquery" [])})))

;; ---------------------------------------------------------------------------
;; Result (atom-map).
;; ---------------------------------------------------------------------------

(defn make-result [resmap]
  (let [m (or resmap (vs/jm))
        g (fn [k] (mget m k))
        s (g "status")
        st (g "statusText")
        h (g "headers")
        rm (g "resmatch")]
    (atom {:ok (= true (g "ok"))
           :status (if (number? s) (long s) -1)
           :status-text (if (string? st) st "")
           :headers (if (vs/ismap h) h (vs/jm))
           :body (g "body")
           :err (g "err")
           :resdata (g "resdata")
           :resmatch (when (vs/ismap rm) rm)
           :paging nil :streaming nil :stream nil})))

;; ---------------------------------------------------------------------------
;; Response (atom-map).
;; ---------------------------------------------------------------------------

(defn make-response [resmap]
  (let [m (or resmap (vs/jm))
        g (fn [k] (mget m k))
        s (g "status")
        st (g "statusText")
        jf (g "json")]
    (atom {:status (if (number? s) (long s) -1)
           :status-text (if (string? st) st "")
           :headers (g "headers")
           :json (when (vs/isfunc jf) jf)
           :body (g "body")
           :err (g "err")})))

;; ---------------------------------------------------------------------------
;; Control (atom-map). Shared with the base context when not overridden.
;; ---------------------------------------------------------------------------

(defn make-control [] (atom {:throw nil :err nil :explain nil :actor nil :paging nil}))

;; ---------------------------------------------------------------------------
;; Context (atom-map).
;; ---------------------------------------------------------------------------

(declare resolve-op)

(defn make-context [ctxmap basectx]
  (let [ctxmap (or ctxmap (vs/jm))
        bget (fn [k] (when basectx (oget basectx k)))
        cprop (fn [k] (mget ctxmap k))
        client (or (cprop "client") (bget :client))
        utility (or (cprop "utility") (bget :utility))
        ;; ctrl: explicit ctrl map -> fresh control; an OPERATION (one named by
        ;; opname) also gets its own, so a paging cursor cannot leak into the
        ;; next call; anything else shares the base ctrl.
        ctrl-raw (cprop "ctrl")
        ctrl (cond
               (vs/ismap ctrl-raw)
               (let [c (make-control)]
                 (when (contains? (into #{} (vs/keysof ctrl-raw)) "throw") (oset! c :throw (mget ctrl-raw "throw")))
                 (when (vs/ismap (mget ctrl-raw "explain")) (oset! c :explain (mget ctrl-raw "explain")))
                 (when (contains? (into #{} (vs/keysof ctrl-raw)) "actor") (oset! c :actor (mget ctrl-raw "actor")))
                 (when (vs/ismap (mget ctrl-raw "paging")) (oset! c :paging (mget ctrl-raw "paging")))
                 c)
               (and (nil? (cprop "opname")) (bget :ctrl)) (bget :ctrl)
               :else (make-control))
        meta (let [m (cprop "meta")] (if (vs/ismap m) m (or (bget :meta) (vs/jm))))
        config (let [c (cprop "config")] (if (vs/ismap c) c (bget :config)))
        entopts (let [e (cprop "entopts")] (if (vs/ismap e) e (bget :entopts)))
        options (let [o (cprop "options")] (if (vs/ismap o) o (bget :options)))
        entity (or (cprop "entity") (bget :entity))
        shared (let [s (cprop "shared")] (if (vs/ismap s) s (bget :shared)))
        opmap (or (cprop "opmap") (bget :opmap) (atom {}))
        dmap (fn [k] (let [v (mget ctxmap k)] (if (vs/ismap v) v (vs/jm))))
        point (let [p (cprop "point")] (if (vs/ismap p) p (bget :point)))
        spec (let [s (cprop "spec")] (if (some? s) s (bget :spec)))
        result (let [r (cprop "result")] (if (some? r) r (bget :result)))
        response (let [r (cprop "response")] (if (some? r) r (bget :response)))
        opname (or (cprop "opname") "")
        ;; `:type` metadata routes print-method to the cleaned record (see
        ;; ctx->data): a bare atom prints its whole value, spec and options
        ;; included.
        ctx (atom {:id (str "C" (+ 10000000 (rand-int 89999999)))
                   :out (atom (vs/jm))
                   :client client :utility utility :ctrl ctrl :meta meta
                   :config config :entopts entopts :options options :entity entity
                   :shared shared :opmap opmap
                   :data (dmap "data") :reqdata (dmap "reqdata")
                   :match (dmap "match") :reqmatch (dmap "reqmatch")
                   :point point :spec spec :result result :response response
                   :op nil}
                  :meta {:type ::context})]
    (oset! ctx :op (resolve-op ctx opname))
    ctx))

(defn ctx-out [ctx] (oget ctx :out))
(defn out-get [ctx k] (mget (deref (ctx-out ctx)) k))
(defn out-set! [ctx k v] (.put ^java.util.Map (deref (ctx-out ctx)) k v))

(defn resolve-op [ctx opname]
  (let [entity (oget ctx :entity)
        config (oget ctx :config)
        opmap (oget ctx :opmap)
        entname (if (and entity (:get-name entity)) ((:get-name entity)) "_")
        cache-key (str entname ":" opname)]
    (cond
      (get (deref opmap) cache-key) (get (deref opmap) cache-key)
      (or (nil? opname) (= "" opname)) (make-operation (vs/jm))
      :else
      (let [opcfg (vs/getpath config (str "entity." entname ".op." opname))
            input (if (or (= opname "update") (= opname "create")) "data" "match")
            points (let [t (when (vs/ismap opcfg) (vs/getprop opcfg "points"))]
                     (if (vs/islist t) t (vs/jt)))
            op (make-operation (vs/jm "entity" entname "name" opname "input" input "points" points))]
        (swap! opmap assoc cache-key op)
        op))))

;; ---------------------------------------------------------------------------
;; Feature dispatch.
;; ---------------------------------------------------------------------------

(defn feature-hook [ctx name]
  (when-let [client (oget ctx :client)]
    (when-let [feats (client-features client)]
      (doseq [f (deref feats)]
        (let [hf (get (deref f) name)]
          (when (fn? hf) (hf ctx)))))))

(defn feature-get-name [f] (:name (deref f)))
(defn feature-get-active [f] (:active (deref f)))
(defn feature-get-version [f] (:version (deref f)))

;; feature_add: position via _options (__before__/__after__/__replace__),
;; first match wins, else append. (gotcha #4 — ordering carrier is the
;; feature's :_options map.)
(defn feature-add [ctx f]
  (let [feats (client-features (oget ctx :client))
        fopts (or (:_options (deref f)) (vs/jm))
        before (mget fopts "__before__")
        after (mget fopts "__after__")
        replace (mget fopts "__replace__")]
    (if (or before after replace)
      (let [cur (deref feats)
            idx (first (keep-indexed (fn [i ef]
                                       (let [nm (feature-get-name ef)]
                                         (when (or (= before nm) (= after nm) (= replace nm)) i)))
                                     cur))]
        (if (nil? idx)
          (swap! feats conj f)
          (let [nm (feature-get-name (nth cur idx))]
            (cond
              (= before nm) (reset! feats (vec (concat (subvec cur 0 idx) [f] (subvec cur idx))))
              (= after nm)  (reset! feats (vec (concat (subvec cur 0 (inc idx)) [f] (subvec cur (inc idx)))))
              (= replace nm) (reset! feats (assoc cur idx f))))))
      (swap! feats conj f))
    nil))

(defn feature-init [ctx f]
  (let [fname (feature-get-name f)
        opts (oget ctx :options)
        feature-opts (when opts (vs/getprop opts "feature"))
        fopts (let [fo (when (vs/ismap feature-opts) (vs/getprop feature-opts fname))]
                (if (vs/ismap fo) fo (vs/jm)))]
    (when (= true (mget fopts "active"))
      ((get (deref f) "init") ctx fopts))))

;; ---------------------------------------------------------------------------
;; Entity helpers. An entity instance is a plain map carrying atoms plus fn
;; slots (:make / :data-set / :data-get / :get-name) so the generic pipeline
;; (make_result list-wrapping) can construct and populate siblings.
;; ---------------------------------------------------------------------------

(defn entity-get-name [ent] (when (and ent (:get-name ent)) ((:get-name ent))))

;; ---------------------------------------------------------------------------
;; Pipeline utilities. Each takes ctx; sibling steps are reached via ucall so
;; overrides / feature-wrapped fetchers are honoured.
;; ---------------------------------------------------------------------------

(def METHOD-MAP {"create" "POST" "update" "PUT" "load" "GET" "list" "GET" "remove" "DELETE" "patch" "PATCH"})

;; ---------------------------------------------------------------------------
;; clean. Everything that leaves the pipeline passes through it; inside, data
;; stays raw so a hook can still read the header it must add to. See
;; docs/explanation/secret-redaction.md.
;; ---------------------------------------------------------------------------

(def ^:private CLEAN-MAXDEPTH 32)
(def ^:private CLEAN-CIRCULAR "[circular]")
(def ^:private DROP (Object.))

(defn- keyname [k] (cond (nil? k) "" (keyword? k) (name k) :else (str k)))

(defn- normkey [k] (str/replace (str/lower-case (keyname k)) #"[-_]" ""))

(defn- splitkeys [keys]
  (->> (str/split (str (or keys "")) #"\s*,\s*") (map normkey) (remove empty?) vec))

(defn splitvalues [values]
  (if (or (vs/islist values) (sequential? values))
    (filterv string? (vec values))
    (->> (str/split (str (or values "")) #"\s*,\s*") (remove empty?) vec)))

(defn- count-opt [v dflt]
  (let [n (try (long (Math/floor (Double/parseDouble (str v)))) (catch Exception _ nil))]
    (if (and n (<= 0 n)) n dflt)))

;; The derived clean block: a struct map so it lives in options.__derived__
;; and its `values` list stays MUTABLE after make-options - features register
;; what they resolve later.
(defn make-clean-config [cleanopts]
  (let [o (fn [k] (mget cleanopts k))
        keys (vs/jt)]
    (doseq [k (splitkeys (o "keys"))] (.add ^java.util.List keys k))
    (vs/jm "active" (not= false (o "active"))
           "keys" keys
           "values" (vs/jt)
           "mask" (let [m (o "mask")] (if (string? m) m "[redacted]"))
           "hint" (count-opt (o "hint") 0)
           "min" (max 1 (count-opt (o "min") 4)))))

;; A context without options (make-error accepts a bare one) still masks by
;; the schema defaults.
(defn- clean-config [ctx]
  (let [options (when (instance? clojure.lang.IDeref ctx) (oget ctx :options))
        derived (when (vs/ismap options) (vs/getpath options "__derived__.clean"))]
    (if (vs/ismap derived) derived (make-clean-config (vs/getprop @optspec-parsed "clean")))))

;; The encoded forms a value travels in.
(defn- clean-forms [^String value]
  (let [out (java.util.ArrayList.)
        add (fn [s] (when (and (string? s) (not= "" s) (not (.contains out s))) (.add out s)))]
    (add value)
    (try (add (.encodeToString (java.util.Base64/getEncoder) (.getBytes value "UTF-8"))) (catch Throwable _ nil))
    (try (add (vs/escurl value)) (catch Throwable _ nil))
    (try (let [j (vs/jsonify value)] (add (subs j 1 (dec (count j))))) (catch Throwable _ nil))
    (vec out)))

(defn u-clean-add [ctx value]
  (let [cfg (clean-config ctx)
        minlen (long (or (mget cfg "min") 4))
        values (mget cfg "values")]
    (when (and (string? value) (>= (count value) minlen) (instance? java.util.List values))
      (let [changed (atom false)]
        (doseq [form (clean-forms value)]
          (when (and (>= (count form) minlen) (not (.contains ^java.util.List values form)))
            (.add ^java.util.List values form)
            (reset! changed true)))
        ;; Longest first, so a value is never masked by a substring of itself.
        (when @changed
          (let [sorted (sort-by (fn [^String s] (- (count s))) (vec values))]
            (.clear ^java.util.List values)
            (doseq [s sorted] (.add ^java.util.List values s))))))
    nil))

(defn- mask-value [cfg ^String value]
  (let [hint (long (or (mget cfg "hint") 0))
        mask (str (mget cfg "mask"))]
    (if (and (pos? hint) (> (count value) (* 2 hint)))
      (str mask (subs value (- (count value) hint)))
      mask)))

(defn- clean-string [cfg ^String text]
  (reduce (fn [^String out ^String value]
            (if (.contains out value) (str/replace out value (mask-value cfg value)) out))
          text
          (vec (or (mget cfg "values") []))))

(defn- sensitive-key? [cfg key]
  (if (or (nil? key) (number? key))
    false
    (let [^String nk (normkey key)]
      (boolean (some (fn [^String k] (.contains nk k)) (vec (or (mget cfg "keys") [])))))))

(defn- number-text [n]
  (if (and (float? n) (== (double n) (Math/floor (double n))) (< (Math/abs (double n)) 9.0E15))
    (str (long n))
    (str n)))

;; Every scalar under a sensitive name, at any depth and of any shape: a
;; credential mistyped as a map or a number is still a credential, and the
;; validation error that rejects it quotes it.
(defn u-clean-add-sensitive
  ([ctx val] (u-clean-add-sensitive ctx (clean-config ctx) val false 0 []))
  ([ctx cfg val under depth seen]
   (cond
     (or (nil? val) (<= CLEAN-MAXDEPTH depth)) nil
     (string? val) (when under (u-clean-add ctx val))
     (number? val) (when under (u-clean-add ctx (number-text val)))
     (some #(identical? % val) seen) nil
     (instance? java.util.Map val)
     (let [seen (conj seen val)]
       (doseq [^java.util.Map$Entry e (vec (.entrySet ^java.util.Map val))]
         (u-clean-add-sensitive ctx cfg (.getValue e)
                                (or under (sensitive-key? cfg (.getKey e))) (inc depth) seen)))
     (or (instance? java.util.Collection val) (sequential? val))
     (let [seen (conj seen val)]
       (doseq [v (seq val)]
         (u-clean-add-sensitive ctx cfg v under (inc depth) seen)))
     :else nil)))

(defn- entity-instance? [v]
  (and (map? v) (instance? clojure.lang.IAtom (:_data v)) (fn? (:get-name v))))

;; A registered value used as a property name is masked like any other
;; string; names that mask alike take a counter, so none is lost.
(defn- clean-name [cfg has? k]
  (let [key (keyname k)
        n (clean-string cfg key)]
    (if (or (= n key) (not (has? n)))
      n
      (loop [i 1]
        (let [c (str n "#" i)]
          (if (has? c) (recur (inc i)) c))))))

;; A masked plain-data COPY (string-keyed struct nodes): an entity serialises
;; as its record, an atom-object as its map, functions are dropped, cycles
;; cut, and nothing is shared with the live value, whose spec must stay raw.
(defn- clean-snapshot [cfg val key depth seen]
  (cond
    (nil? val) nil
    (string? val) (if (sensitive-key? cfg key) (mask-value cfg val) (clean-string cfg val))
    (fn? val) DROP
    (or (number? val) (boolean? val) (keyword? val) (symbol? val) (char? val))
    (if (sensitive-key? cfg key) (mget cfg "mask") val)
    (or (<= CLEAN-MAXDEPTH depth) (some #(identical? % val) seen)) CLEAN-CIRCULAR
    (sensitive-key? cfg key) (mget cfg "mask")
    :else
    (let [seen (conj seen val)]
      (cond
        (entity-instance? val) (clean-snapshot cfg (deref (:_data val)) key (inc depth) seen)
        (instance? clojure.lang.IAtom val) (clean-snapshot cfg (deref val) key (inc depth) seen)
        (instance? Throwable val)
        (let [out (vs/jm "message" (clean-string cfg (str (.getMessage ^Throwable val))))]
          (when (instance? clojure.lang.IExceptionInfo val)
            (let [d (clean-snapshot cfg (ex-data val) "data" (inc depth) seen)]
              (when-not (identical? DROP d) (.put ^java.util.Map out "data" d))))
          out)
        (instance? java.util.Map val)
        (let [out (vs/jm)]
          (doseq [^java.util.Map$Entry e (.entrySet ^java.util.Map val)]
            (let [k (.getKey e)
                  v (clean-snapshot cfg (.getValue e) k (inc depth) seen)]
              (when-not (identical? DROP v)
                (.put ^java.util.Map out
                      (clean-name cfg #(.containsKey ^java.util.Map out %) k) v))))
          out)
        (or (instance? java.util.Collection val) (sequential? val))
        (let [out (vs/jt)]
          (doseq [[i v] (map-indexed vector (seq val))]
            (let [c (clean-snapshot cfg v i (inc depth) seen)]
              (.add ^java.util.List out (if (identical? DROP c) nil c))))
          out)
        :else (clean-string cfg (str val))))))

;; An error map is immutable, so "in place" is a cleaned copy carrying the
;; same metadata (the context stays reachable through err-ctx).
(defn- clean-error [cfg err]
  (with-meta
    (reduce (fn [out [k v]]
              (let [c (clean-snapshot cfg v k 1 [])
                    n (clean-name cfg #(contains? out %) k)]
                (assoc out (if (= n (keyname k)) k n) (if (identical? DROP c) nil c))))
            {} err)
    (meta err)))

(defn u-clean [ctx val]
  (let [cfg (clean-config ctx)]
    (cond
      (= false (mget cfg "active")) val
      (string? val) (clean-string cfg val)
      (sdk-error? val) (clean-error cfg val)
      :else (let [out (clean-snapshot cfg val nil 0 [])] (if (identical? DROP out) nil out)))))

;; A Throwable is immutable, so one that never passed through make-error (a
;; hook's, a fetcher's) leaves as a cleaned copy with the original's trace.
;; One carrying the SDK error keeps it, cleaned, under the same key.
(defn clean-throwable [ctx ^Throwable t]
  (let [cfg (clean-config ctx)]
    (if (= false (mget cfg "active"))
      t
      (let [sdkerr (ex->sdk t)
            out (if (sdk-error? sdkerr)
                  (let [e (clean-error cfg sdkerr)]
                    (ex-info (err-msg e) {::sdk-error e}))
                  (let [data (when (instance? clojure.lang.IExceptionInfo t)
                               (clean-snapshot cfg (ex-data t) nil 0 []))]
                    (ex-info (clean-string cfg (str (.getMessage t)))
                             (if (instance? java.util.Map data) (into {} data) {}))))]
        (.setStackTrace ^Throwable out (.getStackTrace t))
        out))))

;; The error as string-keyed data: jsonify reads a java.util.Map's keys as
;; strings, so a keyword-keyed map would serialise as nulls.
(defn err->data [e]
  (when (sdk-error? e)
    (u-clean (err-ctx e) (into {} (map (fn [[k v]] [(keyname k) v]) e)))))

;; The serialised context leaves the pipeline (a logger, an error dump), so
;; it is the cleaned record; the live fields stay raw for the pipeline's use.
(defn ctx->data [ctx]
  (let [m (deref ctx)
        u (:utility m)
        clean (or (when (instance? clojure.lang.IDeref u) (:clean (deref u))) u-clean)
        entity (:entity m)]
    (clean ctx (vs/jm "id" (:id m) "op" (:op m) "spec" (:spec m)
                      "entity" (when (map? entity) (entity-get-name entity))
                      "result" (:result m) "response" (:response m) "meta" (:meta m)))))

(defmethod print-method ::context [ctx ^java.io.Writer w]
  (.write w (str "#sdk/context " (vs/jsonify (ctx->data ctx) (vs/jm "indent" 0)))))

;; The explain map is the CALLER's, so it is cleaned in place: what they hold
;; after the call is the cleaned record. With clean off its result is the live
;; result atom, which the prune leaves alone.
(defn clean-explain! [ctx]
  (when-let [ex (oget (oget ctx :ctrl) :explain)]
    (let [cleaned (ucall ctx :clean ex)]
      (when (and (vs/ismap ex) (vs/ismap cleaned) (not (identical? cleaned ex)))
        (.clear ^java.util.Map ex)
        (.putAll ^java.util.Map ex ^java.util.Map cleaned))
      (let [er (mget ex "result")] (when (vs/ismap er) (vs/delprop er "err"))))))

;; The API definition is authoritative: a POST-only or PATCH-based API
;; exposes `update` as POST or PATCH, not the PUT the op name implies.
;; Only fall back to the op-name convention when the point has no method.
(defn u-prepare-method [ctx]
  (let [point (oget ctx :point)
        m (when point (vs/getprop point "method"))]
    (if (and (string? m) (not= "" m))
      (str/upper-case m)
      ;; NO CATCH-ALL "GET". The ts reference returns methodMap[key], which is
      ;; undefined for an op the map does not name, so the request is refused
      ;; rather than issued. Defaulting to GET made every unrecognised op — a
      ;; typo, an unsupported operation — a quiet fetch, and the method feeds
      ;; the allow.method gate. ocaml and zig had the identical fallback; the
      ;; shared corpus caught all three.
      (get METHOD-MAP (op-name (oget ctx :op))))))

;; The arguments a point declares in one location, query or header, each as
;; [name wire val]: the name it travels under and the value this call passes
;; in its match or else its data. Unlike a path parameter, the entity's stored
;; match and data never supply one.
(defn- call-args [ctx kind]
  (let [point (oget ctx :point)
        args (when point (vs/getprop point "args"))
        defs (when (vs/ismap args) (vs/getprop args kind))]
    (if (vs/islist defs)
      (vec (keep (fn [ad]
                   (let [name (when (vs/ismap ad) (vs/getprop ad "name"))]
                     (when (and (string? name) (seq name))
                       (let [orig (vs/getprop ad "orig")
                             wire (if (and (string? orig) (seq orig)) orig name)
                             v (vs/getprop (oget ctx :reqmatch) name)
                             v (if (nil? v) (vs/getprop (oget ctx :reqdata) name) v)]
                         [name wire v]))))
                 (vec defs)))
      [])))

;; ---- media -------------------------------------------------------------------
;;
;; The media types a point declares: `response` (the model's `rs`) for the
;; Accept header, and `body` (the model's `rb`) for the request body.

;; The data key holding a raw request body. Like `$action`, it can never be a
;; declared argument name.
(def RAW-BODY "$body")

(defn json-media? [media]
  (let [m (-> (if (string? media) media "") (str/split #";" 2) first (or "") str/trim str/lower-case)]
    (or (= "application/json" m) (= "text/json" m) (str/ends-with? m "+json"))))

;; The declared JSON type alone, else every declared type in the model's
;; order; nil when no success response declares a body.
(defn accept-of [point]
  (let [res (when point (vs/getprop point "response"))
        media (when (vs/ismap res) (vs/getprop res "media"))]
    (when (and (string? media) (seq media))
      (if (= "json" (vs/getprop res "kind"))
        media
        (let [alts (vs/getprop res "alternatives")
              others (when (vs/islist alts)
                       (keep (fn [alt]
                               (let [m (when (vs/ismap alt) (vs/getprop alt "media"))]
                                 (when (and (string? m) (seq m)) m)))
                             (vec alts)))]
          (str/join ", " (cons media others)))))))

(defn raw-request? [point]
  (let [body (when point (vs/getprop point "body"))]
    (and (vs/ismap body) (= "raw" (vs/getprop body "kind")))))

(defn- media-header? [^java.util.Map headers name]
  (boolean (some (fn [k] (and (string? k) (= name (str/lower-case k)))) (vec (.keySet headers)))))

;; A caller's accept wins. A declared request type replaces each JSON
;; content-type, the SDK default, and leaves any other the caller set.
(defn media-headers [point ^java.util.Map headers]
  (let [accept (accept-of point)]
    (when (and accept (not (media-header? headers "accept")))
      (.put headers "accept" accept)))
  (let [body (when point (vs/getprop point "body"))
        kind (when (vs/ismap body) (vs/getprop body "kind"))
        media (when (vs/ismap body) (vs/getprop body "media"))]
    (when (and (contains? #{"raw" "json"} kind) (string? media) (seq media))
      (doseq [k (vec (.keySet headers))]
        (when (and (string? k) (= "content-type" (str/lower-case k)) (json-media? (.get headers k)))
          (.remove headers k)))
      (when-not (media-header? headers "content-type")
        (.put headers "content-type" media))))
  headers)

;; A byte array, an InputStream or a string, sent as it is. An InputStream is
;; read here, once, before the first attempt, so that a retry sends the same
;; bytes again.
(defn raw-body [reqdata]
  (let [body (when (vs/ismap reqdata) (vs/getprop reqdata RAW-BODY))]
    (if (instance? java.io.InputStream body) (.readAllBytes ^java.io.InputStream body) body)))

;; The form style of a cookie parameter: a list repeats the name, a map sends
;; its own keys, and every value is percent-encoded.
(defn- cookie-pair [wire v]
  (let [esc (fn [x] (vs/escurl (vs/stringify x)))]
    (str/join "&"
              (cond
                (vs/islist v) (map (fn [item] (str wire "=" (esc item))) v)
                (vs/ismap v) (map (fn [k] (str (vs/escurl k) "=" (esc (vs/getprop v k)))) (vs/keysof v))
                :else [(str wire "=" (esc v))]))))

;; The caller's cookie pieces with every named cookie removed. A piece whose
;; &-parts are all pairs is the exploded form cookie-pair writes, and loses
;; only the pairs named; any other piece is one cookie, kept or dropped whole.
(defn- cookie-keep [header names]
  (let [named? (fn [part] (contains? names (str/trim (first (str/split part #"=" 2)))))]
    (vec (for [piece (str/split header #";" -1)
               :let [parts (str/split piece #"&" -1)
                     rest (cond
                            (every? #(str/includes? % "=") parts) (remove named? parts)
                            (named? piece) []
                            :else parts)
                     cookie (str/trim (str/join "&" rest))]
               :when (not= "" cookie)]
           cookie))))

(defn u-prepare-headers [ctx]
  (let [options (client-options-map (oget ctx :client))
        headers (vs/getprop options "headers")
        out (media-headers (oget ctx :point)
                           (if (nil? headers) (vs/jm)
                               (let [o (vs/clone headers)] (if (vs/ismap o) o (vs/jm)))))]
    ;; A header argument replaces a default of the same name, whatever its case.
    (doseq [[_ wire v] (call-args ctx "header")]
      (when (some? v)
        (let [key (str/lower-case wire)]
          (doseq [k (vec (.keySet ^java.util.Map out))]
            (when (and (string? k) (= key (str/lower-case k)))
              (.remove ^java.util.Map out k)))
          (.put ^java.util.Map out key (vs/stringify v)))))
    ;; A cookie argument travels in the cookie header, form serialized and
    ;; percent-encoded, replacing a cookie of the same name among those the
    ;; caller's headers already send.
    (let [sent (vec (for [[_ wire v] (call-args ctx "cookie") :when (some? v)] [wire v]))]
      (when (seq sent)
        (let [names (set (mapcat (fn [[wire v]] (if (vs/ismap v) (map vs/escurl (vs/keysof v)) [wire])) sent))
              given (vec (filter (fn [k] (and (string? k) (= "cookie" (str/lower-case k))))
                                 (vec (.keySet ^java.util.Map out))))
              kept (vec (for [k given
                              :let [v (.get ^java.util.Map out k)]
                              :when (string? v)
                              cookie (cookie-keep v names)]
                          cookie))
              pairs (vec (for [[wire v] sent
                               :let [pair (cookie-pair wire v)]
                               :when (not= "" pair)]
                           pair))]
          (doseq [k given] (.remove ^java.util.Map out k))
          (when (seq (concat kept pairs))
            (.put ^java.util.Map out "cookie" (str/join "; " (concat kept pairs)))))))
    out))

;; The name a point gives a parameter in the call, if it renames it.
(defn- param-alias [point key]
  (let [am (when point (to-map (vs/getprop point "alias")))
        ak (when am (vs/getprop am key))]
    (if (string? ak) ak "")))

;; The value the call or its entity gives a point's parameter, under its name
;; or the point's alias for it.
(defn param-value [ctx point key]
  (let [akey (param-alias point key)
        reqmatch (oget ctx :reqmatch)
        reqdata (oget ctx :reqdata)
        data (oget ctx :data)
        v (atom (vs/getprop reqmatch key))]
    (when (nil? @v) (reset! v (vs/getprop (oget ctx :match) key)))
    (when (and (nil? @v) (seq akey)) (reset! v (vs/getprop reqmatch akey)))
    (when (nil? @v) (reset! v (vs/getprop reqdata key)))
    (when (nil? @v) (reset! v (vs/getprop data key)))
    (when (and (nil? @v) (seq akey))
      (reset! v (vs/getprop reqdata akey))
      (when (nil? @v) (reset! v (vs/getprop data akey))))
    @v))

(defn u-param [ctx paramdef]
  (let [point (oget ctx :point)
        spec (oget ctx :spec)
        pt (vs/typify paramdef)
        key (if (pos? (bit-and vs/T_string pt)) paramdef
                (let [k (vs/getprop paramdef "name")] (if (string? k) k "")))
        akey (param-alias point key)]
    (when (and spec (seq akey)
               (nil? (vs/getprop (oget ctx :reqmatch) key))
               (nil? (vs/getprop (oget ctx :match) key)))
      (.put ^java.util.Map (oget spec :alias) akey key))
    (param-value ctx point key)))

(defn u-prepare-params [ctx]
  (let [point (oget ctx :point)
        params (let [args (when point (vs/getprop point "args"))
                     p (when (vs/ismap args) (vs/getprop args "params"))]
                 (if (vs/islist p) p (vs/jt)))
        out (vs/jm)]
    (doseq [pd (vec params)]
      (let [val (ucall ctx :param pd)]
        (when (and (some? val) (vs/ismap pd))
          (let [name (vs/getprop pd "name")]
            (when (and (string? name) (seq name)) (.put ^java.util.Map out name val))))))
    out))

(defn u-prepare-path [ctx]
  (let [point (oget ctx :point)
        parts (let [p (when point (vs/getprop point "parts"))] (if (vs/islist p) p (vs/jt)))]
    (vs/join parts "/" true)))

(defn u-prepare-query [ctx]
  (let [point (oget ctx :point)
        reqmatch (or (oget ctx :reqmatch) (vs/jm))
        params (let [p (when point (vs/getprop point "params"))] (if (vs/islist p) p (vs/jt)))
        ;; A path parameter travels in the path. The generated config lists
        ;; them as args.params, which u-prepare-params reads; params is the
        ;; older list of names.
        aparams (let [args (when point (vs/getprop point "args"))
                      p (when (vs/ismap args) (vs/getprop args "params"))]
                  (if (vs/islist p) p (vs/jt)))
        ;; A header parameter travels in the headers, which u-prepare-headers
        ;; fills.
        aheader (let [args (when point (vs/getprop point "args"))
                      h (when (vs/ismap args) (vs/getprop args "header"))]
                  (if (vs/islist h) h (vs/jt)))
        ;; A cookie parameter travels in the cookie header, which u-prepare-headers fills.
        acookie (let [args (when point (vs/getprop point "args"))
                      c (when (vs/ismap args) (vs/getprop args "cookie"))]
                  (if (vs/islist c) c (vs/jt)))
        ;; A header or cookie name leaves the query unless a query parameter
        ;; shares it: then both are sent.
        declared (let [args (when point (vs/getprop point "args"))
                       q (when (vs/ismap args) (vs/getprop args "query"))]
                   (into #{} (keep (fn [qd] (when (vs/ismap qd) (vs/getprop qd "name")))
                                   (vec (if (vs/islist q) q (vs/jt))))))
        routed (fn [d] (when (vs/ismap d)
                         (let [n (vs/getprop d "name")] (when-not (contains? declared n) n))))
        pset (into (into (into (into #{} (vec params))
                               (keep (fn [pd] (when (vs/ismap pd) (vs/getprop pd "name"))) (vec aparams)))
                         (keep routed (vec aheader)))
                   (keep routed (vec acookie)))
        ;; A query parameter travels under the name the definition gives it,
        ;; its orig, which the model may have renamed for the caller.
        aquery (let [args (when point (vs/getprop point "args"))
                     q (when (vs/ismap args) (vs/getprop args "query"))]
                 (if (vs/islist q) q (vs/jt)))
        wire (into {}
                   (keep (fn [qd]
                           (when (vs/ismap qd)
                             (let [n (vs/getprop qd "name") o (vs/getprop qd "orig")]
                               (when (and (string? n) (string? o) (not= "" o)) [n o]))))
                         (vec aquery)))
        out (vs/jm)]
    (doseq [item (or (vs/items reqmatch) [])]
      (let [k (vs/getprop item 0) v (vs/getprop item 1)]
        (when (and (some? v) (string? k) (not= "$action" k) (not (contains? pset k)))
          (.put ^java.util.Map out (get wire k k) v))))
    ;; A create or update passes its query arguments in its data.
    (doseq [[name orig v] (call-args ctx "query")]
      (when (and (some? v) (not (contains? pset name)))
        (.put ^java.util.Map out orig v)))
    out))

(defn- omit-keys [reqdata names]
  (if (and (vs/ismap reqdata) (some #(.containsKey ^java.util.Map reqdata %) names))
    (let [body (vs/jm)]
      (doseq [item (or (vs/items reqdata) [])]
        (let [k (vs/getprop item 0) v (vs/getprop item 1)]
          (when-not (some #(= k %) names) (.put ^java.util.Map body k v))))
      body)
    reqdata))

;; `$action` selects the point (see u-make-point); it is never an API field,
;; so the body is a copy without it. The caller's map is left untouched.
(defn- strip-action [reqdata] (omit-keys reqdata ["$action"]))

;; A header or query argument travels where u-prepare-headers or
;; u-prepare-query sends it, so the body is built from the request data
;; without it.
(defn- routed-arg-names [ctx]
  (mapv first (concat (call-args ctx "header") (call-args ctx "cookie") (call-args ctx "query"))))

(defn u-transform-request [ctx]
  (let [spec (oget ctx :spec) point (oget ctx :point)
        data (omit-keys (oget ctx :reqdata) (routed-arg-names ctx))]
    (when spec (oset! spec :step "reqform"))
    (let [transform (to-map (vs/getprop point "transform"))]
      (strip-action
       (if (nil? transform) data
           (let [reqform (vs/getprop transform "req")]
             (if (nil? reqform) data
                 (vs/transform (vs/jm "reqdata" data) reqform))))))))

(defn u-prepare-body [ctx]
  (cond
    (not= "data" (op-input (oget ctx :op))) nil
    (raw-request? (oget ctx :point)) (raw-body (oget ctx :reqdata))
    :else (ucall ctx :transform-request)))

;; ---- graphql ---------------------------------------------------------------
;;
;; GraphQL transport. API-INDEPENDENT: every GraphQL SDK this generator
;; produces uses this code unchanged. The API-specific part — which
;; operations exist and what each one's document is — is model data, computed
;; once by apidef and emitted into Config.
;;
;; Two jobs:
;;
;;   u-graphql-body   — build {query, variables} for a point, binding the op's
;;                      arguments to the document's declared variables.
;;
;;   u-graphql-errors — lift a GraphQL failure into an SDK error. GraphQL
;;                      reports failures as a top-level `errors` array under
;;                      HTTP 200, so the status-driven path in result-basic
;;                      never sees them.

;; Content type every GraphQL-over-HTTP request uses.
(def GRAPHQL-CONTENT-TYPE "application/json")

;; Map a GraphQL error to the same error codes the HTTP path produces, so a
;; caller handles auth or rate limiting identically on both transports.
;; Servers put the machine-readable code in `extensions.code`; Linear-style
;; APIs use `extensions.type`.
(defn graphql-error-code [gqlerr]
  (let [ext (vs/getprop gqlerr "extensions")
        code (let [c (vs/getprop ext "code")]
               (if (and (string? c) (seq c)) c (vs/getprop ext "type")))
        raw (str/upper-case (if (string? code) code ""))]
    (cond
      (or (str/includes? raw "AUTH") (str/includes? raw "FORBIDDEN")
          (str/includes? raw "UNAUTHENTICATED")) "request_auth"
      (or (str/includes? raw "RATELIMIT") (str/includes? raw "RATE_LIMIT")
          (str/includes? raw "TOO_MANY")) "request_ratelimit"
      (or (str/includes? raw "BAD_USER_INPUT") (str/includes? raw "VALIDATION")
          (str/includes? raw "INVALID")) "request_invalid"
      :else "request_graphql")))

;; Build the request body for a GraphQL point.
;;
;; Variables come from the op's own arguments: a named variable binds to the
;; like-named argument (`from`), and the input-object variable (empty `from`)
;; takes the request data as a whole — which is what makes a generated
;; create/update call look exactly like its REST equivalent.
(defn u-graphql-body [ctx]
  (let [gql (vs/getprop (oget ctx :point) "graphql")]
    (when (vs/ismap gql)
      ;; reqmatch/reqdata hold the caller's arguments for this operation;
      ;; which one depends on whether the op takes match or data input.
      (let [datainput (= "data" (op-input (oget ctx :op)))
            reqsrc (let [r (if datainput (oget ctx :reqdata) (oget ctx :reqmatch))]
                     (if (vs/ismap r) r (vs/jm)))
            ;; data/match hold the entity's current state; a named variable
            ;; falls back to it, so updating a loaded entity with just
            ;; {title} still binds the stored id the mutation requires.
            datasrc (let [d (if datainput (oget ctx :data) (oget ctx :match))]
                      (if (vs/ismap d) d (vs/jm)))
            variables (vs/jm)
            varlist (let [v (vs/getprop gql "vars")] (if (vs/islist v) v (vs/jt)))]
        (doseq [spec (vec varlist)]
          (when (vs/ismap spec)
            (let [name (vs/getprop spec "name")
                  from (vs/getprop spec "from")]
              (when (and (string? name) (seq name))
                (if (or (nil? from) (not (string? from)) (empty? from))
                  ;; The input object IS the request body. Strip the action
                  ;; selector, which is an SDK-side point discriminator, not
                  ;; an API field.
                  (let [body (vs/jm)]
                    (doseq [item (or (vs/items reqsrc) [])]
                      (let [k (vs/getprop item 0) v (vs/getprop item 1)]
                        (when (not= "$action" k) (.put ^java.util.Map body k v))))
                    (.put ^java.util.Map variables name body))
                  ;; Only send variables the caller actually supplied: sending
                  ;; an explicit null would clear a field on many APIs.
                  (let [val (let [v (vs/getprop reqsrc from)]
                              (if (some? v) v (vs/getprop datasrc from)))]
                    (when (some? val) (.put ^java.util.Map variables name val))))))))
        (vs/jm "query" (vs/getprop gql "doc") "variables" variables)))))

;; Inspect a decoded GraphQL response body and record a failure when the
;; server reported one. Returns true when an error was recorded.
;;
;; Partial data (`data` alongside `errors`) is treated as failure: the REST
;; surface has no partial-success concept, and silently returning half an
;; object would be worse than failing.
(defn u-graphql-errors [ctx]
  (let [result (oget ctx :result)
        errors (when result (vs/getprop (oget result :body) "errors"))
        n (if (vs/islist errors) (vs/size errors) 0)]
    (if (or (nil? result)
            (not= "graphql" (vs/getprop (oget ctx :point) "kind"))
            (zero? n))
      false
      (let [first-err (vs/getprop errors 0)
            m (vs/getprop first-err "message")
            m (if (and (string? m) (seq m)) m "graphql error")
            m (if (< 1 n) (str m " (+" (dec n) " more)") m)]
        (oset! result :err (ctx-error ctx (graphql-error-code first-err) (str "graphql: " m)))
        (oset! result :ok false)
        true))))

;; WHERE THE CREDENTIAL GOES IS A FACT ABOUT THE API, so HEADER-AUTH,
;; OPTION-APIKEY, NOT-FOUND and u-prepare-auth are GENERATED into
;; src/sdk/prepare_auth.clj rather than written here.
;;
;; apidef resolves the security scheme's `in` and `name` into
;; main.kit.info.security - joplin's says `in: "query", name: "token"` - and
;; this file used to hardcode an `authorization` HEADER, so an
;; apiKey-in-query API got a header it does not read and never got the query
;; parameter it does. Header, query and cookie need three different bodies
;; and a hand-written file has to pick one, so cmp/clojure/PrepareAuth_
;; clojure.ts emits the branch the API actually uses and nothing else.
;;
;; `load`, NOT `require`: the generated file opens with `(in-ns 'sdk.core)`
;; and is read INTO THIS NAMESPACE, right here, where the defn used to be.
;; A namespace of its own would need sdk.core's oget / ctx-error /
;; client-options-map while base-utility-map below needs its u-prepare-auth -
;; a load cycle, which Clojure refuses. This is the idiom clojure.core itself
;; uses to split across files, every helper above is already in scope, and
;; both `:prepare-auth u-prepare-auth` below and `core/HEADER-AUTH` (read by
;; feature/secrets) go on resolving exactly as before.
(load "prepare_auth")

;; The path parameters of a point that neither the call nor the entity gives a
;; value for, looked up as u-param looks them up.
(defn- unfilled-params [ctx point]
  (let [parts (vs/getprop point "parts")]
    (if (vs/islist parts)
      (vec (keep (fn [part]
                   (when-let [[_ pname] (and (string? part) (re-matches #"\{([^{}/]+)\}" part))]
                     (when (nil? (param-value ctx point pname)) pname)))
                 (vec parts)))
      [])))

(defn u-make-point [ctx]
  (let [preset (out-get ctx "point")]
    (if (some? preset)
      (if (sdk-error? preset)
        [nil preset]
        (do (oset! ctx :point preset) [(oget ctx :point) nil]))
      (let [op (oget ctx :op)
            options (oget ctx :options)
            allow-op (or (vs/getpath options "allow.op") "")]
        (cond
          (not (str/includes? allow-op (op-name op)))
          [nil (ctx-error ctx "point_op_allow"
                          (str "Operation \"" (op-name op) "\" not allowed by SDK option allow.op value: \"" allow-op "\""))]
          (zero? (vs/size (op-points op)))
          [nil (ctx-error ctx "point_no_points"
                          (str "Operation \"" (op-name op) "\" has no endpoint definitions."))]
          (= 1 (vs/size (op-points op)))
          (do (oset! ctx :point (vs/getelem (op-points op) 0)) [(oget ctx :point) nil])
          :else
          (let [datainput (= (op-input op) "data")
                reqselector (if datainput (oget ctx :reqdata) (oget ctx :reqmatch))
                selector (if datainput (oget ctx :data) (oget ctx :match))
                point-matches?
                (fn [p]
                  (let [select-def (to-map (vs/getprop p "select"))
                        found (atom true)]
                    (when (and selector select-def)
                      (let [exist (vs/getprop select-def "exist")]
                        (when (vs/islist exist)
                          (doseq [ek (vec exist)]
                            (when @found
                              (let [rv (vs/getprop reqselector (str ek))
                                    sv (vs/getprop selector (str ek))]
                                (when (and (nil? rv) (nil? sv)) (reset! found false))))))))
                    (when @found
                      (let [ra (vs/getprop reqselector "$action")
                            sa (vs/getprop select-def "$action")]
                        (when (not= ra sa) (reset! found false))))
                    @found))
                ;; How many path segments a point has, and whether its path
                ;; ends in a parameter. A record route ends in the record's
                ;; identifier (/boards/{id}); a cross-reference that also
                ;; returns the entity ends in the relationship's name
                ;; (/posts/{id}/author). That, then fewest segments, is what
                ;; tells the entity's own route from a cross-reference. The
                ;; same rule runs at generation time, in helpers/opShape.ts —
                ;; both sides must move together.
                parts-len (fn [p]
                            (let [parts (vs/getprop p "parts")]
                              (if (vs/islist parts) (vs/size parts) 0)))
                terminal-param? (fn [p]
                                  (let [parts (vs/getprop p "parts")]
                                    (and (vs/islist parts)
                                         (pos? (vs/size parts))
                                         (let [last-part (vs/getelem parts (dec (vs/size parts)))]
                                           (and (string? last-part)
                                                (str/starts-with? last-part "{"))))))
                own-point (fn [ps]
                            (reduce (fn [best cand]
                                      (let [ct (terminal-param? cand)
                                            bt (terminal-param? best)]
                                        (if (not= ct bt)
                                          (if ct cand best)
                                          (if (< (parts-len cand) (parts-len best)) cand best))))
                                    (first ps) ps))
                matched (first (filter point-matches? (vec (op-points op))))
                req-action (vs/getprop reqselector "$action")]
            (cond
              ;; select.exist can list more than the params needed to pick a
              ;; point, so nothing matches. A request naming an action reaches
              ;; here only because that action's own point failed its exist
              ;; test, so it is unbuildable whatever we pick — refuse it
              ;; BEFORE falling back, since the guard below compares the
              ;; chosen point's $action and would wave the request through
              ;; whenever the fallback lands on the action point itself.
              (and (nil? matched) reqselector req-action)
              [nil (ctx-error ctx "point_action_invalid"
                              (str "Operation \"" (op-name op) "\" action \"" (vs/stringify req-action) "\" is not valid."))]

              :else
              (let [all (vec (op-points op))
                    ;; A call without an action falls back to a point without
                    ;; one, as generation does, and only to a route the call
                    ;; can fill.
                    plain (filterv #(nil? (vs/getprop (to-map (vs/getprop % "select")) "$action")) all)
                    fillable (filterv #(empty? (unfilled-params ctx %)) plain)
                    chosen (or matched (when (seq fillable) (own-point fillable)))]
                (cond
                  (and (nil? matched) (empty? plain))
                  [nil (ctx-error ctx "point_action_required"
                                  (str "Operation \"" (op-name op)
                                       "\" has only action endpoints; pass $action to choose one."))]

                  (nil? chosen)
                  [nil (ctx-error ctx "point_no_match"
                                  (str "Operation \"" (op-name op)
                                       "\" has no endpoint whose path parameters are all given (missing: "
                                       (str/join ", " (unfilled-params ctx (own-point plain))) ")."))]

                  (and reqselector req-action)
                  (let [point-select (to-map (vs/getprop chosen "select"))
                        point-action (vs/getprop point-select "$action")]
                    (if (not= req-action point-action)
                      [nil (ctx-error ctx "point_action_invalid"
                                      (str "Operation \"" (op-name op) "\" action \"" (vs/stringify req-action) "\" is not valid."))]
                      (do (oset! ctx :point chosen) [(oget ctx :point) nil])))

                  :else
                  (do (oset! ctx :point chosen) [(oget ctx :point) nil]))))))))))

(defn u-make-spec [ctx]
  (if (some? (out-get ctx "spec"))
    ;; A PreSpec feature hook (e.g. validate) may short-circuit the operation
    ;; by storing an error here; surface it before the request is built, the
    ;; same way u-make-point surfaces out["point"].
    (if (sdk-error? (out-get ctx "spec"))
      [nil (out-get ctx "spec")]
      (do (oset! ctx :spec (out-get ctx "spec")) [(oget ctx :spec) nil]))
    (let [point (oget ctx :point)
          options (oget ctx :options)
          base (or (vs/getprop options "base") "")
          prefix (or (vs/getprop options "prefix") "")
          suffix (or (vs/getprop options "suffix") "")
          parts (let [p (when point (vs/getprop point "parts"))] (if (vs/islist p) p (vs/jt)))
          spec (make-spec (vs/jm "base" base "prefix" prefix "parts" parts "suffix" suffix "step" "start"))]
      (oset! ctx :spec spec)
      (oset! spec :method (ucall ctx :prepare-method))
      (let [allow-method (or (vs/getpath options "allow.method") "")]
        (if (not (str/includes? allow-method (oget spec :method)))
          [nil (ctx-error ctx "spec_method_allow"
                          (str "Method \"" (oget spec :method) "\" not allowed by SDK option allow.method value: \"" allow-method "\""))]
          (do
            (oset! spec :params (ucall ctx :prepare-params))
            (oset! spec :query (ucall ctx :prepare-query))
            (oset! spec :headers (ucall ctx :prepare-headers))
            (if (= "graphql" (vs/getprop point "kind"))
              ;; GraphQL addresses one endpoint: no path parts, no query
              ;; string, and the body carries the operation. prepare-body is
              ;; skipped deliberately — it only emits a body for data-input
              ;; ops, whereas every GraphQL op posts one, including
              ;; load/list/remove.
              (do
                (oset! spec :body (ucall ctx :graphql-body))
                (oset! spec :path "")
                ;; prepare-query already copied the op's match arguments into
                ;; the query string. Those same values are bound as operation
                ;; variables, so leaving them would send /graphql?id=i1.
                (oset! spec :query (vs/jm))
                (.put ^java.util.Map (oget spec :headers) "content-type" GRAPHQL-CONTENT-TYPE))
              (do
                (oset! spec :body (ucall ctx :prepare-body))
                (oset! spec :path (ucall ctx :prepare-path))))
            (when-let [ex (oget (oget ctx :ctrl) :explain)] (.put ^java.util.Map ex "spec" spec))
            ;; Whatever prepare-auth sets in the query, under whichever name,
            ;; is the credential; a key it leaves as it was is the caller's.
            (let [query (java.util.LinkedHashMap. ^java.util.Map (or (oget spec :query) (vs/jm)))
                  [s err] (ucall ctx :prepare-auth)]
              (if err [nil err]
                  (do
                    (oset! s :authquery
                           (vec (for [[k v] (or (oget s :query) (vs/jm))
                                      :when (or (not (.containsKey query k)) (not= (.get query k) v))]
                                  k)))
                    (oset! ctx :spec s) [s nil])))))))))

(defn u-make-url [ctx]
  (let [spec (oget ctx :spec) result (oget ctx :result)]
    (cond
      (nil? spec) ["" (ctx-error ctx "url_no_spec" "Expected context spec property to be defined.")]
      (nil? result) ["" (ctx-error ctx "url_no_result" "Expected context result property to be defined.")]
      :else
      (let [url (atom (vs/join (vs/jt (oget spec :base) (oget spec :prefix) (oget spec :path) (oget spec :suffix)) "/" true))
            resmatch (vs/jm)
            ;; Sent with the request, never recorded as the entity's match.
            authquery (set (oget spec :authquery []))
            point (oget ctx :point)
            orig (when point (vs/getprop point "orig"))]
        ;; A route the definition ends with a slash keeps it: a server such as a
        ;; Django REST one redirects or refuses the route without it.
        (when (and (string? orig) (str/ends-with? orig "/") (empty? (str (oget spec :suffix)))
                   (not (str/ends-with? @url "/")))
          (swap! url str "/"))
        (doseq [item (or (vs/items (oget spec :params)) [])]
          (let [k (vs/getprop item 0) v (vs/getprop item 1)]
            (when (and (some? v) (string? k))
              (let [placeholder (str "{" k "}")
                    val-str (if (string? v) v (vs/stringify v))
                    encoded (vs/escurl val-str)]
                (reset! url (str/replace @url placeholder encoded))
                (.put ^java.util.Map resmatch k v)))))
        ;; A placeholder left in the route would send the request to the wrong
        ;; route. The base's own placeholders are server variables, resolved
        ;; with the options.
        (if-let [unfilled (let [base (str/replace (str (or (oget spec :base) "")) #"/+$" "")]
                            (seq (re-seq #"\{[^{}/]+\}"
                                         (if (str/starts-with? @url base) (subs @url (count base)) @url))))]
          ["" (ctx-error ctx "url_param_missing"
                         (str "URL path has no value for " (str/join ", " unfilled) "."))]
          (do
            (let [qsep (atom "?")]
              (doseq [item (or (vs/items (oget spec :query)) [])]
                (let [k (vs/getprop item 0) v (vs/getprop item 1)]
                  (when (and (some? v) (string? k))
                    (let [val-str (if (string? v) v (vs/stringify v))]
                      (reset! url (str @url @qsep (vs/escurl k) "=" (vs/escurl val-str)))
                      (reset! qsep "&")
                      (when-not (contains? authquery k)
                        (.put ^java.util.Map resmatch k v)))))))
            (oset! result :resmatch resmatch)
            [@url nil]))))))

(defn u-make-fetch-def [ctx]
  (let [spec (oget ctx :spec)]
    (if (nil? spec) [nil (ctx-error ctx "fetchdef_no_spec" "Expected context spec property to be defined.")]
        (do
          (when (nil? (oget ctx :result)) (oset! ctx :result (make-result (vs/jm))))
          (oset! spec :step "prepare")
          (let [[url err] (ucall ctx :make-url)]
            (if err [nil err]
                (do
                  (oset! spec :url url)
                  (let [fetchdef (vs/jm "url" url "method" (oget spec :method) "headers" (oget spec :headers))
                        body (oget spec :body)]
                    (when (some? body)
                      (.put ^java.util.Map fetchdef "body" (if (vs/ismap body) (vs/jsonify body) body)))
                    [fetchdef nil]))))))))

(defn u-make-request [ctx]
  (if (some? (out-get ctx "request")) [(out-get ctx "request") nil]
      (let [spec (oget ctx :spec)
            response (make-response (vs/jm))
            result (make-result (vs/jm))]
        (oset! ctx :result result)
        (if (nil? spec) [nil (ctx-error ctx "request_no_spec" "Expected context spec property to be defined.")]
            (let [[fetchdef err] (ucall ctx :make-fetch-def)]
              (if err
                (do (oset! response :err err) (oset! ctx :response response) (oset! spec :step "postrequest") [response nil])
                (do
                  (when-let [ex (oget (oget ctx :ctrl) :explain)] (.put ^java.util.Map ex "fetchdef" fetchdef))
                  (oset! spec :step "prerequest")
                  (let [url (or (vs/getprop fetchdef "url") "")
                        [fetched fetch-err] ((uget ctx :fetcher) ctx url fetchdef)
                        resp (cond
                               fetch-err (do (oset! response :err fetch-err) response)
                               (nil? fetched) (make-response (vs/jm "err" (ctx-error ctx "request_no_response" "response: undefined")))
                               (vs/ismap fetched) (make-response fetched)
                               :else (do (oset! response :err (ctx-error ctx "request_invalid_response" "response: invalid type")) response))]
                    (oset! spec :step "postrequest")
                    (oset! ctx :response resp)
                    [resp nil]))))))))

(defn u-result-basic [ctx]
  (let [response (oget ctx :response) result (oget ctx :result)]
    (when (and result response)
      (oset! result :status (oget response :status))
      (oset! result :status-text (oget response :status-text))
      (cond
        (>= (oget result :status) 400)
        (let [msg (str "request: " (oget result :status) ": " (oget result :status-text))
              prev (oget result :err)]
          (if prev
            (oset! result :err (ctx-error ctx "request_status" (str (err-msg prev) ": " msg)))
            (oset! result :err (ctx-error ctx "request_status" msg))))
        (oget response :err) (oset! result :err (oget response :err))))
    result))

(defn u-result-headers [ctx]
  (let [response (oget ctx :response) result (oget ctx :result)]
    (when result
      (oset! result :headers (if (and response (vs/ismap (oget response :headers))) (oget response :headers) (vs/jm))))
    result))

(defn u-result-body [ctx]
  (let [response (oget ctx :response) result (oget ctx :result)]
    (when (and result response (oget response :json) (oget response :body))
      (oset! result :body ((oget response :json))))
    result))

(defn u-transform-response [ctx]
  (let [spec (oget ctx :spec) result (oget ctx :result) point (oget ctx :point)]
    (when spec (oset! spec :step "resform"))
    (if (or (nil? result) (not (oget result :ok))) nil
        (let [transform (to-map (vs/getprop point "transform"))]
          (if (nil? transform) nil
              (let [resform (vs/getprop transform "res")]
                (if (nil? resform) nil
                    (let [resdata (vs/transform
                                   (vs/jm "ok" (oget result :ok) "status" (oget result :status)
                                          "statusText" (oget result :status-text) "headers" (oget result :headers)
                                          "body" (oget result :body) "err" (oget result :err)
                                          "resdata" (oget result :resdata) "resmatch" (oget result :resmatch))
                                   resform)]
                      (oset! result :resdata resdata)
                      resdata))))))))

(defn u-make-response [ctx]
  (if (some? (out-get ctx "response")) [(out-get ctx "response") nil]
      (let [spec (oget ctx :spec) result (oget ctx :result) response (oget ctx :response)]
        (cond
          (nil? spec) [nil (ctx-error ctx "response_no_spec" "Expected context spec property to be defined.")]
          (nil? response) [nil (ctx-error ctx "response_no_response" "Expected context response property to be defined.")]
          (nil? result) [nil (ctx-error ctx "response_no_result" "Expected context result property to be defined.")]
          :else
          (do
            (oset! spec :step "response")
            ;; A body reader that throws (a non-JSON body) fails the result,
            ;; as in ts; it must not escape the pipeline with the raw spec
            ;; still on the explain record.
            (try
              (ucall ctx :result-basic)
              (ucall ctx :result-headers)
              (ucall ctx :result-body)
              ;; GraphQL reports failures as a top-level `errors` array under
              ;; HTTP 200, so result-basic's status check never sees them. Lift
              ;; them here, before the response transform tries to unwrap data
              ;; that is not there.
              (ucall ctx :graphql-errors)
              (ucall ctx :transform-response)
              (when (nil? (oget result :err)) (oset! result :ok true))
              (catch Throwable e
                (oset! result :err e)))
            (when-let [ex (oget (oget ctx :ctrl) :explain)] (.put ^java.util.Map ex "result" result))
            [response nil])))))

(defn u-make-result [ctx]
  (if (some? (out-get ctx "result")) [(out-get ctx "result") nil]
      (let [op (oget ctx :op) entity (oget ctx :entity) spec (oget ctx :spec) result (oget ctx :result)]
        (cond
          (nil? spec) [nil (ctx-error ctx "result_no_spec" "Expected context spec property to be defined.")]
          (nil? result) [nil (ctx-error ctx "result_no_result" "Expected context result property to be defined.")]
          :else
          (do
            (oset! spec :step "result")
            (ucall ctx :transform-response)
            (when (= "list" (op-name op))
              (let [resdata (oget result :resdata)]
                (oset! result :resdata (vs/jt))
                (when (and (vs/islist resdata) (pos? (vs/size resdata)) entity)
                  (let [out (vs/jt)]
                    (doseq [entry (vec resdata)]
                      (let [e ((:make entity))]
                        (when (vs/ismap entry) ((:data-set e) entry))
                        (.add ^java.util.List out e)))
                    (oset! result :resdata out)))))
            (when-let [ex (oget (oget ctx :ctrl) :explain)] (.put ^java.util.Map ex "result" result))
            [result nil])))))

(defn u-make-error [ctx err]
  (let [ctx (or ctx (make-context (vs/jm) nil))
        op (or (oget ctx :op) (make-operation (vs/jm)))
        opname0 (op-name op)
        opname (if (or (= opname0 "") (= opname0 "_")) "unknown operation" opname0)
        result (or (oget ctx :result) (make-result (vs/jm)))]
    (oset! result :ok false)
    (oset! ctx :result result)
    (let [err (or err (oget result :err) (ctx-error ctx "unknown" "unknown error"))
          errmsg (err-msg err)
          msg0 (str SDK-NAME "SDK: " opname ": " errmsg)
          msg (ucall ctx :clean msg0)
          spec (oget ctx :spec)]
      (oset! result :err nil)
      (clean-explain! ctx)
      (when-let [ex (oget (oget ctx :ctrl) :explain)] (.put ^java.util.Map ex "err" (vs/jm "message" msg)))
      ;; Cleaned COPIES of the result and spec, never the live objects.
      (let [code (when (sdk-error? err) (ucall ctx :clean (:code err)))
            sdk-err (assoc (make-error-obj code msg ctx)
                           :result (ucall ctx :clean result)
                           :spec (ucall ctx :clean spec))]
        (oset! (oget ctx :ctrl) :err sdk-err)
        ;; Fire PreUnexpected so observability features (metrics, telemetry,
        ;; audit, debug) close/record error paths that never reach PreDone
        ;; (e.g. a PrePoint rbac short-circuit). Fires after ctrl.err is set so
        ;; hooks can read the error; features guard against double-recording
        ;; when PreDone already fired.
        (when (oget ctx :utility)
          (ucall ctx :feature-hook "PreUnexpected"))
        (if (= false (oget (oget ctx :ctrl) :throw))
          (oget result :resdata)
          (sdk-throw sdk-err))))))

(defn u-done [ctx]
  (clean-explain! ctx)
  (let [result (oget ctx :result)]
    (if (and result (oget result :ok))
      (oget result :resdata)
      (ucall ctx :make-error nil))))

;; Public camelCase option key -> the kebab-case keyword naming a utility
;; member, or nil when the key is not a public name.
;;
;; Public utility names are camelCase and carry neither a hyphen nor an
;; underscore, so either means the caller named something of their own -
;; possibly the INTERNAL spelling of a real member. `make-error` must stay an
;; extension in :custom; replacing the pipeline function with a non-callable
;; would break the error path on the next request, silently.
;; `str` is the clojure.string ALIAS in this namespace, so core's str is
;; qualified here rather than shadowed.
(defn- util-member [k]
  (let [n (name k)]
    (when-not (or (str/includes? n "-") (str/includes? n "_"))
      (keyword (str/replace n #"([A-Z])"
                            (fn [[_ c]]
                              (clojure.core/str "-" (str/lower-case c))))))))

;; A feature's name is not a field name: only the sensitive names inside its
;; settings count, so `secrets` does not make every setting a secret. Entity
;; blocks hold entity settings and seeded records, never a credential.
(defn- clean-add-options [ctx opts]
  (let [noent #(omit-keys % ["entity"])
        top (dissoc (into {} opts) "feature" "entity")
        feature (vs/getprop opts "feature")]
    (u-clean-add-sensitive ctx (cond-> top (contains? top "test") (update "test" noent)))
    (doseq [fopts (cond (vs/ismap feature) (map #(vs/getprop feature %) (vs/keysof feature))
                        (vs/islist feature) (vec feature)
                        :else [feature])]
      (u-clean-add-sensitive ctx (noent fopts)))))

(defn u-make-options [ctx]
  (let [options (or (oget ctx :options) (vs/jm))
        custom-utils (vs/getprop options "utility")]
    ;; A key naming a real utility member REPLACES it; anything else is
    ;; attached as a custom extra. Shelving everything in :custom - a map
    ;; nothing reads - made `{"utility" {"fetcher" ...}}`, the documented
    ;; transport seam, a silent no-op here while ts honoured it.
    (when (and (vs/ismap custom-utils) (oget ctx :utility))
      (let [util (oget ctx :utility)
            members (deref util)]
        (doseq [item (or (vs/items custom-utils) [])]
          (let [k (vs/getprop item 0)
                v (vs/getprop item 1)
                member (util-member k)]
            (if (and member (not= member :custom) (contains? members member))
              (oset! util member v)
              (.put ^java.util.Map (oget util :custom) k v))))))
    (let [;; `auth` nil is the documented way to disable auth outright, and
          ;; u-prepare-auth honours it before it ever reads the apikey. It
          ;; cannot survive validate: a stored null reads as "no value", so the
          ;; optspec's `auth` default fires and the suppression silently
          ;; becomes "use default auth" - transmitting the credential the
          ;; caller withheld. Withhold the key for validate, then put the nil
          ;; back. Same fix as ts/js/go makeOptions.
          ;;
          ;; `.containsKey` rather than a nil check on the value: the latter
          ;; cannot tell an ABSENT auth from a suppressed one, and only the
          ;; second is a suppression.
          auth-suppressed (and (vs/ismap options)
                               (.containsKey ^java.util.Map options "auth")
                               (nil? (.get ^java.util.Map options "auth")))
          opts0 (let [c (vs/clone options)] (if (vs/ismap c) c (vs/jm)))
          _ (when auth-suppressed (.remove ^java.util.Map opts0 "auth"))
          ;; Feature add-order. options.feature may be given as an ordered
          ;; ARRAY of {name active ...opts} entries (array position = add
          ;; order) or a {name {opts}} map. Normalize an array to a map (so
          ;; merge/validate/init are unchanged) and remember the explicit
          ;; order; a map defaults to test-first so the `test` mock transport
          ;; is the base of the transport wrapper chain.
          explicit-order
          (let [feature-raw (vs/getprop opts0 "feature")]
            (when (vs/islist feature-raw)
              (let [fmap (vs/jm) order (vs/jt)]
                (doseq [entry (vec feature-raw)]
                  (when (vs/ismap entry)
                    (let [nm (vs/getprop entry "name")]
                      (when (string? nm)
                        (let [fopts (vs/clone entry)]
                          (vs/delprop fopts "name")
                          (.put ^java.util.Map fmap nm fopts)
                          (.add ^java.util.List order nm))))))
                (.put ^java.util.Map opts0 "feature" fmap)
                order)))
          config (or (oget ctx :config) (vs/jm))
          cfgopts (let [c (vs/getprop config "options")] (if (vs/ismap c) c (vs/jm)))
          ;; THE OPTION SPEC IS GENERATED, NOT WRITTEN HERE.
          ;;
          ;; Built from the model: main.kit.optspec for the standard
          ;; options, plus one entry per feature this target carries, from
          ;; that feature's own config.options / config.optspec. Editing
          ;; this file to add an option would put it back where it was —
          ;; one of twenty hand-maintained copies of a schema nothing
          ;; cross-checked — so add it to the model instead.
          optspec @optspec-parsed
          ;; The secret registry exists BEFORE validation, fed from the raw
          ;; input, so the constructor's own rejection of a mistyped
          ;; credential is clean too. A shallow merge over the schema
          ;; defaults: the clean block is flat.
          cleancfg (make-clean-config
                    (let [out (vs/jm)]
                      (doseq [src [(vs/getprop optspec "clean") (vs/getprop cfgopts "clean")
                                   (vs/getprop opts0 "clean")]]
                        (when (vs/ismap src)
                          (doseq [k (vs/keysof src)] (.put ^java.util.Map out k (vs/getprop src k)))))
                      out))
          cleanctx (atom {:options (vs/jm "__derived__" (vs/jm "clean" cleancfg))})
          _ (clean-add-options cleanctx (omit-keys opts0 ["clean"]))
          _ (doseq [raw (concat (splitvalues (vs/getpath cfgopts "clean.values"))
                                (splitvalues (vs/getpath opts0 "clean.values")))]
              (u-clean-add cleanctx raw))
          sys-fetch (vs/getpath opts0 "system.fetch")
          ;; Cloned: merge writes through the nested maps of what it reads.
          merged (vs/merge (vs/jt (vs/jm) (vs/clone cfgopts) opts0))
          validated (try (vs/validate merged optspec)
                         (catch RuntimeException e
                           (throw (RuntimeException. ^String (u-clean cleanctx (str (.getMessage e)))))))
          opts (if (vs/ismap validated) validated (vs/jm))
          ;; Restore the suppression the optspec default would otherwise erase.
          _ (when auth-suppressed (.put ^java.util.Map opts "auth" nil))
          ;; Resolve a templated base URL (e.g. https://{tenant_id}.hanko.io).
          ;; Every placeholder must resolve to a non-empty value: from
          ;; options["server"] (user), else the config default. A placeholder
          ;; that resolves to "" is a construction ERROR in live mode - the URL
          ;; cannot work - but in test mode substitutes the deterministic value
          ;; "test-<name>" so offline tests need no configuration.
          ;;
          ;; Accepting `server` in the option spec without this is a trap: the
          ;; option validates and is then ignored, so a templated URL still
          ;; reaches the wire with a literal {name} in it.
          base (vs/getprop opts "base")
          _ (when (and (string? base) (.contains ^String base "{"))
              (let [testmode (or (true? (vs/getpath opts "test.active"))
                                 (true? (vs/getpath opts "feature.test.active")))
                    server (let [s (vs/getprop opts "server")]
                             (if (vs/ismap s) s (vs/jm)))
                    sdkname (let [n (vs/getpath config "main.name")]
                              (if (and (string? n) (seq n)) n "SDK"))
                    resolved (str/replace
                               base #"\{([A-Za-z0-9_]+)\}"
                               (fn [[_ name]]
                                 (let [v (vs/getprop server name)
                                       v (if (string? v) v "")]
                                   (cond
                                     (seq v) v
                                     testmode (str "test-" name)
                                     :else
                                     (throw (IllegalArgumentException.
                                              (str sdkname ": the server variable '" name
                                                   "' is required: the API base URL is '" base
                                                   "' - pass {\"server\" {\"" name "\" \"...\"}}"
                                                   " in the SDK options")))))))]
                (vs/setprop opts "base" resolved)))]
      (when sys-fetch
        (when (not (vs/ismap (vs/getprop opts "system"))) (.put ^java.util.Map opts "system" (vs/jm)))
        (.put ^java.util.Map (vs/getprop opts "system") "fetch" sys-fetch))
      (let [;; Resolve the feature add-order: an explicit array order (above)
            ;; wins; otherwise order the map test-first, then the remaining
            ;; names sorted, so the outcome is deterministic and `test` is
            ;; always the base transport.
            feature-order
            (if explicit-order
              explicit-order
              (let [fmap (let [f (vs/getprop opts "feature")] (if (vs/ismap f) f (vs/jm)))
                    names (vec (sort (map str (or (vs/keysof fmap) []))))
                    order (vs/jt)]
                (when (some #(= % "test") names) (.add ^java.util.List order "test"))
                (doseq [n names] (when (not= n "test") (.add ^java.util.List order n)))
                order))
            derived (vs/jm "clean" cleancfg "featureorder" feature-order)]
        (.put ^java.util.Map opts "__derived__" derived)
        ;; Again over the merged result: the config's own defaults can carry one.
        (clean-add-options (atom {:options opts}) (omit-keys opts ["clean" "__derived__"]))
        opts))))

;; ---------------------------------------------------------------------------
;; Default transport + fetcher gate.
;; ---------------------------------------------------------------------------

(defn default-http-fetch [fullurl fetchdef]
  (let [method-str (or (vs/getprop fetchdef "method") "GET")
        body-str (vs/getprop fetchdef "body")
        headers (or (vs/getprop fetchdef "headers") (vs/jm))]
    (try
      (let [url (java.net.URL. fullurl)
            conn (.openConnection url)]
        (.setRequestMethod ^java.net.HttpURLConnection conn (str/upper-case method-str))
        (let [has-ua (atom false)]
          (doseq [item (or (vs/items headers) [])]
            (let [k (vs/getprop item 0) v (vs/getprop item 1)]
              (when (string? v)
                (when (= (str/lower-case (str k)) "user-agent") (reset! has-ua true))
                (.setRequestProperty ^java.net.HttpURLConnection conn (str k) v))))
          (when-not @has-ua
            (.setRequestProperty ^java.net.HttpURLConnection conn "User-Agent"
                                 (str "Mozilla/5.0 (compatible; " SDK-NAME "SDK/1.0)"))))
        (when (or (string? body-str) (bytes? body-str) (instance? java.io.InputStream body-str))
          (.setDoOutput ^java.net.HttpURLConnection conn true)
          (with-open [os (.getOutputStream ^java.net.HttpURLConnection conn)]
            (cond
              (string? body-str) (.write os (.getBytes ^String body-str "UTF-8"))
              (bytes? body-str) (.write os ^bytes body-str)
              :else (.transferTo ^java.io.InputStream body-str os))))
        (let [code (.getResponseCode ^java.net.HttpURLConnection conn)
              is (try (.getInputStream ^java.net.HttpURLConnection conn) (catch Exception _ (.getErrorStream ^java.net.HttpURLConnection conn)))
              body (when is (slurp is))
              resp-headers (vs/jm)]
          (doseq [[k vlist] (.getHeaderFields ^java.net.HttpURLConnection conn)]
            (when k (.put ^java.util.Map resp-headers (str/lower-case k) (str/join "," vlist))))
          (let [json-body (try (when (and body (seq body)) (json-parse body)) (catch Exception _ nil))]
            [(vs/jm "status" code "statusText" "" "headers" resp-headers
                    "json" (fn [] json-body) "body" body) nil])))
      (catch Throwable e
        [(vs/jm "status" 0 "statusText" (str (.getName (class e)) ": " (.getMessage e))
                "headers" (vs/jm) "json" (fn [] nil) "body" nil) nil]))))

(defn u-fetcher [ctx fullurl fetchdef]
  (let [client (oget ctx :client)]
    (if (not= (client-mode client) "live")
      [nil (ctx-error ctx "fetch_mode_block"
                      (str "Request blocked by mode: \"" (client-mode client) "\" (URL was: \"" fullurl "\")"))]
      (let [options (client-options-map client)]
        (if (= true (vs/getpath options "feature.test.active"))
          [nil (ctx-error ctx "fetch_test_block"
                          (str "Request blocked as test feature is active (URL was: \"" fullurl "\")"))]
          (let [sys-fetch (vs/getpath options "system.fetch")]
            (cond
              (nil? sys-fetch) (default-http-fetch fullurl fetchdef)
              (vs/isfunc sys-fetch) (sys-fetch fullurl fetchdef)
              :else [nil (ctx-error ctx "fetch_invalid" "system.fetch is not a valid function")])))))))

;; ---------------------------------------------------------------------------
;; The base utility map (keys mirror the reference utility members).
;; ---------------------------------------------------------------------------

(defn base-utility-map []
  {:clean u-clean :clean-add u-clean-add :done u-done :make-error u-make-error
   :feature-add feature-add :feature-hook feature-hook :feature-init feature-init
   :fetcher u-fetcher :make-fetch-def u-make-fetch-def :make-context (fn [cm bc] (make-context cm bc))
   :make-options u-make-options :make-request u-make-request :make-response u-make-response
   :make-result u-make-result :make-point u-make-point :make-spec u-make-spec :make-url u-make-url
   :param u-param :prepare-auth u-prepare-auth :prepare-body u-prepare-body
   :prepare-headers u-prepare-headers :prepare-method u-prepare-method :prepare-params u-prepare-params
   :prepare-path u-prepare-path :prepare-query u-prepare-query
   :graphql-body u-graphql-body :graphql-errors u-graphql-errors
   :result-basic u-result-basic :result-body u-result-body :result-headers u-result-headers
   :transform-request u-transform-request :transform-response u-transform-response})

;; feature-hook needs to be reachable via the utility atom too (some callers
;; invoke it through the utility object).
(defn feature-hook-call [ctx name] (feature-hook ctx name))
