
import { cmp, Content, File } from '@voxgig/sdkgen'

import {
  KIT,
  getModelPath,
} from '@voxgig/apidef'


// Generates ts/test/readme_examples.test.ts — a test that reads the
// repo's root README.md, extracts every fenced ```ts block, and puts each
// one through TWO gates:
//
//  (1) TYPE-CHECK — every block is wrapped in an isolated block scope
//      inside one async function, written to a temp module, and compiled
//      with the repo's local `tsc --noEmit`. This catches API-shape drift
//      that a runtime test cannot — e.g. reading `.data` off a `list()`
//      result (a bare `Advice[]`) is a compile error, so a stale
//      `advices.data` snippet fails the build.
//
//  (2) EXECUTE — every runnable block is rewritten to seeded test mode
//      (`new <Sdk>SDK(...)` and any `<Sdk>SDK.test(...)` become
//      `<Sdk>SDK.test({ entity: { <entname>: { test01: { id: 'test01' } } } })`
//      seeding a fixture for every entity), transpiled to JS, and RUN
//      offline. A LIVE example constructed with `new <Sdk>SDK()` is now
//      actually executed, so a documented call that doesn't work at
//      runtime (undefined method, wrong-arg-count, bad symbol) FAILS the
//      test. Only an expected domain error (a 404 / "Not found" for an
//      unseeded id) is tolerated.
//
// Both gates run against whatever the README currently says, so editing a
// snippet to misuse the SDK — at the type level OR the runtime level —
// makes THIS test fail.
//
// A THIRD gate TYPE-CHECKS the per-language REFERENCE.md: its ```ts blocks
// are extracted and compiled the same way, minus the method-signature
// illustration blocks (typed-param sigs, `field: /* type */` placeholders)
// that are documentation rather than runnable code. This catches the same
// class of API-shape drift in REFERENCE.md — e.g. a `number` id shown as a
// quoted string in a `load({ id })` example is a compile error.
//
// A FOURTH gate TYPE-CHECKS this target's OWN per-language README.md the
// exact same way (same `tsc --noEmit` against the shared seeded client, same
// `isReferenceSnippet` illustration-skip). The per-language README carries
// ~20 how-to / error-handling / entity examples that no other gate touches;
// without this gate a merged section can ship a real type bug — e.g. a
// string id passed to a `number`-typed `load({ id })` (TS2322) — undetected.
// Shape-illustration blocks (`{ ok: boolean; status: number; ... }`) list
// bare type keywords as values, so isReferenceSnippet skips them too.
const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { ctx$: { model } } = props
  const Name = model.const.Name

  // Seed a fixture for every active entity so list()/load() resolve
  // offline in test mode with no network. Keyed by the entity's model
  // name (the same key the test-mode transport looks up).
  const entity = getModelPath(model, `main.${KIT}.entity`)
  const seedEntities: Record<string, any> = {}
  Object.values(entity).forEach((e: any) => {
    if (e && false !== e.active && 'string' === typeof e.name) {
      seedEntities[e.name] = { test01: { id: 'test01' } }
    }
  })
  const seedLiteral = JSON.stringify({ entity: seedEntities })

  File({ name: 'readme_examples.test.ts' }, () => {
    Content(`// Verifies every TypeScript snippet in the repo's root README.md both
// TYPE-CHECKS and EXECUTES in offline test mode, and TYPE-CHECKS the usage
// snippets in this target's REFERENCE.md AND its per-language README.md.
//
// (1) Type-check: each fenced \\\`\\\`\\\`ts block is extracted, wrapped in
//     its own block scope inside one async function, written to a temp
//     module, and compiled with the repo's local \\\`tsc --noEmit\\\`. A
//     snippet that misuses the SDK types (e.g. \\\`.data\\\` on a
//     \\\`list()\\\` array) is a compile error and fails this test.
// (2) Execute: each runnable block is rewritten to seeded test mode
//     (\\\`new ${Name}SDK(...)\\\` / \\\`${Name}SDK.test(...)\\\` become
//     \\\`${Name}SDK.test({ entity: ... })\\\`), transpiled to JS, and run
//     offline. A programming error (undefined method, wrong-arg-count,
//     bad symbol) fails the test; only an expected domain error (a 404 /
//     "Not found" for an unseeded id) is tolerated.
//
// Generated by @voxgig/sdkgen — do not edit by hand.

import { describe, it } from 'node:test'
import assert from 'node:assert'
import * as Fs from 'node:fs'
import * as Path from 'node:path'
import { createRequire } from 'node:module'
import { spawnSync } from 'node:child_process'

import { ${Name}SDK } from '..'


const SDK_NAME = '${Name}SDK'

// A fixture for every entity, so list()/load() resolve offline with no
// network. Snippet client construction is rewritten to seed this.
const TEST_SEED = ${seedLiteral}
const SEED_ARG = JSON.stringify(TEST_SEED)
const SEEDED_CTOR = SDK_NAME + '.test(' + SEED_ARG + ')'


// Pull out the body of every \\\`\\\`\\\`ts fenced code block.
function extractTsBlocks(md: string): string[] {
  const blocks: string[] = []
  const re = /\`\`\`ts\\n([\\s\\S]*?)\`\`\`/g
  let m: RegExpExecArray | null
  while ((m = re.exec(md)) !== null) {
    blocks.push(m[1])
  }
  return blocks
}


// Snippet import lines reference the published package name, which is not
// resolvable from inside the repo; the SDK symbol is supplied by the one
// module-level import we emit / inject instead.
function stripImports(code: string): string {
  return code.replace(/^\\s*import\\s+[^\\n]*$/gm, '')
}


function buildModule(blocks: string[]): string {
  const body = blocks.map((b, i) =>
    '  // --- README snippet ' + i + ' ---\\n  {\\n' +
    stripImports(b).replace(/^/gm, '    ') + '\\n  }'
  ).join('\\n\\n')

  return [
    'import { ' + SDK_NAME + " } from '..'",
    '',
    'async function __readme_examples() {',
    '  // Shared client for snippets that reference \\\`client\\\` without',
    '  // constructing one (e.g. the direct() example).',
    '  const client = ' + SDK_NAME + '.test()',
    '  void client',
    body,
    '}',
    'void __readme_examples',
    '',
  ].join('\\n')
}


// REFERENCE.md and the per-language README.md also carry ILLUSTRATION blocks
// — documentation, not runnable TS — that must be skipped so the gate does
// not falsely fail on them (a false failure on an illustration block is a
// gate bug). Three shapes are skipped:
//   1. method-signature blocks with a typed-parameter signature ("?:")
//      (e.g. a bare constructor signature \\\`options?: { base?: string }\\\`);
//   2. placeholder-comment values ("/*") in create examples
//      (e.g. \\\`field: /* string */\\\`);
//   3. type-SHAPE blocks that list fields as \\\`name: TypeKeyword\\\` with the
//      type standing alone as the value — e.g. the DirectResult / FetchDef
//      shape \\\`{ ok: boolean; status: number; ... }\\\`. Those bare keywords are
//      undeclared VALUES (TS2693 "only refers to a type"), so the block is
//      documentation. Matched only at the START of a line, so a genuine
//      annotation inside runnable code (e.g. \\\`(ctx: any) => ...\\\`) is NOT
//      skipped and still type-checks.
// Everything that survives is compiled against a shared seeded client,
// exactly like the root README.
const SHAPE_ILLUSTRATION =
  /^\\s*[A-Za-z_$][\\w$]*\\??\\s*:\\s*(?:boolean|number|string|object|any|unknown|never|void|symbol|bigint|Record<|Partial<|Array<|Map<|Set<)/m
function isReferenceSnippet(code: string): boolean {
  if (code.includes('?:')) {
    return false
  }
  if (code.includes('/*')) {
    return false
  }
  if (SHAPE_ILLUSTRATION.test(code)) {
    return false
  }
  return true
}


// Turn a documented snippet into an offline-runnable one: strip imports,
// rewrite real client construction (\\\`new ${Name}SDK(...)\\\` and any
// \\\`${Name}SDK.test(...)\\\`) to a seeded test-mode client, and give
// snippets that reference \\\`client\\\` without constructing one a shared
// seeded client.
function rewriteForRun(code: string): string {
  let out = stripImports(code)
  out = out.replace(/new\\s+${Name}SDK\\s*\\([^)]*\\)/g, () => SEEDED_CTOR)
  out = out.replace(/${Name}SDK\\.test\\s*\\([^)]*\\)/g, () => SEEDED_CTOR)
  if (/\\bclient\\b/.test(out) && !/\\b(?:const|let|var)\\s+client\\b/.test(out)) {
    out = 'const client = ' + SEEDED_CTOR + '\\n' + out
  }
  return out
}


describe('README examples', () => {
  it('every TypeScript snippet in the root README type-checks', () => {
    const readmePath = Path.join(__dirname, '..', '..', 'README.md')
    const md = Fs.readFileSync(readmePath, 'utf8')

    const blocks = extractTsBlocks(md)
    assert(blocks.length > 0, 'No TypeScript code blocks found in root README.md')

    const tsDir = Path.join(__dirname, '..')
    // Leading dot: TypeScript wildcard includes skip dot-files, so a
    // stray temp file is never swept into the normal build.
    const tmpFile = Path.join(tsDir, 'test', '.readme_examples.gen.ts')
    Fs.writeFileSync(tmpFile, buildModule(blocks), 'utf8')

    try {
      const requireFrom = createRequire(__filename)
      const tsc = requireFrom.resolve('typescript/bin/tsc')

      const res = spawnSync(process.execPath, [
        tsc,
        '--noEmit',
        '--strict',
        '--target', 'ES2022',
        '--module', 'nodenext',
        '--moduleResolution', 'nodenext',
        '--esModuleInterop',
        '--resolveJsonModule',
        '--skipLibCheck',
        '--types', 'node',
        tmpFile,
      ], { cwd: tsDir, encoding: 'utf8' })

      const out = ((res.stdout || '') + (res.stderr || '')).trim()
      assert.strictEqual(res.status, 0,
        'README TypeScript snippets failed to type-check:\\n\\n' + out + '\\n')
    } finally {
      Fs.rmSync(tmpFile, { force: true })
    }
  })


  it('every usage TypeScript snippet in REFERENCE.md type-checks', () => {
    const refPath = Path.join(__dirname, '..', 'REFERENCE.md')
    // A target without a REFERENCE.md has nothing to check.
    if (!Fs.existsSync(refPath)) {
      return
    }
    const md = Fs.readFileSync(refPath, 'utf8')

    const blocks = extractTsBlocks(md).filter(isReferenceSnippet)
    assert(blocks.length > 0, 'No checkable TypeScript code blocks found in REFERENCE.md')

    const tsDir = Path.join(__dirname, '..')
    const tmpFile = Path.join(tsDir, 'test', '.reference_examples.gen.ts')
    Fs.writeFileSync(tmpFile, buildModule(blocks), 'utf8')

    try {
      const requireFrom = createRequire(__filename)
      const tsc = requireFrom.resolve('typescript/bin/tsc')

      const res = spawnSync(process.execPath, [
        tsc,
        '--noEmit',
        '--strict',
        '--target', 'ES2022',
        '--module', 'nodenext',
        '--moduleResolution', 'nodenext',
        '--esModuleInterop',
        '--resolveJsonModule',
        '--skipLibCheck',
        '--types', 'node',
        tmpFile,
      ], { cwd: tsDir, encoding: 'utf8' })

      const out = ((res.stdout || '') + (res.stderr || '')).trim()
      assert.strictEqual(res.status, 0,
        'REFERENCE.md TypeScript snippets failed to type-check:\\n\\n' + out + '\\n')
    } finally {
      Fs.rmSync(tmpFile, { force: true })
    }
  })


  it('every usage TypeScript snippet in the per-language README.md type-checks', () => {
    // The per-language README (this target's README.md, one level up from
    // test/) carries the tutorial / error-handling / how-to / entity-interface
    // examples. Type-check them exactly like REFERENCE.md: extract the \\\`\\\`\\\`ts
    // blocks, drop the illustration blocks (isReferenceSnippet), and compile
    // the rest against the shared seeded client. This is what catches a real
    // type bug in a merged section — e.g. \\\`load({ id: 'example_id' })\\\` against
    // a \\\`number\\\`-typed match (TS2322).
    const readmePath = Path.join(__dirname, '..', 'README.md')
    // A target without a per-language README.md has nothing to check.
    if (!Fs.existsSync(readmePath)) {
      return
    }
    const md = Fs.readFileSync(readmePath, 'utf8')

    const blocks = extractTsBlocks(md).filter(isReferenceSnippet)
    assert(blocks.length > 0, 'No checkable TypeScript code blocks found in the per-language README.md')

    const tsDir = Path.join(__dirname, '..')
    const tmpFile = Path.join(tsDir, 'test', '.readme_lang_examples.gen.ts')
    Fs.writeFileSync(tmpFile, buildModule(blocks), 'utf8')

    try {
      const requireFrom = createRequire(__filename)
      const tsc = requireFrom.resolve('typescript/bin/tsc')

      const res = spawnSync(process.execPath, [
        tsc,
        '--noEmit',
        '--strict',
        '--target', 'ES2022',
        '--module', 'nodenext',
        '--moduleResolution', 'nodenext',
        '--esModuleInterop',
        '--resolveJsonModule',
        '--skipLibCheck',
        '--types', 'node',
        tmpFile,
      ], { cwd: tsDir, encoding: 'utf8' })

      const out = ((res.stdout || '') + (res.stderr || '')).trim()
      assert.strictEqual(res.status, 0,
        'Per-language README.md TypeScript snippets failed to type-check:\\n\\n' + out + '\\n')
    } finally {
      Fs.rmSync(tmpFile, { force: true })
    }
  })


  it('every runnable TypeScript snippet in the root README executes in test mode', async () => {
    const readmePath = Path.join(__dirname, '..', '..', 'README.md')
    const md = Fs.readFileSync(readmePath, 'utf8')

    const blocks = extractTsBlocks(md)
    assert(blocks.length > 0, 'No TypeScript code blocks found in root README.md')

    const requireFrom = createRequire(__filename)
    const ts = requireFrom('typescript')

    const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor
    const silentConsole = { log() {}, error() {}, warn() {}, info() {} }

    const failures: string[] = []

    for (let i = 0; i < blocks.length; i++) {
      const src = rewriteForRun(blocks[i])
      // Nothing executable (e.g. an import-only block) — nothing to run.
      if ('' === src.trim()) {
        continue
      }

      // Compile the snippet to JS (strips type annotations) so it runs
      // under node exactly as a real caller would.
      const js = ts.transpileModule(src, {
        compilerOptions: {
          target: ts.ScriptTarget.ES2020,
          module: ts.ModuleKind.ESNext,
        },
      }).outputText

      let runner: any
      try {
        runner = new AsyncFunction(SDK_NAME, 'console', js)
      } catch (err: any) {
        failures.push('snippet ' + i + ' failed to compile as runnable JS: ' +
          String((err && err.message) || err))
        continue
      }

      try {
        await runner(${Name}SDK, silentConsole)
      } catch (err: any) {
        const msg = String((err && err.message) || err)
        // Tolerate the one expected domain error: no fixture seeded for
        // the requested id (a 404 / "Not found" from test mode). A
        // programming error (undefined method/symbol, wrong arg count) is
        // a real README bug and is NOT tolerated.
        if (/\\b(?:404|not found)\\b/i.test(msg)) {
          continue
        }
        failures.push('snippet ' + i + ' threw at runtime: ' + msg)
      }
    }

    assert.strictEqual(failures.length, 0,
      'README TypeScript snippets failed to run in test mode:\\n\\n' +
      failures.join('\\n') + '\\n')
  })
})
`)
  })
})


export {
  ReadmeExamplesTest
}
