
import { cmp, Content, File } from '@voxgig/sdkgen'


// Generates ts/test/readme_examples.test.ts — a test that reads the
// repo's root README.md, extracts every fenced ```ts block, wraps each
// one in an isolated block scope inside a single async function, writes
// the result to a temp module, and runs the repo's local
// `tsc --noEmit` over it. Zero type errors => pass.
//
// Because the snippets are type-checked (not just run), this catches
// API-shape drift that a runtime test cannot — e.g. reading `.data` off
// a `list()` result (which is a bare array, `Advice[]`) is a compile
// error, so a stale `advices.data` snippet fails the build.
//
// Approach chosen: spawn `tsc --noEmit` at test time over the actual
// README snippets (rather than emitting a pre-baked source file). This
// keeps the test honest against whatever the README currently says, so
// editing a snippet to reintroduce `.data` makes THIS test fail.
const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { ctx$: { model } } = props
  const Name = model.const.Name

  File({ name: 'readme_examples.test.ts' }, () => {
    Content(`// Type-checks every TypeScript snippet in the repo's root README.md.
//
// Each fenced \\\`\\\`\\\`ts block is extracted, wrapped in its own block
// scope inside one async function (so re-declared locals like \\\`client\\\`
// across snippets don't collide), written to a temp module, and compiled
// with the repo's local \\\`tsc --noEmit\\\`. A snippet that misuses the SDK
// types (e.g. \\\`.data\\\` on a \\\`list()\\\` array) is a compile error and
// fails this test. Generated by @voxgig/sdkgen — do not edit by hand.

import { describe, it } from 'node:test'
import assert from 'node:assert'
import * as Fs from 'node:fs'
import * as Path from 'node:path'
import { createRequire } from 'node:module'
import { spawnSync } from 'node:child_process'


const SDK_NAME = '${Name}SDK'


// Pull out the body of every \\\`\\\`\\\`ts fenced code block.
function extractTsBlocks(md: string): string[] {
  const blocks: string[] = []
  const re = /\`\`\`ts\\n([\\s\\S]*?)\`\`\`/g
  let m: RegExpExecArray | null
  while ((m = re.exec(md)) !== null) {
    blocks.push(m[1])
  }
  return blocks
}


// Snippet import lines reference the published package name, which is not
// resolvable from inside the repo; the SDK symbol is supplied by the one
// module-level import we emit instead.
function stripImports(code: string): string {
  return code.replace(/^\\s*import\\s+[^\\n]*$/gm, '')
}


function buildModule(blocks: string[]): string {
  const body = blocks.map((b, i) =>
    '  // --- README snippet ' + i + ' ---\\n  {\\n' +
    stripImports(b).replace(/^/gm, '    ') + '\\n  }'
  ).join('\\n\\n')

  return [
    'import { ' + SDK_NAME + " } from '..'",
    '',
    'async function __readme_examples() {',
    '  // Shared client for snippets that reference \\\`client\\\` without',
    '  // constructing one (e.g. the direct() example).',
    '  const client = ' + SDK_NAME + '.test()',
    '  void client',
    body,
    '}',
    'void __readme_examples',
    '',
  ].join('\\n')
}


describe('README examples', () => {
  it('every TypeScript snippet in the root README type-checks', () => {
    const readmePath = Path.join(__dirname, '..', '..', 'README.md')
    const md = Fs.readFileSync(readmePath, 'utf8')

    const blocks = extractTsBlocks(md)
    assert(blocks.length > 0, 'No TypeScript code blocks found in root README.md')

    const tsDir = Path.join(__dirname, '..')
    // Leading dot: TypeScript wildcard includes skip dot-files, so a
    // stray temp file is never swept into the normal build.
    const tmpFile = Path.join(tsDir, 'test', '.readme_examples.gen.ts')
    Fs.writeFileSync(tmpFile, buildModule(blocks), 'utf8')

    try {
      const requireFrom = createRequire(__filename)
      const tsc = requireFrom.resolve('typescript/bin/tsc')

      const res = spawnSync(process.execPath, [
        tsc,
        '--noEmit',
        '--strict',
        '--target', 'ES2022',
        '--module', 'nodenext',
        '--moduleResolution', 'nodenext',
        '--esModuleInterop',
        '--resolveJsonModule',
        '--skipLibCheck',
        '--types', 'node',
        tmpFile,
      ], { cwd: tsDir, encoding: 'utf8' })

      const out = ((res.stdout || '') + (res.stderr || '')).trim()
      assert.strictEqual(res.status, 0,
        'README TypeScript snippets failed to type-check:\\n\\n' + out + '\\n')
    } finally {
      Fs.rmSync(tmpFile, { force: true })
    }
  })
})
`)
  })
})


export {
  ReadmeExamplesTest
}
