/* Copyright (c) 2024-2025 Voxgig, MIT License */



import { SdkGenError } from '../utility'


type PathSegment = {
  lit?: string
  var?: string
}


function pointSegments(point: any): PathSegment[] {
  const segments = point && point.segments

  if (!Array.isArray(segments) && Array.isArray(point && point.parts)) {
    throw new SdkGenError(
      'model: the point for `' + ((point && point.orig) || '(unknown path)') +
      '` still describes its path as `parts` (' +
      JSON.stringify(point.parts) + ') and carries no `segments`. apidef ' +
      'replaced the braced-string form with the typed segment vector in ' +
      '8.2.0 (its ADR-003), so this model was generated by an older apidef ' +
      'and has not been regenerated. Generating from it would build every ' +
      'URL as the API root. Run `npm run generate` in the project\'s `.sdk` ' +
      'so apidef rewrites its entity models, then generate again.')
  }

  return Array.isArray(segments) ? segments : []
}


function pointParts(point: any): string[] {
  return pointSegments(point).map((seg: PathSegment) =>
    null == seg.var ? String(seg.lit ?? '') : '{' + seg.var + '}')
}


function pointTerminalParam(point: any): boolean {
  const parts = pointParts(point)
  const last = 0 < parts.length ? parts[parts.length - 1] : ''
  return 0 === last.indexOf('{')
}


function pointPathKey(point: any): string {
  return pointSegments(point)
    .map((seg: PathSegment) =>
      null == seg.var ? 'l:' + String(seg.lit ?? '') : 'v:' + seg.var)
    .join('/')
}


export type {
  PathSegment,
}

export {
  pointSegments,
  pointParts,
  pointTerminalParam,
  pointPathKey,
}
