
import * as Path from 'node:path'

import {
  cmp, each,
  File, Content, Copy, Folder, Fragment,
  entityClassName,
} from '@voxgig/sdkgen'


import type {
  ModelEntity
} from '@voxgig/apidef'


import {
  KIT,
  getModelPath
} from '@voxgig/apidef'


import { Package } from './Package_rust'
import { Config } from './Config_rust'
import { Gitignore } from './Gitignore_rust'
import { MainEntity } from './MainEntity_rust'
import { EntityBase } from './EntityBase_rust'
import { EntityTypes } from './EntityTypes_rust'
import { SdkError } from './SdkError_rust'
import { crateIdent } from './utility_rust'


const Main = cmp(async function Main(props: any) {

  const { target } = props
  const { model } = props.ctx$

  const entity: ModelEntity = getModelPath(model, `main.${KIT}.entity`)

  // The rust crate identifier (RUSTCRATE placeholder), e.g. solar_sdk —
  // used in every `use <crate>::...` path in the test templates.
  const rustcrate = crateIdent(model)

  Package({ target })

  Gitignore({})

  // Copy tm/rust files with replacements. The tm src/ subtree only stages
  // the per-feature custom-source dirs (target add), so it is excluded
  // here exactly like the go target.
  Copy({
    from: 'tm/' + target.name,
    exclude: [/src\//],
    replace: {
      ...props.ctx$.stdrep,
      RUSTCRATE: rustcrate,
    }
  })

  // Generated core files: the client (sdk.rs), the API config and the
  // branded error type.
  Folder({ name: 'core' }, () => {

    File({ name: 'sdk.' + target.ext }, () => {

      Fragment(
        {
          from: Path.normalize(__dirname + '/../../../src/cmp/rust/fragment/Main.fragment.rs'),
          replace: {
            ...props.ctx$.stdrep,
          }
        },

        // Entity accessors - injected at SLOT
        () => {
          each(entity, (entity: ModelEntity) => {
            const entitySDK = getModelPath(model, `main.${KIT}.entity.${entity.name}`)
            const entprops = { target, entity, entitySDK }
            MainEntity(entprops)
          })
        })
    })

    Config({ target })

    SdkError({ target })
  })

  // entity/mod.rs — the entity module index.
  EntityBase({ target })

  // entity/types.rs — the documentary typed models (one struct per entity +
  // per op). Declared as a module by EntityBase so it compiles with the crate.
  EntityTypes({ target })

  // lib.rs — the crate root: module declarations plus the public API
  // re-exports (twin of the go root package file).
  File({ name: 'lib.' + target.ext }, () => {
    Content(`// ${model.const.Name} SDK for Rust (generated by @voxgig/sdkgen).
//
// The crate mirrors the go SDK layout: core/ (pipeline types), feature/
// (pipeline features), utility/ (pipeline utilities + the vendored voxgig
// struct port), entity/ (per-entity clients). The crate root is this file
// (see Cargo.toml [lib] path).

pub mod core;
pub mod entity;
pub mod feature;
pub mod utility;

// Public API re-exports.
pub use crate::core::config::{make_config, make_feature};
pub use crate::core::context::{Context, CtxSpec, OpMap};
pub use crate::core::control::Control;
pub use crate::core::error::${model.const.Name}Error;
pub use crate::core::helpers::{
    call_json, call_vfn, ja, jo, json_thunk, unsupported_op, vfn,
};
pub use crate::core::operation::Operation;
pub use crate::core::point::Point;
pub use crate::core::response::Response;
pub use crate::core::result::{SdkResult, StreamFn};
pub use crate::core::sdk::{test_sdk, ${model.const.Name}SDK};
pub use crate::core::spec::Spec;
pub use crate::core::types::{
    Entity, Feature, FeatureRef, FetcherFn, OutVal, ${model.const.Name}Entity,
};
pub use crate::core::utility_type::Utility;
pub use crate::feature::base::BaseFeature;
pub use crate::utility::jsonparse::json_parse;
pub use crate::utility::voxgigstruct::Value;

// No-argument convenience constructors: \`${rustcrate}::new()\` /
// \`${rustcrate}::test()\` for the common no-options case.
use std::rc::Rc;

pub fn new() -> Rc<${model.const.Name}SDK> {
    ${model.const.Name}SDK::new(Value::Noval)
}

pub fn test() -> Rc<${model.const.Name}SDK> {
    test_sdk(Value::Noval, Value::Noval)
}
`)
  })

})


export {
  Main
}
