
import {
  Content,
  File,
  cmp,
  collectDeps,
  packageVersion,
  targetFeatures,
} from '@voxgig/sdkgen'


import type {
  Model,
} from '@voxgig/apidef'


import { crateIdent, crateName } from './utility_rust'


const Package = cmp(async function Package(props: any) {
  const ctx$ = props.ctx$
  const target = props.target

  const model: Model = ctx$.model

  File({ name: 'Cargo.toml' }, () => {
    Content(`[package]
name = "${crateName(model)}"
version = "${packageVersion(model, target.name)}"
edition = "2021"
description = "${model.const.Name} SDK for Rust (generated by @voxgig/sdkgen)"
license = "MIT"

[lib]
name = "${crateIdent(model)}"
path = "lib.rs"

`)

    const prod: Record<string, string> = {}
    const dev: Record<string, string> = {}
    for (const d of collectDeps(model, target.name, target.deps, ctx$.log)) {
      // Target-level deps default to '*' when version is absent; feature
      // deps require an explicit version.
      const version = d.source === 'target' ? (d.version || '*') : d.version
      if ('dev' === (d.raw as any)?.kind) {
        dev[d.name] = depValue(version, d.raw)
      }
      else {
        prod[d.name] = depValue(version, d.raw)
      }
    }

    Content(`[dependencies]
`)
    for (const [name, value] of Object.entries(prod)) {
      Content(`${name} = ${value}
`)
    }

    if (0 < Object.keys(dev).length) {
      Content(`
[dev-dependencies]
`)
      for (const [name, value] of Object.entries(dev)) {
        Content(`${name} = ${value}
`)
      }
    }

    const suites = Object.keys(targetFeatures(model, target))
      .filter((name: string) => null != FEATURE_TESTS[name])
      .sort()

    for (const name of suites) {
      Content(`
[[test]]
name = "${name}_feature"
path = "${FEATURE_TESTS[name]}"
`)
    }
  })
})


// Which features ship a rust integration-test suite, and where its crate
// root is. A map rather than a convention because the file has to EXIST:
// cargo fails the whole manifest on a `[[test]]` path it cannot find, so
// this may only name suites the templates actually carry.
const FEATURE_TESTS: Record<string, string> = {
  secrets: 'tests/feature/secrets/main.rs',
}


function depValue(version: string, raw: any): string {
  const features: string[] = Array.isArray(raw?.features) ? raw.features : []
  const nodefault = false === raw?.default

  if (0 === features.length && !nodefault) {
    return `"${version}"`
  }

  const parts = [`version = "${version}"`]
  if (nodefault) {
    parts.push('default-features = false')
  }
  if (0 < features.length) {
    parts.push('features = [' + features.map((f) => `"${f}"`).join(', ') + ']')
  }

  return '{ ' + parts.join(', ') + ' }'
}


export {
  Package
}
