
import {
  Content,
  File,
  cmp,
  collectDeps,
} from '@voxgig/sdkgen'


import type {
  Model,
} from '@voxgig/apidef'


import { crateIdent, crateName } from './utility_rust'


// Cargo.toml (the rust manifest). Dependencies come from the target model
// (`deps` block, kind prod|dev) plus any feature-declared rust deps, via
// the shared collectDeps helper. The vendored voxgig struct port needs no
// external crate. The lib path is the crate root `lib.rs` (the generated
// SDK mirrors the go layout: core/, feature/, utility/, entity/ at the
// repo root rather than under src/).
const Package = cmp(async function Package(props: any) {
  const ctx$ = props.ctx$
  const target = props.target

  const model: Model = ctx$.model

  File({ name: 'Cargo.toml' }, () => {
    Content(`[package]
name = "${crateName(model)}"
version = "0.0.1"
edition = "2021"
description = "${model.const.Name} SDK for Rust (generated by @voxgig/sdkgen)"
license = "MIT"

[lib]
name = "${crateIdent(model)}"
path = "lib.rs"

`)

    const prod: Record<string, string> = {}
    const dev: Record<string, string> = {}
    for (const d of collectDeps(model, target.name, target.deps)) {
      // Target-level deps default to '*' when version is absent; feature
      // deps require an explicit version.
      const version = d.source === 'target' ? (d.version || '*') : d.version
      if ('dev' === (d.raw as any)?.kind) {
        dev[d.name] = version
      }
      else {
        prod[d.name] = version
      }
    }

    Content(`[dependencies]
`)
    for (const [name, version] of Object.entries(prod)) {
      Content(`${name} = "${version}"
`)
    }

    if (0 < Object.keys(dev).length) {
      Content(`
[dev-dependencies]
`)
      for (const [name, version] of Object.entries(dev)) {
        Content(`${name} = "${version}"
`)
      }
    }
  })
})


export {
  Package
}
