
import { cmp, File, Content } from '@voxgig/sdkgen'


// Emits sdktest/ReadmeExamplesTest.scala — a PRESENCE + STRUCTURE gate over
// every scala fenced block in the repository ROOT README.md, the per-language
// scala/README.md, AND the per-language scala/REFERENCE.md. It is a
// default-package scala-cli object exposing run(rep) and is driven by the
// generated SdkEntityTestMain aggregator (mirrors the generated per-entity
// test objects).
//
// SCOPE NOTE (deliberate, documented): the Python/TS/Go equivalents EXECUTE and
// type-check every documented block. That is infeasible here — the generated
// Scala SDK compiles with scala-cli only (no in-process Scala compiler wired
// into the test runtime), so a test cannot compile-and-run arbitrary doc
// snippets at test time. This gate therefore guarantees the weaker-but-real
// invariant that keeps the docs honest as the generator evolves:
//   1. every doc exists and contains at least one scala block (nothing was
//      dropped);
//   2. every scala block is structurally well-formed — its braces, parentheses
//      and brackets balance (catches a truncated or malformed generated
//      snippet).
// A per-doc summary line makes the coverage visible in the test output.
//
// The emitted Scala is written WITHOUT literal backticks (the fence marker is
// built at runtime as 96.toChar.toString.repeat(3)) so this TS template literal
// stays clean.
const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { target, ctx$: { model } } = props

  const Name = model.const.Name

  File({ name: 'ReadmeExamplesTest.' + target.ext }, () => {
    Content(`// ${Name} SDK — documentation scala-examples PRESENCE + STRUCTURE gate.
//
// GUARANTEE (see ReadmeExamplesTest_scala.ts for why this is a structure gate
// and not an execute gate): every scala example in the docs is accounted for.
// A dependency-free scala-cli test object (default package, driven by
// SdkEntityTestMain) over every scala fenced code block in three documents:
//   - the repository ROOT README.md (one directory above the scala module),
//   - the per-language scala/README.md,
//   - the per-language scala/REFERENCE.md.
//
// Checks, PER DOCUMENT:
//   1. PRESENCE: the doc exists and holds at least one scala block.
//   2. STRUCTURE: every scala block's braces / parens / brackets balance, so a
//      truncated or malformed generated snippet fails loudly.
//
// GENERATED by @voxgig/sdkgen — do not edit by hand.

import java.nio.file.{Files, Path, Paths}

object ReadmeExamplesTest {

  // The three documents to scan, resolved relative to the scala module
  // directory (the working directory when scala-cli runs the tests). Each row
  // is {label, relative path}.
  private def docs(): Array[Array[String]] = Array(
    Array("root README", ".." + java.io.File.separator + "README.md"),
    Array("scala README.md", "README.md"),
    Array("scala REFERENCE.md", "REFERENCE.md")
  )

  // Extract every scala fenced block. Split on the triple-backtick fence:
  // odd-indexed segments are the inside of a fenced block (info string on the
  // first line, then the code). Only blocks whose info string is exactly
  // "scala" are returned.
  private def scalaBlocks(text: String): java.util.List[String] = {
    val fence = 96.toChar.toString.repeat(3)
    val parts = text.split(java.util.regex.Pattern.quote(fence), -1)
    val blocks = new java.util.ArrayList[String]()
    var i = 1
    while (i < parts.length) {
      val seg = parts(i)
      val nl = seg.indexOf('\\n')
      val info = (if (nl < 0) seg else seg.substring(0, nl)).trim()
      if (info == "scala") {
        blocks.add(if (nl < 0) "" else seg.substring(nl + 1))
      }
      i += 2
    }
    blocks
  }

  private def readDoc(path: Path): String =
    new String(Files.readAllBytes(path), "UTF-8")

  // True when every open/close delimiter balances (ignores the subtlety of
  // delimiters inside string literals — a generated snippet never nests an
  // unbalanced delimiter in a string, and this catches truncation).
  private def balanced(block: String): Boolean = {
    val stack = new java.util.ArrayDeque[Character]()
    var i = 0
    while (i < block.length) {
      val ch = block.charAt(i)
      ch match {
        case '(' => stack.push(')')
        case '[' => stack.push(']')
        case '{' => stack.push('}')
        case ')' | ']' | '}' =>
          if (stack.isEmpty || stack.pop().charValue() != ch) return false
        case _ =>
      }
      i += 1
    }
    stack.isEmpty
  }

  def run(rep: SdkTestReport): Unit = {
    val ds = docs()

    // PRESENCE: each doc exists and holds at least one scala block.
    var di = 0
    while (di < ds.length) {
      val label = ds(di)(0)
      val rel = ds(di)(1)
      rep.scope("readme-examples.presence." + label) {
        val path = Paths.get(rel)
        rep.check("readme-examples.presence." + label + ".exists",
          Files.exists(path), label + " not found: " + path)
        if (Files.exists(path)) {
          val blocks = scalaBlocks(readDoc(path))
          rep.check("readme-examples.presence." + label, blocks.size() > 0,
            "expected at least one scala block in " + label)
        }
      }
      di += 1
    }

    // STRUCTURE: every scala block's delimiters balance.
    rep.scope("readme-examples.structure") {
      val failures = new java.util.ArrayList[String]()
      var dj = 0
      while (dj < ds.length) {
        val label = ds(dj)(0)
        val path = Paths.get(ds(dj)(1))
        if (Files.exists(path)) {
          val blocks = scalaBlocks(readDoc(path))
          var balancedCount = 0
          var bi = 0
          while (bi < blocks.size()) {
            if (balanced(blocks.get(bi))) balancedCount += 1
            else failures.add(label + " scala block #" + bi + " has unbalanced delimiters")
            bi += 1
          }
          println("[readme-examples] " + label + " scala blocks: total=" +
            blocks.size() + " balanced=" + balancedCount)
        }
        dj += 1
      }
      rep.check("readme-examples.structure", failures.isEmpty(),
        String.join("; ", failures))
    }
  }
}
`)
  })
})


export {
  ReadmeExamplesTest
}
