
import { cmp, Content, File } from '@voxgig/sdkgen'


const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { model } = props.ctx$

  File({ name: 'readme_examples_test.cpp' }, () => {
    Content(`// Structural gate over every \`\`\`cpp block in the ${model.const.Name} SDK docs
// (root README.md, cpp/README.md, cpp/REFERENCE.md). Generated by
// @voxgig/sdkgen — do not edit by hand.
//
// Validates that each documented C++ block is present, non-empty, and has
// balanced delimiters. Missing docs are tolerated. See ReadmeExamplesTest_cpp
// for why this is a structural gate rather than a full compile harness.

#include "testlib.hpp"

#include <fstream>
#include <sstream>
#include <string>
#include <vector>

using namespace sdk;

// Read an entire file into a string, or "" if absent.
static std::string read_file(const std::string& path) {
  std::ifstream f(path, std::ios::binary);
  if (!f) return std::string();
  std::ostringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

// Trim leading/trailing whitespace (fence lines are short).
static std::string trim(const std::string& s) {
  size_t a = s.find_first_not_of(" \\t\\r\\n");
  if (a == std::string::npos) return std::string();
  size_t b = s.find_last_not_of(" \\t\\r\\n");
  return s.substr(a, b - a + 1);
}

// Balanced (), [], {} outside of string literals, with each closer matching
// the most-recent opener (so "([)]" is rejected, not just counted). Naive
// quote toggle: the generated snippets never embed an escaped quote inside a
// string.
static bool is_balanced(const std::string& block) {
  bool in_str = false;
  std::vector<char> stack;
  for (char c : block) {
    if (c == '"') { in_str = !in_str; continue; }
    if (in_str) continue;
    if (c == '(') stack.push_back(')');
    else if (c == '[') stack.push_back(']');
    else if (c == '{') stack.push_back('}');
    else if (c == ')' || c == ']' || c == '}') {
      if (stack.empty() || stack.back() != c) return false;
      stack.pop_back();
    }
  }
  return stack.empty() && !in_str;
}

// Scan one doc: for every \`\`\`cpp ... \`\`\` block, check non-empty + balanced.
// Returns the number of blocks seen (0 if the file is absent).
static int check_doc(const std::string& label, const std::string& path) {
  std::string src = read_file(path);
  if (src.empty()) return 0; // doc not generated in this run — tolerate

  int blocks = 0;
  bool in_block = false;
  std::string block;
  std::istringstream in(src);
  std::string line;
  while (std::getline(in, line)) {
    std::string t = trim(line);
    if (!in_block) {
      if (t == "\`\`\`cpp") { in_block = true; block.clear(); }
    } else if (t == "\`\`\`") {
      std::string body = trim(block);
      ASSERT_TRUE(!body.empty(), label + ": cpp block " + std::to_string(blocks + 1) + " non-empty");
      ASSERT_TRUE(is_balanced(body), label + ": cpp block " + std::to_string(blocks + 1) + " balanced");
      blocks++;
      in_block = false;
    } else {
      block += line;
      block += '\\n';
    }
  }
  // A fence opened but never closed is a malformed doc — fail rather than
  // silently skipping the unterminated block.
  ASSERT_TRUE(!in_block, label + ": cpp fence closed");
  return blocks;
}

static void readme_examples_gate() {
  int total = 0;
  total += check_doc("root README", "../README.md");
  total += check_doc("cpp/README", "README.md");
  total += check_doc("cpp/REFERENCE", "REFERENCE.md");
  // Missing docs are tolerated (a run may generate a subset of phases), so a
  // zero total is not a failure — the per-block checks above carry the gate.
  std::printf("readme_examples: scanned %d cpp block(s)\\n", total);
}

int main() {
  T_RUN(readme_examples_gate);
  return sdktest::summary("readme_examples_test");
}
`)
  })
})


export {
  ReadmeExamplesTest
}
