
import {
  Content,
  File,
  cmp,
  collectDeps,
} from '@voxgig/sdkgen'


import type {
  Model,
} from '@voxgig/apidef'


import { mavenGroupId } from './utility_java'


// Generates the Maven pom.xml (the java analog of go.mod, which the go
// target also generates in its Package cmp). Runtime dependencies come
// from collectDeps (the java target ships none by default — struct is
// vendored and JSON/HTTP are JDK built-ins); JUnit is the only test-scope
// dependency, mirroring the voxgig struct java port's testing approach.
const Package = cmp(async function Package(props: any) {
  const ctx$ = props.ctx$
  const target = props.target

  const model: Model = ctx$.model

  const groupId = mavenGroupId(model)
  const artifactId = `${model.name}-sdk`

  // Dep name convention: "groupId:artifactId" with an explicit version.
  const deps: { groupId: string, artifactId: string, version: string, kind: string }[] = []
  for (const d of collectDeps(model, target.name, target.deps)) {
    const [dgroup, dartifact] = String(d.name).split(':')
    if (dgroup && dartifact && d.version) {
      deps.push({
        groupId: dgroup,
        artifactId: dartifact,
        version: d.version,
        kind: d.raw?.kind || 'prod',
      })
    }
  }

  File({ name: 'pom.xml' }, () => {
    Content(`<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>${groupId}</groupId>
  <artifactId>${artifactId}</artifactId>
  <version>0.0.1</version>
  <name>${model.const.Name} SDK</name>
  <description>${model.const.Name} client SDK for Java (generated by @voxgig/sdkgen).</description>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <junit.jupiter.version>6.1.0</junit.jupiter.version>
  </properties>

  <dependencies>
`)

    for (const d of deps) {
      const scope = 'dev' === d.kind || 'test' === d.kind
        ? '\n      <scope>test</scope>' : ''
      Content(`    <dependency>
      <groupId>${d.groupId}</groupId>
      <artifactId>${d.artifactId}</artifactId>
      <version>${d.version}</version>${scope}
    </dependency>
`)
    }

    Content(`    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>\${junit.jupiter.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <!-- The runtime source keeps the same flat layout as the other
         statically-typed targets (core/, utility/, feature/, entity/),
         with tests in test/. javac does not require package-shaped
         directories for explicitly-listed sources. -->
    <sourceDirectory>\${project.basedir}</sourceDirectory>
    <testSourceDirectory>\${project.basedir}/test</testSourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.0</version>
        <configuration>
          <includes>
            <include>core/**/*.java</include>
            <include>utility/**/*.java</include>
            <include>feature/**/*.java</include>
            <include>entity/**/*.java</include>
          </includes>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.5.2</version>
        <configuration>
          <useModulePath>false</useModulePath>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
`)
  })
})


export {
  Package
}
