
import { cmp, File, Content } from '@voxgig/sdkgen'

import { javaPackage } from './utility_java'


// Emits test/ReadmeExamplesTest.java — a JUnit PRESENCE + STRUCTURE gate over
// every ```java fenced block in the repository ROOT README.md, the
// per-language java/README.md, AND the per-language java/REFERENCE.md.
//
// SCOPE NOTE (deliberate, documented): the Python/TS/Go equivalents EXECUTE and
// type-check every documented block. That is infeasible here — the generated
// Java SDK compiles with plain `javac`/Maven only (no in-process Java compiler
// dependency wired into the test classpath), so a test cannot compile-and-run
// arbitrary doc snippets at test time. This gate therefore guarantees the
// weaker-but-real invariant that keeps the docs honest as the generator evolves:
//   1. every doc exists and contains at least one ```java block (nothing was
//      dropped);
//   2. every ```java block is structurally well-formed — its braces,
//      parentheses and brackets balance (catches a truncated or malformed
//      generated snippet).
// A per-doc summary line makes the coverage visible in the test output.
//
// The emitted Java is written WITHOUT literal backticks (the fence marker is
// built at runtime as String.valueOf((char) 96).repeat(3)) so this TS template
// literal stays clean.
const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { target, ctx$: { model } } = props

  const Name = model.const.Name
  const javapackage = props.javapackage || javaPackage(model)

  File({ name: 'ReadmeExamplesTest.' + target.ext }, () => {
    Content(`package ${javapackage}.sdktest;

// ${Name} SDK — documentation java-examples PRESENCE + STRUCTURE gate.
//
// GUARANTEE (see ReadmeExamplesTest_java.ts for why this is a structure gate
// and not an execute gate): every java example in the docs is accounted for.
// This JUnit class is a completeness gate over every ${'```'}java fenced code
// block in three documents:
//   - the repository ROOT README.md (one directory above this module),
//   - the per-language java/README.md,
//   - the per-language java/REFERENCE.md.
//
// Checks, PER DOCUMENT:
//   1. PRESENCE: the doc exists and holds at least one java block.
//   2. STRUCTURE: every java block's braces / parens / brackets balance, so a
//      truncated or malformed generated snippet fails loudly.
//
// GENERATED by @voxgig/sdkgen — do not edit by hand.

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;

public class ReadmeExamplesTest {

  // The three documents to scan, resolved relative to the Maven module
  // directory (the working directory when surefire runs the tests). Each row
  // is {label, relative path}.
  private static String[][] docs() {
    return new String[][] {
      { "root README", ".." + java.io.File.separator + "README.md" },
      { "java README.md", "README.md" },
      { "java REFERENCE.md", "REFERENCE.md" },
    };
  }

  // Extract every java fenced block. Split on the triple-backtick fence:
  // odd-indexed segments are the inside of a fenced block (info string on the
  // first line, then the code). Only blocks whose info string is exactly
  // "java" are returned.
  private static List<String> javaBlocks(String text) {
    String fence = String.valueOf((char) 96).repeat(3);
    String[] parts = text.split(java.util.regex.Pattern.quote(fence), -1);
    List<String> blocks = new ArrayList<>();
    for (int i = 1; i < parts.length; i += 2) {
      String seg = parts[i];
      int nl = seg.indexOf('\\n');
      String info = (nl < 0 ? seg : seg.substring(0, nl)).trim();
      if (info.equals("java")) {
        blocks.add(nl < 0 ? "" : seg.substring(nl + 1));
      }
    }
    return blocks;
  }

  private static String readDoc(Path path, String label) {
    assertTrue(Files.exists(path), label + " not found: " + path);
    try {
      return Files.readString(path);
    }
    catch (IOException e) {
      throw new RuntimeException("failed to read " + label + ": " + path, e);
    }
  }

  // True when every open/close delimiter balances (ignores the subtlety of
  // delimiters inside string literals — a generated snippet never nests an
  // unbalanced delimiter in a string, and this catches truncation).
  private static boolean balanced(String block) {
    Deque<Character> stack = new ArrayDeque<>();
    Map<Character, Character> pairs =
        Map.of('(', ')', '[', ']', '{', '}');
    for (int i = 0; i < block.length(); i++) {
      char ch = block.charAt(i);
      if (pairs.containsKey(ch)) {
        stack.push(pairs.get(ch));
      }
      else if (ch == ')' || ch == ']' || ch == '}') {
        if (stack.isEmpty() || stack.pop() != ch) {
          return false;
        }
      }
    }
    return stack.isEmpty();
  }

  @Test
  public void rootReadmeHasJavaBlocks() {
    String[] doc = docs()[0];
    List<String> blocks = javaBlocks(readDoc(Path.of(doc[1]), doc[0]));
    assertTrue(blocks.size() > 0,
        "expected at least one java block in " + doc[0]);
  }

  @Test
  public void localReadmeHasJavaBlocks() {
    String[] doc = docs()[1];
    List<String> blocks = javaBlocks(readDoc(Path.of(doc[1]), doc[0]));
    assertTrue(blocks.size() > 0,
        "expected at least one java block in " + doc[0]);
  }

  @Test
  public void referenceHasJavaBlocks() {
    String[] doc = docs()[2];
    List<String> blocks = javaBlocks(readDoc(Path.of(doc[1]), doc[0]));
    assertTrue(blocks.size() > 0,
        "expected at least one java block in " + doc[0]);
  }

  @Test
  public void allJavaBlocksAreStructurallyBalanced() {
    List<String> failures = new ArrayList<>();
    for (String[] doc : docs()) {
      Path path = Path.of(doc[1]);
      if (!Files.exists(path)) {
        continue;
      }
      List<String> blocks = javaBlocks(readDoc(path, doc[0]));
      int balancedCount = 0;
      for (int i = 0; i < blocks.size(); i++) {
        if (balanced(blocks.get(i))) {
          balancedCount++;
        }
        else {
          failures.add(doc[0] + " java block #" + i +
              " has unbalanced delimiters:\\n\\n" + blocks.get(i));
        }
      }
      System.out.println(
          "[readme-examples] " + doc[0] + " java blocks: total=" +
          blocks.size() + " balanced=" + balancedCount);
    }
    assertTrue(failures.isEmpty(), String.join("\\n\\n", failures));
  }
}
`)
  })
})


export {
  ReadmeExamplesTest
}
