
import * as Path from 'node:path'

import {
  cmp, each,
  File, Content, Fragment, Slot,
} from '@voxgig/sdkgen'

import type {
  ModelEntity,
} from '@voxgig/apidef'

import {
  KIT,
  getModelPath,
} from '@voxgig/apidef'


// Published aql/eng/go version. Tagged at aql-lang/aql under
// eng/go/v<X.Y.Z>. Bump here when adopting a newer engine.
const AQL_ENG_VERSION = 'v0.0.1'

// go.sum entries for AQL_ENG_VERSION and its transitive deps. The sibling
// SDK dep needs no entry (path replace). Deterministic because the version
// is pinned above — regenerate with `go mod tidy` and update BOTH constants
// together when bumping AQL_ENG_VERSION.
const AQL_ENG_GOSUM = `github.com/aql-lang/aql/eng/go v0.0.1 h1:qvopmpIX5xL6cpAC4otSUO7fUDA46x/y+2lT2zoxTaA=
github.com/aql-lang/aql/eng/go v0.0.1/go.mod h1:7LmNG+pASY2jlPZB0iFAt/ZNdmc8qxvaf+njVmaSFks=
github.com/jsonicjs/jsonic/go v0.1.6 h1:oUw4vxCK6tqa7SGN87vjCtx3sCpeHXdqfl25hx5LKP0=
github.com/jsonicjs/jsonic/go v0.1.6/go.mod h1:ObNKlCG7esWoi4AHCpdgkILvPINV8bpvkbCd4llGGUg=
`


const Main = cmp(function Main(props: any) {
  const { target } = props
  const { model } = props.ctx$

  const org = model.origin || 'voxgig-sdk'
  const sdkModule = `github.com/${org}/${model.name}-sdk/go`
  const cliModule = `github.com/${org}/${model.name}-sdk/go-cli`

  const entityMap: any = getModelPath(model, `main.${KIT}.entity`)
  const entityNames = Object.keys(entityMap).map(n => n.toLowerCase())

  const FRAGMENT = Path.normalize(__dirname + '/../../../src/cmp/go-cli/fragment')

  // .gitignore — the compiled binary lands at /<modulename>-cli; ignore it.
  File({ name: '.gitignore' }, () => Content(`/${model.name}-cli
`))

  // README.md — usage guide for the AQL-driven CLI.
  const entityList = entityNames.length > 0 ? entityNames.join(' ') : '(none)'

  // MODEL-DRIVEN verbs. The CLI implements three AQL words (list / load /
  // update; see words.fragment.go + runOp). Each README verb row is
  // advertised ONLY when at least one active entity actually exposes that
  // op (op.<name>.active !== false) — never document an operation no entity
  // supports.
  const CLI_VERB_ROWS: Record<string, string> = {
    list:   '| `list`   | `[entity]` · `[query entity]`                | List records               |',
    load:   '| `load`   | `[entity]` · `[query entity]`                | Load a single record       |',
    update: '| `update` | `[entity]` · `[query entity]`                | Update a record            |',
  }
  const supportedOps = new Set<string>()
  each(entityMap, (entity: any) => {
    if (entity && entity.active === false) return
    const ops = (entity && entity.op) || {}
    for (const opname of Object.keys(ops)) {
      if (ops[opname] && ops[opname].active !== false) supportedOps.add(opname)
    }
  })
  const verbRows = ['list', 'load', 'update']
    .filter(op => supportedOps.has(op))
    .map(op => CLI_VERB_ROWS[op])
    .join('\n')

  // MODEL-DRIVEN run examples, gated on the first entity's own ops so the
  // Run section never demonstrates a verb the example entity lacks.
  const firstEntityObj: any =
    Object.values(entityMap).find((e: any) => e && e.active !== false)
  const firstEntity = firstEntityObj
    ? String(firstEntityObj.name).toLowerCase()
    : (entityNames[0] || 'entity')
  const firstOps: any = (firstEntityObj && firstEntityObj.op) || {}
  const firstHas = (op: string) => !!(firstOps[op] && firstOps[op].active !== false)
  const runLines: string[] = ['# One-shot: arguments form a single AQL expression']
  if (firstHas('list')) {
    runLines.push(`./${model.name}-cli list ${firstEntity}`)
  }
  if (firstHas('load')) {
    runLines.push(`./${model.name}-cli load 1 ${firstEntity}`)
    runLines.push(`./${model.name}-cli load '{id:1}' ${firstEntity}`)
  }
  if (firstHas('update')) {
    runLines.push(`./${model.name}-cli update '{id:1}' ${firstEntity}`)
  }

  File({ name: 'README.md' }, () => Content(`# ${model.name}-cli

AQL-driven CLI and REPL for the ${model.Name} SDK. Positional arguments are
joined into a single AQL expression and evaluated; with no arguments,
falls into an interactive REPL.

Built on \`github.com/aql-lang/aql/eng/go\` and the sibling Go SDK at \`../go\`.

## Build

\`\`\`sh
go build -o ${model.name}-cli ./...
\`\`\`

## Run

\`\`\`sh
${runLines.join('\n')}

# REPL
./${model.name}-cli
\`\`\`

## Words

| Word     | Signatures                                   | Description                |
|----------|----------------------------------------------|----------------------------|
${verbRows}

\`query\` is either a Map (\`{id:1}\`) or a Scalar (\`1\`, treated as \`{id:1}\`).
\`entity\` is one of the SDK's entity names (auto-quoted as an atom).

## Entities

${entityList}

## REPL commands

- \`:quit\` / \`:q\` / \`:exit\` — exit the REPL
- \`:help\` / \`:h\` / \`:?\`     — show help

## Generated by

sdkgen \`go-cli\` target. See the target source under
\`.sdk/src/cmp/go-cli/\` in this repo, or upstream at
\`github.com/voxgig/sdkgen/project/.sdk/src/cmp/go-cli/\`.
`))

  // go.mod — sibling SDK via relative replace; aql/eng/go from the
  // public Go module proxy. The go directive must be >= aql/eng/go's own
  // (go 1.24.7 at eng/go/v0.0.1) — keep in step with AQL_ENG_VERSION.
  File({ name: 'go.mod' }, () => Content(`module ${cliModule}

go 1.24.7

require ${sdkModule} v0.0.0
require github.com/aql-lang/aql/eng/go ${AQL_ENG_VERSION}

require github.com/jsonicjs/jsonic/go v0.1.6 // indirect

replace ${sdkModule} => ../go
`))

  // go.sum — required for `go build` to accept the aql/eng/go dependency
  // (the path-replaced sibling SDK needs no entry). Pinned alongside
  // AQL_ENG_VERSION above.
  File({ name: 'go.sum' }, () => Content(AQL_ENG_GOSUM))

  // main.go — produced from fragment/main.fragment.go with two Slots
  // for the prompt label and the entity help line.
  File({ name: 'main.go' }, () => {
    Fragment(
      {
        from: Path.join(FRAGMENT, 'main.fragment.go'),
        replace: {
          ...props.ctx$.stdrep,
          GOMODULE: sdkModule,
        },
      },
      () => {
        Slot({ name: 'promptName' }, () => Content(model.name))
        Slot({ name: 'entityNamesSpaced' }, () => Content(entityNames.join(' ')))
      },
    )
  })

  // words.go — produced from fragment/words.fragment.go with a single
  // Slot that emits one `case "<name>":` per entity.
  File({ name: 'words.go' }, () => {
    Fragment(
      {
        from: Path.join(FRAGMENT, 'words.fragment.go'),
        replace: {
          ...props.ctx$.stdrep,
          GOMODULE: sdkModule,
        },
      },
      () => {
        Slot({ name: 'entityCases' }, () => {
          each(entityMap, (entity: ModelEntity) => {
            const lower = entity.name.toLowerCase()
            const pascal = (entity as any).Name
            Content(`\tcase "${lower}":
\t\treturn client.${pascal}(nil), nil
`)
          })
        })
      },
    )
  })
})


export {
  Main
}
