import { cmp, Content, File } from '@voxgig/sdkgen'

import {
  KIT,
  getModelPath,
} from '@voxgig/apidef'


// Emits lua/test/readme_examples_test.lua — a busted spec that is a
// COMPLETENESS GATE over every ```lua block in ALL THREE docs that ship
// lua examples:
//   - the root README.md (top-level, multi-language quick start)
//   - the per-language lua/README.md
//   - the per-language lua/REFERENCE.md
//
// For every ```lua block, tagged by (source doc, index):
//   1. Syntax: it must compile with Lua's load() — catches malformed
//      example code (missing end, bad token, ...).
//   2. Offline run: every RUNNABLE block (one that builds a client via
//      sdk.new/sdk.test or references `client`) is EXECUTED with the mock
//      transport (no network). Each client constructor is rewritten to the
//      seeded test-mode form, and fragments that only use `client` get a
//      seeded test client injected. A call to a method that does not exist
//      — e.g. a lowercase entity accessor after the API capitalised it to
//      client:Entity() — raises "call a nil value" and FAILS the test.
//      Entity operations return a (value, err) tuple, so a seeded-fixture
//      miss surfaces as a tolerated (nil, err) not-found domain error.
//   3. Completeness: every block is partitioned into {executed, illustration}
//      and total == executed + illustration is asserted per doc. A block that
//      is neither runnable nor a NARROW explicit illustration (a comment-only
//      / --[[ ]] placeholder) is a silently-untested example and FAILS the
//      gate — "illustration" is never a catch-all.
const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { ctx$: { model } } = props

  // Every active entity, keyed by its model name, is seeded with a `test01`
  // fixture whose id is `test01` — so a load({ id = "test01" }) in a doc
  // resolves offline. Bracket-string keys keep the literal valid for any
  // entity name.
  const entity = getModelPath(model, `main.${KIT}.entity`) || {}
  const entnames = Object.values(entity)
    .filter((e: any) => e && e.active !== false)
    .map((e: any) => e.name)

  const seedEntries = entnames
    .map((n: string) => `["${n}"] = { ["test01"] = { id = "test01" } }`)
    .join(', ')
  const seedLiteral = `{ entity = { ${seedEntries} } }`

  File({ name: 'readme_examples_test.lua' }, () => {
    Content(`-- README lua example snippets check. Generated by @voxgig/sdkgen.
--
-- COMPLETENESS GATE over every \`\`\`lua block in all three docs that ship
-- lua examples: the root README.md, the lua/README.md, and the
-- lua/REFERENCE.md. For every block:
--   1. Syntax: each block must compile with Lua's load().
--   2. Offline run: every runnable block (one that builds a client or
--      references \`client\`) is EXECUTED with the mock transport (no
--      network). Each client constructor is rewritten to the seeded
--      test-mode form, and fragments that only use \`client\` get a seeded
--      test client injected. A call to a method that does not exist raises
--      "call a nil value" and FAILS the test. A seeded-fixture miss surfaces
--      as a tolerated (nil, err) not-found domain error, not a raised error.
--   3. Completeness: total == executed + illustration per doc. A block that
--      is neither runnable nor an explicit comment-only placeholder FAILS
--      the gate, so no runnable example can be silently skipped.

local SDK_MODULE = "${model.name}_sdk"

-- A test-mode client seeded with a fixture for every entity. The constructor
-- of each runnable snippet is rewritten to this form so the offline mock has
-- data to return.
local TEST_SEED = '${seedLiteral}'
local TEST_CTOR = "sdk.test(" .. TEST_SEED .. ")"

local function script_dir()
  local src = debug.getinfo(1, "S").source
  local path = src:sub(1, 1) == "@" and src:sub(2) or src
  return path:match("^(.*)[/\\\\][^/\\\\]*$") or "."
end

-- Read a doc by its path relative to this test file's directory (which is
-- <repo>/lua/test). The root README is two levels up; the lua docs are one.
local function read_doc(relpath)
  local dir = script_dir()
  local candidates = {
    dir .. "/" .. relpath,
    relpath,
  }
  for _, p in ipairs(candidates) do
    local f = io.open(p, "r")
    if f then
      local data = f:read("*a")
      f:close()
      return data, p
    end
  end
  return nil
end

local function trim(s)
  return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

local function extract_blocks(md, lang)
  local blocks = {}
  local open = "\`\`\`" .. lang
  local in_block = false
  local cur = {}
  for line in (md .. "\\n"):gmatch("([^\\n]*)\\n") do
    local t = trim(line)
    if not in_block then
      if t == open then
        in_block = true
        cur = {}
      end
    else
      if t == "\`\`\`" then
        table.insert(blocks, table.concat(cur, "\\n"))
        in_block = false
      else
        table.insert(cur, line)
      end
    end
  end
  return blocks
end

-- A block is runnable if it builds a client (sdk.new / sdk.test) or uses one
-- (references \`client\`). These are the blocks we EXECUTE offline.
local function is_runnable(block)
  return block:find("sdk%s*%.%s*new") ~= nil
    or block:find("sdk%s*%.%s*test") ~= nil
    or block:find("client") ~= nil
end

-- NARROW illustration class:
--   - a comment-only block (nothing remains after stripping lua comments), or
--   - a --[[ ]] value-slot placeholder template (e.g. field = --[[ type ]]):
--     the placeholder stands in for a value, so the block does not parse.
-- Everything else must be runnable and is executed; a non-runnable,
-- non-illustration block is a silently-untested example and fails the
-- completeness gate.
local function is_illustration(block)
  local stripped = block:gsub("%-%-%[%[.-%]%]", "")  -- block comments
  stripped = stripped:gsub("%-%-[^\\n]*", "")          -- line comments
  if trim(stripped) == "" then
    return true
  end
  if block:find("%-%-%[%[") and load(block) == nil then
    return true
  end
  return false
end

-- Transform a README block into an executable offline snippet: rewrite any
-- client constructor to the seeded test-mode form, inject a seeded client for
-- bare fragments, and ensure \`sdk\` is in scope.
local function make_runnable(block)
  local src = block

  local constructs = block:find("sdk%s*%.%s*new") ~= nil
    or block:find("sdk%s*%.%s*test") ~= nil

  if constructs then
    -- %b() matches a balanced ( ... ) argument list, so nested tables/parens
    -- in the original constructor call are replaced wholesale.
    src = src:gsub("sdk%s*%.%s*new%s*%b()", function() return TEST_CTOR end)
    src = src:gsub("sdk%s*%.%s*test%s*%b()", function() return TEST_CTOR end)
  end

  local prelude = {}
  if not src:find("require%s*%(") then
    table.insert(prelude, 'local sdk = require("' .. SDK_MODULE .. '")')
  end
  if not constructs and src:find("client") then
    table.insert(prelude, "local client = " .. TEST_CTOR)
  end

  if #prelude > 0 then
    src = table.concat(prelude, "\\n") .. "\\n" .. src
  end
  return src
end

-- All three docs are checked identically. relpath is resolved against this
-- test file's directory (<repo>/lua/test).
local DOCS = {
  { label = "root README",   relpath = "../../README.md" },
  { label = "lua/README",    relpath = "../README.md" },
  { label = "lua/REFERENCE", relpath = "../REFERENCE.md" },
}

for _, doc in ipairs(DOCS) do
  describe("lua doc examples (" .. doc.label .. ")", function()
    local md = read_doc(doc.relpath)

    it(doc.label .. " is present", function()
      assert.is_not_nil(md, "could not read " .. doc.label ..
        " (" .. doc.relpath .. ")")
    end)

    if not md then
      return
    end

    local blocks = extract_blocks(md, "lua")

    it(doc.label .. " has lua example blocks", function()
      assert.is_true(#blocks > 0, "no lua code blocks found in " .. doc.label)
    end)

    it(doc.label .. ": every lua block is syntactically valid", function()
      for i, block in ipairs(blocks) do
        -- Illustration placeholders (--[[ type ]] templates) intentionally do
        -- not parse; every other block must.
        if not is_illustration(block) then
          local chunk, err = load(block, "=" .. doc.label .. "-lua-" .. i)
          assert.is_not_nil(chunk,
            doc.label .. " lua block #" .. i .. " has a syntax error: " ..
            tostring(err) .. "\\n----\\n" .. block .. "\\n----")
        end
      end
    end)

    it(doc.label .. ": every runnable lua block runs offline in test mode",
      function()
      local ran = 0
      for i, block in ipairs(blocks) do
        if is_runnable(block) and not is_illustration(block) then
          local src = make_runnable(block)
          local chunk, err = load(src, "=" .. doc.label .. "-run-" .. i)
          assert.is_not_nil(chunk,
            doc.label .. " runnable block #" .. i .. " failed to compile: " ..
            tostring(err) .. "\\n----\\n" .. src .. "\\n----")
          local ok, e = pcall(chunk)
          if not ok then
            local msg = tostring(e)
            -- A nil accessor / missing method / bad index is a real doc bug:
            -- the documented call does not exist.
            if msg:find("nil value") or msg:find("attempt to call")
              or msg:find("attempt to index") then
              assert.is_true(false,
                doc.label .. " runnable block #" .. i .. " hit a runtime " ..
                "error (missing method / nil call): " .. msg ..
                "\\n----\\n" .. src .. "\\n----")
            end
            -- Other runtime errors (a seeded-fixture miss surfaces as a
            -- tolerated not-found domain error, e.g. "request: 404") are
            -- expected offline and tolerated.
          end
          ran = ran + 1
        end
      end
      assert.is_true(ran > 0,
        "expected at least one runnable lua block in " .. doc.label)
    end)

    it(doc.label .. ": every lua block is executed or an explicit " ..
      "illustration (completeness)", function()
      local executed, illustration = 0, 0
      local unclassified = {}
      for i, block in ipairs(blocks) do
        if is_illustration(block) then
          illustration = illustration + 1
        elseif is_runnable(block) then
          executed = executed + 1
        else
          table.insert(unclassified, i)
        end
      end
      assert.is_true(#unclassified == 0,
        doc.label .. " has lua block(s) that are neither runnable nor a " ..
        "recognized illustration and would be silently untested: #" ..
        table.concat(unclassified, ", #"))
      assert.are.equal(#blocks, executed + illustration,
        doc.label .. " completeness: total " .. #blocks ..
        " != executed " .. executed .. " + illustration " .. illustration)
      print(string.format(
        "[readme-lua] %s: total=%d executed=%d illustration=%d",
        doc.label, #blocks, executed, illustration))
    end)
  end)
end
`)
  })

})


export {
  ReadmeExamplesTest
}
