import {
  cmp, each,
  File, Content, Folder,
} from '@voxgig/sdkgen'


// The rest of the seneca-provider package: its test suite, CI workflow and
// README. Split out of Main only for size — everything here is driven by the
// same `provider` shape Main builds from the model.
//
// The tests are the reason this target is worth generating at all. A provider
// is thin, and the thin part is exactly where the mistakes are: a cmd that
// forgets a parent path param, an entity that comes back under the wrong
// canon, a 404 that should have been `null` and instead threw. All three are
// checked below, offline, against the SDK's own mock transport — so a
// generated provider is verified without a server.


// A plausible seed record for an entity: its required fields, given values
// that read as data rather than as `string`.
function seedRecord(e: any, idx: number): Record<string, any> {
  const out: Record<string, any> = {}

  for (const f of e.fields) {
    if ('id' === f.name || f.name === e.idf) {
      out[f.name] = `${e.name}${idx}`
    }
    else if (e.parents.includes(f.name)) {
      // A nested entity's parent id must match a record the parent seeds, or
      // the offline store answers nothing and every nested test reads as a
      // false pass.
      out[f.name] = `${f.parentEntity}0`
    }
    else if ('number' === f.kind) {
      out[f.name] = 100 * (idx + 1)
    }
    else if ('boolean' === f.kind) {
      out[f.name] = false
    }
    else {
      out[f.name] = `${f.name}${idx}`
    }
  }

  return out
}


const Tests = cmp(function Tests(props: any) {
  const { provider } = props

  // The entity the suite exercises hardest: prefer one with no parent keys
  // (nothing to arrange) and the most cmds.
  const subject = [...provider.entities]
    .sort((a: any, b: any) =>
      (a.parents.length - b.parents.length) || (b.cmds.length - a.cmds.length))[0]

  const nested = provider.entities.filter((e: any) => 0 < e.parents.length)

  Folder({ name: 'test' }, () => {

    // The seed the offline mock transport is loaded with. Generated from the
    // model so it matches the shape the SDK will actually return.
    File({ name: 'seed.js' }, () => {
      Content(`/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

// Seed data for the SDK's offline mock transport, so the entity tests
// exercise real code paths without a server.
const SEED = {
  entity: {
`)
      each(provider.entities, (e: any) => {
        Content(`    ${e.name}: {
`)
        each([0, 1], (i: any) => {
          const idx = Number(i.val$ ?? i)
          const rec = seedRecord(e, idx)
          Content(`      ${e.name}${idx}: ${JSON.stringify(rec)},
`)
        })
        Content(`    },
`)
      })
      Content(`  },
}

module.exports = { SEED }
`)
    })


    // The message-level spec seneca-msg-test drives. TypeScript, compiled to
    // dist-test by test/tsconfig.json — which is also why it must exist: the
    // shipped tsconfig has `include: ["**/*.ts"]` and tsc fails outright on a
    // config that matches no input.
    File({ name: 'basic.messages.ts' }, () => {
      Content(`/* Generated by @voxgig/sdkgen. Do not edit. */

const Pkg = require('../package.json')

const messages = {
  print: false,
  pattern: 'sys:provider,provider:${provider.lower}',
  allow: { missing: true },

  calls: [
    {
      pattern: 'get:info',
      out: {
        ok: true,
        name: '${provider.lower}',
        version: Pkg.version,
      },
    },
  ],
}

export default messages

if ('undefined' !== typeof module) {
  module.exports = messages
}
`)
    })


    File({ name: `${provider.fileBase}.test.js` }, () => {
      Content(`/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

const { describe, it } = require('node:test')
const assert = require('node:assert')

const Seneca = require('seneca')

const ${provider.pluginName} = require('../dist/${provider.fileBase}')
const ${provider.pluginName}Doc = require('../dist/${provider.pluginName}-doc')

const SenecaMsgTest = require('seneca-msg-test')

const { SEED } = require('./seed')

const BasicMessages = require('../dist-test/basic.messages')


describe('${provider.fileBase}', () => {

  it('happy', async () => {
    assert.notEqual(${provider.pluginName}, undefined)
    assert.notEqual(${provider.pluginName}Doc, undefined)

    const seneca = await makeSeneca()

    assert.partialDeepStrictEqual(
      await seneca.post('sys:provider,provider:${provider.lower},get:info'),
      {
        ok: true,
        name: '${provider.lower}',
      },
    )
  })


  it('messages', async () => {
    const seneca = await makeSeneca()
    await SenecaMsgTest(seneca, BasicMessages)()
  })


  it('sdk-export', async () => {
    const seneca = await makeSeneca()
    const sdk = seneca.export('${provider.pluginName}/sdk')()

`)
      each(provider.entities, (e: any) => {
        Content(`    assert.equal(typeof sdk.${e.acc}, 'function')
`)
      })
      Content(`  })

`)

      if (subject.cmds.includes('list')) {
        Content(`
  it('${subject.name}-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/${provider.lower}/${subject.name}').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/${provider.lower}/${subject.name}',
    )
  })

`)
      }

      if (subject.cmds.includes('load')) {
        Content(`
  it('${subject.name}-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/${provider.lower}/${subject.name}')
      .load$('${subject.name}0')

    assert.equal(found.${subject.idf || 'id'}, '${subject.name}0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/${provider.lower}/${subject.name}',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('${subject.name}-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/${provider.lower}/${subject.name}')
      .load$('nosuch${subject.name}')

    assert.equal(missing, null)
  })

`)
      }

      // A nested entity cannot build its path without the parent id. That is
      // the mistake this target exists to make impossible, so pin it.
      each(nested, (e: any) => {
        const key = e.parents[0]
        Content(`
  it('${e.name}-needs-${key}', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/${provider.lower}/${e.name}').list$({}),
      /${key} is required/,
    )
  })

`)
        if (e.cmds.includes('list')) {
          Content(`
  it('${e.name}-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca
      .entity('provider/${provider.lower}/${e.name}')
      .list$({ ${key}: '${e.parentEntity || ''}0' })

    assert.ok(Array.isArray(list))
  })

`)
        }
      })

      Content(`})


// Default to the SDK's offline mock transport, seeded from ./seed.
async function makeSeneca(pluginopts) {
  pluginopts = pluginopts || { test: true, testopts: SEED }

  const seneca = Seneca({ legacy: false })
    .test()
    .use('promisify')
    .use('entity')
    .use('env', {
      // Declared so the provider convention is exercised, and defaulted so
      // the suite runs with nothing configured.
      var: {
        $${provider.ENV}_APIKEY: '',
      },
    })
    .use('provider', {
      provider: {
        ${provider.lower}: {
          keys: {
            apikey: { value: '$${provider.ENV}_APIKEY' },
          },
        },
      },
    })
    .use(${provider.pluginName}, pluginopts)

  return seneca.ready()
}
`)
    })
  })
})


// --- .github/workflows/build.yml --------------------------------------------

const Workflow = cmp(function Workflow(props: any) {
  const { provider } = props

  Folder({ name: '.github' }, () => {
    Folder({ name: 'workflows' }, () => {
      File({ name: 'build.yml' }, () => {
        Content(`# Generated by @voxgig/sdkgen. Do not edit.
#
# The ${provider.api} SDK is a normal published dependency, so \`npm install\`
# is all that is needed to build and run the offline tests on every platform.

name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [24.x]

    runs-on: \${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: \${{ matrix.node-version }}

      - run: npm install
      - run: npm i seneca seneca-entity seneca-promisify @seneca/provider @seneca/env
      - run: npm run build --if-present
      - run: npm test
`)
      })
    })
  })
})


// --- README.md ---------------------------------------------------------------

const Readme = cmp(function Readme(props: any) {
  const { provider } = props

  File({ name: 'README.md' }, () => {
    Content(`# ${provider.pkgName}

Seneca entity provider for the ${provider.api} API, using the
[\`${provider.sdkPkg}\`](https://www.npmjs.com/package/${provider.sdkPkg}) SDK.

Generated by [@voxgig/sdkgen](https://github.com/voxgig/sdkgen) from the
${provider.api} API definition. Do not edit by hand — change the model and
regenerate.

## Install

\`\`\`sh
npm install ${provider.pkgName}
\`\`\`

This plugin expects the Seneca host framework to be present:

\`\`\`sh
npm install seneca seneca-entity seneca-promisify @seneca/provider @seneca/env
\`\`\`

## Usage

\`\`\`js
const Seneca = require('seneca')

const seneca = Seneca()
  .use('promisify')
  .use('entity')
  .use('env', { var: { $${provider.ENV}_APIKEY: '' } })
  .use('provider', {
    provider: {
      ${provider.lower}: {
        keys: { apikey: { value: '$${provider.ENV}_APIKEY' } },
      },
    },
  })
  .use('${provider.pkgName}')

await seneca.ready()
\`\`\`

## Entities

Each API entity is exposed as a Seneca entity under
\`provider/${provider.lower}/<entity>\`.

| Seneca entity | Commands |
| --- | --- |
`)
    each(provider.entities, (e: any) => {
      Content(`| \`provider/${provider.lower}/${e.name}\` | ${e.cmds.map((c: string) => '`' + c + '$`').join(', ')} |
`)
    })

    const nested = provider.entities.filter((e: any) => 0 < e.parents.length)
    if (0 < nested.length) {
      Content(`
### Nested entities

Some entities live under a parent in the API path, so every command needs the
parent's id in the query. Leaving it out throws with a message naming the
missing key, rather than failing as an opaque 404 from a half-built URL.

`)
      each(nested, (e: any) => {
        Content(`- \`${e.name}\` requires \`${e.parents.join('`, `')}\`
`)
      })
    }

    Content(`
## Offline testing

The SDK ships an in-memory mock transport, so this plugin can be exercised
with no server:

\`\`\`js
.use('${provider.pkgName}', { test: true, testopts: { entity: { ... } } })
\`\`\`

\`testopts\` is passed straight to the SDK's test constructor; \`entity\`
seeds the mock store. See \`test/seed.js\` for the shape.
`)
  })
})


export {
  Tests,
  Workflow,
  Readme,
}
