import {
  cmp, each,
  File, Content, Folder,
} from '@voxgig/sdkgen'


// The rest of the seneca-provider package: its test suite, CI workflow and
// README. Split out of Main only for size — everything here is driven by the
// same `provider` shape Main builds from the model.
//
// The tests are the reason this target is worth generating at all. A provider
// is thin, and the thin part is exactly where the mistakes are: a cmd that
// forgets a parent path param, an entity that comes back under the wrong
// canon, a 404 that should have been `null` and instead threw. All three are
// checked below, offline, against the SDK's own mock transport — so a
// generated provider is verified without a server.


// A plausible seed record for an entity: its required fields, given values
// that read as data rather than as `string`.
function seedRecord(e: any, idx: number): Record<string, any> {
  const out: Record<string, any> = {}

  for (const f of e.fields) {
    if ('id' === f.name || f.name === e.idf) {
      out[f.name] = `${e.name}${idx}`
    }
    else if (e.parents.includes(f.name)) {
      // A nested entity's parent id must match a record the parent seeds, or
      // the offline store answers nothing and every nested test reads as a
      // false pass.
      out[f.name] = `${f.parentEntity}0`
    }
    else if ('number' === f.kind) {
      out[f.name] = 100 * (idx + 1)
    }
    else if ('boolean' === f.kind) {
      out[f.name] = false
    }
    else {
      out[f.name] = `${f.name}${idx}`
    }
  }

  return out
}


const Tests = cmp(function Tests(props: any) {
  const { provider } = props

  // The entity the suite exercises hardest: prefer one with no parent keys
  // (nothing to arrange) and the most cmds.
  const subject = [...provider.entities]
    .sort((a: any, b: any) =>
      (a.parents.length - b.parents.length) || (b.cmds.length - a.cmds.length))[0]

  const nested = provider.entities.filter((e: any) => 0 < e.parents.length)

  Folder({ name: 'test' }, () => {

    // The seed the offline mock transport is loaded with. Generated from the
    // model so it matches the shape the SDK will actually return.
    File({ name: 'seed.js' }, () => {
      Content(`/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

// Seed data for the SDK's offline mock transport, so the entity tests
// exercise real code paths without a server.
const SEED = {
  entity: {
`)
      each(provider.entities, (e: any) => {
        Content(`    ${e.name}: {
`)
        each([0, 1], (i: any) => {
          const idx = Number(i.val$ ?? i)
          const rec = seedRecord(e, idx)
          Content(`      ${e.name}${idx}: ${JSON.stringify(rec)},
`)
        })
        Content(`    },
`)
      })
      Content(`  },
}

module.exports = { SEED }
`)
    })


    // The message-level spec seneca-msg-test drives. TypeScript, compiled to
    // dist-test by test/tsconfig.json — which is also why it must exist: the
    // shipped tsconfig has `include: ["**/*.ts"]` and tsc fails outright on a
    // config that matches no input.
    File({ name: 'basic.messages.ts' }, () => {
      Content(`/* Generated by @voxgig/sdkgen. Do not edit. */

const Pkg = require('../package.json')

const messages = {
  print: false,
  pattern: 'sys:provider,provider:${provider.lower}',
  allow: { missing: true },

  calls: [
    {
      pattern: 'get:info',
      out: {
        ok: true,
        name: '${provider.lower}',
        version: Pkg.version,
      },
    },
  ],
}

export default messages

if ('undefined' !== typeof module) {
  module.exports = messages
}
`)
    })


    File({ name: `${provider.fileBase}.test.js` }, () => {
      Content(`/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

const { describe, it, before } = require('node:test')
const assert = require('node:assert')

const Seneca = require('seneca')

const ${provider.pluginName} = require('../dist/${provider.fileBase}')
const ${provider.pluginName}Doc = require('../dist/${provider.pluginName}-doc')

const SenecaMsgTest = require('seneca-msg-test')
const { Maintain } = require('@seneca/maintain')

const { SEED } = require('./seed')

const BasicMessages = require('../dist-test/basic.messages')
${'' === provider.liveBase ? '' : `
// The live tests run against the companion test server in the SDK repo
// (\`app/\`), which serves this by default. Start it with:
//   cd ${provider.sdkrel}/app && npm start
const LIVE_BASE = process.env.${provider.ENV}_TEST_BASE || '${provider.liveBase}'
`}

describe('${provider.fileBase}', () => {

  it('happy', async () => {
    assert.notEqual(${provider.pluginName}, undefined)
    assert.notEqual(${provider.pluginName}Doc, undefined)

    const seneca = await makeSeneca()

    assert.partialDeepStrictEqual(
      await seneca.post('sys:provider,provider:${provider.lower},get:info'),
      {
        ok: true,
        name: '${provider.lower}',
      },
    )
  })


  it('messages', async () => {
    const seneca = await makeSeneca()
    await SenecaMsgTest(seneca, BasicMessages)()
  })


  it('sdk-export', async () => {
    const seneca = await makeSeneca()
    const sdk = seneca.export('${provider.pluginName}/sdk')()

`)
      each(provider.entities, (e: any) => {
        Content(`    assert.equal(typeof sdk.${e.acc}, 'function')
`)
      })
      Content(`  })

`)

      if (subject.cmds.includes('list')) {
        Content(`
  it('${subject.name}-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/${provider.lower}/${subject.name}').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/${provider.lower}/${subject.name}',
    )
  })

`)
      }

      if (subject.cmds.includes('load')) {
        Content(`
  it('${subject.name}-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/${provider.lower}/${subject.name}')
      .load$('${subject.name}0')

    assert.equal(found.${subject.idf || 'id'}, '${subject.name}0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/${provider.lower}/${subject.name}',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('${subject.name}-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/${provider.lower}/${subject.name}')
      .load$('nosuch${subject.name}')

    assert.equal(missing, null)
  })

`)
      }

      // A nested entity cannot build its path without the parent id. That is
      // the mistake this target exists to make impossible, so pin it.
      each(nested, (e: any) => {
        const key = e.parents[0]
        Content(`
  it('${e.name}-needs-${key}', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/${provider.lower}/${e.name}').list$({}),
      /${key} is required/,
    )
  })

`)
        if (e.cmds.includes('list')) {
          Content(`
  it('${e.name}-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca
      .entity('provider/${provider.lower}/${e.name}')
      .list$({ ${key}: '${e.parentEntity || ''}0' })

    assert.ok(Array.isArray(list))
  })

`)
        }

        // Reading ONE nested record is the path that has to thread both the
        // parent id and the entity id through to the SDK, so cover it
        // separately from list.
        if (e.cmds.includes('load')) {
          Content(`
  it('${e.name}-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/${provider.lower}/${e.name}')
      .load$({ ${key}: '${e.parentEntity || ''}0', ${e.idf || 'id'}: '${e.name}0' })

    assert.equal(found.${e.idf || 'id'}, '${e.name}0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/${provider.lower}/${e.name}',
    )
  })


  it('${e.name}-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/${provider.lower}/${e.name}')
      .load$({ ${key}: '${e.parentEntity || ''}0', ${e.idf || 'id'}: 'nosuch${e.name}' })

    assert.equal(missing, null)
  })

`)
        }
      })

      // Live tests, against the companion server in the SDK repo's `app/`.
      // They PROBE first and skip when nothing is listening, so the suite is
      // green on a machine that has never started it — a live suite that
      // fails when the server is absent is one nobody runs.
      if ('' !== provider.liveBase) {
        Content(`
  describe('live', () => {
    let live = false

    before(async () => {
      live = await serverUp(LIVE_BASE)
    })

`)
        if (subject.cmds.includes('list')) {
          Content(`    it('${subject.name}-list', async (t) => {
      if (!live) return t.skip(noServer())
      const seneca = await makeSeneca(liveOpts())

      const list = await seneca.entity('provider/${provider.lower}/${subject.name}').list$()

      assert.ok(Array.isArray(list))
      if (0 < list.length) {
        assert.equal(
          list[0].canon$({ string: true }),
          'provider/${provider.lower}/${subject.name}',
        )
      }
    })

`)
        }
        if (subject.cmds.includes('load')) {
          Content(`    // A read of something that is not there is \`null\`, live as well as
    // offline: the provider's 404 handling is the same code path either way.
    it('${subject.name}-load-missing', async (t) => {
      if (!live) return t.skip(noServer())
      const seneca = await makeSeneca(liveOpts())

      assert.equal(
        await seneca
          .entity('provider/${provider.lower}/${subject.name}')
          .load$('nosuch${subject.name}'),
        null,
      )
    })

`)
        }
        Content(`  })

`)
      }

      // Repository hygiene, from the @seneca/maintain dependency this package
      // declares. Two of its checks report a fault that is not there, because
      // of WHERE they run rather than what they find, so each is excluded
      // only in the environment that breaks it.
      Content(`
  it('maintain', async () => {
    const exclude = []

    // check_default proves the default branch is main by looking for
    // [branch "main"] in .git/config. A pull_request build checks out the
    // merge ref, which records no such section.
    if ('pull_request' === process.env.GITHUB_EVENT_NAME) {
      exclude.push('check_default')
    }

    // url_pkgjson locates package.json by comparing process.cwd() + '/package.json'
    // against a path found with Filehound. On Windows those are the same file
    // spelt with different separators, so the url is never read.
    if ('win32' === process.platform) {
      exclude.push('url_pkgjson')
    }

    await Maintain({ exclude })
  })

`)

      Content(`})

`)

      if ('' !== provider.liveBase) {
        Content(`
function noServer() {
  return 'no ${provider.lower} server at ' + LIVE_BASE
}


function liveOpts() {
  return { sdk: { base: LIVE_BASE } }
}


// Probe the companion test server so live tests skip cleanly when it is not
// running, rather than failing the suite.
async function serverUp(base) {
  try {
    const res = await fetch(base + '${provider.probePath}', {
      signal: AbortSignal.timeout(2000),
    })
    return res.ok
  }
  catch (e) {
    return false
  }
}

`)
      }

      Content(`
// Default to the SDK's offline mock transport, seeded from ./seed.
async function makeSeneca(pluginopts) {
  pluginopts = pluginopts || { test: true, testopts: SEED }

  const seneca = Seneca({ legacy: false })
    .test()
    .use('promisify')
    .use('entity')
    .use('env', {
      // Declared so the provider convention is exercised, and defaulted so
      // the suite runs with nothing configured.
      var: {
        $${provider.ENV}_APIKEY: '',
      },
    })
    .use('provider', {
      provider: {
        ${provider.lower}: {
          keys: {
            apikey: { value: '$${provider.ENV}_APIKEY' },
          },
        },
      },
    })
    .use(${provider.pluginName}, pluginopts)

  return seneca.ready()
}
`)
    })
  })
})


// --- test/live.js, test/quick.js --------------------------------------------
//
// Manual scripts, not part of `npm test`: they need the companion server in
// the SDK repo's `app/`, which is not published. Generated because the path
// to that server is knowable — it is the inverse of this target's own
// `output: path` — so the instruction can be exact rather than "start the
// server somehow".

const Scripts = cmp(function Scripts(props: any) {
  const { provider } = props

  // Nothing to point at without a declared server.
  if ('' === provider.liveBase) {
    return
  }

  const subject = [...provider.entities]
    .sort((a: any, b: any) =>
      (a.parents.length - b.parents.length) || (b.cmds.length - a.cmds.length))[0]

  const senecaSetup = `const Seneca = require('seneca')

const BASE = process.env.${provider.ENV}_TEST_BASE || '${provider.liveBase}'

async function makeSeneca() {
  return Seneca({ legacy: false })
    .test()
    .use('promisify')
    .use('entity')
    .use('provider', {
      provider: {
        ${provider.lower}: {
          keys: {
            apikey: { value: '' },
          },
        },
      },
    })
    .use('..', { sdk: { base: BASE } })
    .ready()
}
`

  Folder({ name: 'test' }, () => {

    File({ name: 'live.js' }, () => {
      Content(`/* Manual script: read from a running ${provider.api} server.
 *
 * Start the companion test server from the SDK repo first:
 *   cd ${provider.sdkrel}/app && npm start
 *
 * Then:  node test/live.js
 */

${senecaSetup}

run()

async function run() {
  const seneca = await makeSeneca()

`)
      // A nested entity's list needs its parent's id, so LOOK ONE UP rather
      // than emitting a placeholder: a script that 404s on first run teaches
      // nothing and reads as a broken provider.
      each(provider.entities.filter((e: any) => e.cmds.includes('list')), (e: any) => {
        if (0 === e.parents.length) {
          Content(`  console.log('${e.name.toUpperCase()}', await seneca
    .entity('provider/${provider.lower}/${e.name}')
    .list$())

`)
          return
        }

        const parent = provider.entities
          .find((p: any) => p.name === e.parentEntity && p.cmds.includes('list'))
        if (null == parent) {
          // Nothing to derive the parent id from. Say so in the script
          // rather than emitting a call that cannot work.
          Content(`  // ${e.name}: needs ${e.parents.join(', ')}; no listable parent to take
  // one from, so supply it yourself:
  //   await seneca.entity('provider/${provider.lower}/${e.name}')
  //     .list$({ ${e.parents.map((k: string) => `${k}: '...'`).join(', ')} })

`)
          return
        }

        const key = e.parents[0]
        Content(`  const ${parent.name}s = await seneca
    .entity('provider/${provider.lower}/${parent.name}')
    .list$()

  if (0 < ${parent.name}s.length) {
    console.log('${e.name.toUpperCase()}', await seneca
      .entity('provider/${provider.lower}/${e.name}')
      .list$({ ${key}: ${parent.name}s[0].${parent.idf || 'id'} }))
  }

`)
      })
      Content(`}
`)
    })


    // The write cycle, kept separate: it MUTATES the server, so it is not
    // something to run by reflex. It cleans up after itself.
    if (subject.cmds.includes('save') && subject.cmds.includes('remove')) {
      const idf = subject.idf || 'id'
      const writable = subject.fields
        .filter((f: any) => f.name !== idf && f.name !== 'id')
        .filter((f: any) => !subject.parents.includes(f.name))

      const make = writable
        .map((f: any) => `${f.name}: ${'number' === f.kind ? '1234' :
          'boolean' === f.kind ? 'false' : `'quick-${f.name}'`}`)
        .join(', ')

      File({ name: 'quick.js' }, () => {
        Content(`/* Manual script: exercise the full CRUD cycle against a running server.
 *
 * Start the companion test server from the SDK repo first:
 *   cd ${provider.sdkrel}/app && npm start
 *
 * Then:  node test/quick.js
 *
 * Creates and then removes a ${subject.name}, so the server is left as found.
 */

${senecaSetup}

run()

async function run() {
  const seneca = await makeSeneca()

  // Create: the API assigns the id, so none is supplied here.
  let ${subject.name} = await seneca
    .entity('provider/${provider.lower}/${subject.name}')
    .make$({ ${make} })
    .save$()
  console.log('CREATED', ${subject.name})

  const id = ${subject.name}.${idf}

  try {
`)
        if (subject.ops.includes('update') && 0 < writable.length) {
          const f = writable[0]
          const v = 'number' === f.kind ? '4321' :
            'boolean' === f.kind ? 'true' : `'quick-${f.name}-2'`
          Content(`    // Update: an entity carrying an id is an update.
    ${subject.name}.${f.name} = ${v}
    console.log('UPDATED', await ${subject.name}.save$())

`)
        }
        if (subject.cmds.includes('load')) {
          Content(`    console.log(
      'LOADED',
      await seneca.entity('provider/${provider.lower}/${subject.name}').load$(id)
    )

`)
        }
        Content(`  }
  finally {
    await seneca.entity('provider/${provider.lower}/${subject.name}').remove$(id)
    console.log('REMOVED', id)
  }
`)
        if (subject.cmds.includes('load')) {
          Content(`
  console.log(
    'AFTER REMOVE (expect null)',
    await seneca.entity('provider/${provider.lower}/${subject.name}').load$(id)
  )
`)
        }
        Content(`}
`)
      })
    }
  })
})


// --- .github/workflows/build.yml --------------------------------------------

const Workflow = cmp(function Workflow(props: any) {
  const { provider } = props

  Folder({ name: '.github' }, () => {
    Folder({ name: 'workflows' }, () => {
      File({ name: 'build.yml' }, () => {
        Content(`# Generated by @voxgig/sdkgen. Do not edit.
#
# The ${provider.api} SDK is a normal published dependency, so \`npm install\`
# is all that is needed to build and run the offline tests on every platform.
${'' === provider.liveBase ? '' : `#
# The live tests additionally need the companion server, which is only
# distributed in the SDK's source repository (it is not published). That repo
# is cloned and started on Linux only, because backgrounding the server
# assumes a POSIX shell. The live tests probe for the server and skip cleanly
# when it is absent, so on Windows and macOS they simply skip.`}

name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [24.x]

    runs-on: \${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: \${{ matrix.node-version }}

${'' === provider.liveBase ? '' : `
      # Live-test target. Failure to start degrades coverage (the live tests
      # skip) rather than failing the build.
      - name: Start the ${provider.api} test server
        if: runner.os == 'Linux'
        run: |
          git clone --depth 1 \\
            ${provider.sdkRepoUrl}.git \\
            "$RUNNER_TEMP/sdk"
          cd "$RUNNER_TEMP/sdk/app"
          npm install
          npm run build
          npm start &
          for i in $(seq 1 30); do
            if curl -sf ${provider.liveBase}${provider.probePath} > /dev/null; then
              echo "server up"
              exit 0
            fi
            sleep 1
          done
          echo "server did not start; live tests will skip"
`}
      - run: npm install
      - run: npm i seneca seneca-entity seneca-promisify @seneca/provider @seneca/env
      - run: npm run build --if-present
      - run: npm test
`)
      })
    })
  })
})


// --- README.md ---------------------------------------------------------------
//
// The heading set is NOT free: @seneca/maintain checks a Seneca plugin README
// for "Quick Example", "More Examples", "Motivation", "Support", "API",
// "Contributing" and "Background", and the generated `maintain` test fails
// without them. That check is the reason to generate this file rather than
// leave it to a maintainer.

const Readme = cmp(function Readme(props: any) {
  const { provider } = props

  const subject = [...provider.entities]
    .sort((a: any, b: any) =>
      (a.parents.length - b.parents.length) || (b.cmds.length - a.cmds.length))[0]

  const nested = provider.entities.filter((e: any) => 0 < e.parents.length)

  File({ name: 'README.md' }, () => {
    Content(`![Seneca ${provider.Name}-Provider](http://senecajs.org/files/assets/seneca-logo.png)

> _Seneca ${provider.Name}-Provider_ is a plugin for [Seneca](http://senecajs.org)

Provides access to the ${provider.api} API using the Seneca _provider_
convention. ${provider.api} entities are represented as Seneca entities so that
they can be accessed using the Seneca entity API and messages.

Requests are handled by the [${provider.api} SDK](${provider.sdkRepoUrl}),
which is generated from the API's OpenAPI specification. This plugin is
generated from the same specification by
[@voxgig/sdkgen](https://github.com/voxgig/sdkgen) — do not edit it by hand,
change the model and regenerate.

See [seneca-entity](https://github.com/senecajs/seneca-entity) and the [Seneca Data
Entities
Tutorial](https://senecajs.org/docs/tutorials/understanding-data-entities.html)
for more details on the Seneca entity API.

[![build](${provider.repoUrl}/actions/workflows/build.yml/badge.svg)](${provider.repoUrl}/actions/workflows/build.yml)

| This open source module is sponsored and supported by [${provider.publisher}](${provider.publisherUrl}). |
| --- |


<!--START:SECTION:intro-->
<!--END:SECTION:intro-->


## Quick Example

\`\`\`js
const Seneca = require('seneca')

const seneca = Seneca()
  .use('promisify')
  .use('entity')
  .use('env', { var: { $${provider.ENV}_APIKEY: '' } })
  .use('provider', {
    provider: {
      ${provider.lower}: {
        keys: { apikey: { value: '$${provider.ENV}_APIKEY' } },
      },
    },
  })
  .use('${provider.pkgName}')

await seneca.ready()

`)
    if (subject.cmds.includes('list')) {
      Content(`const ${subject.name}s = await seneca
  .entity('provider/${provider.lower}/${subject.name}').list$()
`)
    }
    if (subject.cmds.includes('load')) {
      Content(`const ${subject.name} = await seneca
  .entity('provider/${provider.lower}/${subject.name}').load$('some-id')
`)
    }
    Content(`\`\`\`


## Install

\`\`\`sh
npm install ${provider.pkgName}
\`\`\`

This plugin expects the Seneca host framework to be present:

\`\`\`sh
npm install seneca seneca-entity seneca-promisify @seneca/provider @seneca/env
\`\`\`


## Options

| Option | Type | Description |
| --- | --- | --- |
| \`sdk\` | object | Passed straight to the \`${provider.sdkClass}\` constructor. Most usefully \`base\`, to point at a server. |
| \`test\` | boolean | Run the SDK in offline test mode (in-memory mock transport). |
| \`testopts\` | object | Seed and options for the mock, used only when \`test\` is true. |


## Entities

Each API entity is exposed as a Seneca entity under
\`provider/${provider.lower}/<entity>\`.

| Seneca entity | Commands |
| --- | --- |
`)
    each(provider.entities, (e: any) => {
      Content(`| \`provider/${provider.lower}/${e.name}\` | ${e.cmds.map((c: string) => '`' + c + '$`').join(', ')} |
`)
    })

    if (0 < nested.length) {
      Content(`
### Nested entities

Some entities live under a parent in the API path, so every command needs the
parent's id in the query. Leaving it out throws with a message naming the
missing key, rather than failing as an opaque 404 from a half-built URL.

`)
      each(nested, (e: any) => {
        Content(`- \`${e.name}\` requires \`${e.parents.join('`, `')}\`
`)
      })
    }

    Content(`

## Action Patterns

| Pattern | Description |
| --- | --- |
| \`sys:provider,provider:${provider.lower},get:info\` | Plugin and SDK version information. |


## More Examples

### Offline testing

The SDK ships an in-memory mock transport, so this plugin can be exercised
with no server:

\`\`\`js
.use('${provider.pkgName}', { test: true, testopts: { entity: { ... } } })
\`\`\`

\`testopts\` is passed straight to the SDK's test constructor; \`entity\`
seeds the mock store. See \`test/seed.js\` for the shape.

`)
    if ('' !== provider.liveBase) {
      Content(`### Running against a server

\`\`\`js
.use('${provider.pkgName}', { sdk: { base: '${provider.liveBase}' } })
\`\`\`

The companion test server is distributed in the SDK's source repository
only. From a checkout beside this one:

\`\`\`sh
cd ${provider.sdkrel}/app && npm start
\`\`\`

Then \`node test/live.js\` reads from it, and \`node test/quick.js\` runs a
full create/update/load/remove cycle.

`)
    }

    Content(`
## Motivation

Applications rarely talk to one external service, and each service usually
arrives with its own client library, authentication style and error
conventions. That variety leaks into application code and makes it harder to
test.

The Seneca provider convention removes the variety: every external service
becomes a Seneca entity reached with \`list$\`, \`load$\`, \`save$\` and
\`remove$\`, so application code has one shape regardless of what it talks to.

The SDK underneath arrives at a similar conclusion from the other side — it
deliberately exposes entities rather than HTTP routes. This plugin is the
short bridge between the two.


## Support

- Issues and bugs: [GitHub issues](${provider.repoUrl}/issues)
- Seneca community: [senecajs.org](http://senecajs.org)


## API

### Plugin export: \`${provider.pluginName}/sdk\`

Returns the configured \`${provider.sdkClass}\` instance, for the operations
the entity API does not cover:

\`\`\`js
const sdk = seneca.export('${provider.pluginName}/sdk')()
\`\`\`


## Contributing

This plugin is GENERATED. Changes belong in the SDK project's model and
components, not here — anything edited in this repository is overwritten by
the next generation run.

The [Senecajs org](http://senecajs.org) encourages open participation. If you
feel you can help in any way, be it with bug reporting, documentation,
examples, extra testing, or new features, please get in touch.


## Background

Generated by [@voxgig/sdkgen](https://github.com/voxgig/sdkgen) from the
${provider.api} API definition, against the
[${provider.sdkPkg}](https://www.npmjs.com/package/${provider.sdkPkg}) SDK.
`)
  })
})


export {
  Tests,
  Scripts,
  Workflow,
  Readme,
}
