import {
  Content,
  File,
  cmp,
  packageVersion,
} from '@voxgig/sdkgen'

import type {
  Model,
} from '@voxgig/apidef'

import { pkgName } from './utility_lean'


// Each runtime module is its own `lean_lib` (Lake globs `<LibName>.lean` from
// srcDir), matching the vendored struct project's layout. The runtime is
// dependency-free (prelude + Std only); the HTTP transport shells to curl.
const LIBS = [
  'Vregex', 'VoxgigStruct', 'SdkJson', 'SdkUtility', 'SdkFeature', 'SdkFeatures', 'SdkRuntime', 'SdkConfig',
  'SdkClient',
]


const Package = cmp(async function Package(props: any) {
  const ctx$ = props.ctx$
  const target = props.target
  const model: Model = ctx$.model

  const libBlocks = LIBS.map((n) =>
    `[[lean_lib]]\nname = "${n}"\nsrcDir = "src"\n`).join('\n')

  File({ name: 'lakefile.toml' }, () => {
    Content(`# ${model.const.Name} SDK for Lean 4 (generated by @voxgig/sdkgen).
name = "${pkgName(model)}"
version = "${packageVersion(model, target.name)}"
defaultTargets = ["SdkClient"]

${libBlocks}
[[lean_exe]]
name = "runner"
srcDir = "test"
root = "Runner"

[[lean_exe]]
name = "structcorpus"
srcDir = "test"
root = "StructCorpus"

[[lean_exe]]
name = "primary"
srcDir = "test"
root = "TPrimaryUtility"

[[lean_exe]]
name = "feature"
srcDir = "test"
root = "TFeature"
`)
  })

  // Pin the toolchain to the version the runtime is developed against.
  File({ name: 'lean-toolchain' }, () => {
    Content(`leanprover/lean4:v4.32.1\n`)
  })
})


export {
  Package
}
