import {
  Content,
  File,
  Folder,
  cmp,
  each,
} from '@voxgig/sdkgen'

import {
  KIT,
  Model,
  getModelPath,
} from '@voxgig/apidef'


// True when an op has at least one endpoint point that needs no path params
// (a top-level operation the live smoke test can call without an id).
function hasParamFreePoint(op: any): boolean {
  if (null == op) return false
  const points = op.points || []
  for (const pt of points) {
    const params = ((pt.args || {}).params) || []
    if (params.length === 0) return true
  }
  return false
}


// Synthesize a create payload from the entity's required non-id fields.
function synthData(fields: any): any {
  const o: any = {}
  each(fields, (f: any) => {
    if (f.req && f.name !== 'id') {
      const t = String(f.type || '').toLowerCase()
      o[f.name] =
        (t.includes('number') || t.includes('integer') || t.includes('decimal')) ? 42
          : t.includes('bool') ? true
            : 'leantest'
    }
  })
  return o
}


// The offline+live test runner. Every generated SDK ships a `test/Runner.lean`
// exe: it points a client at the local test server (SDK_TEST_BASE or the
// default) and exercises the config-driven runtime end-to-end — a `list` smoke
// test on every top-level entity, and a create/load/remove round-trip on each
// entity with a param-free create.
const Test = cmp(async function Test(props: any) {
  const ctx$ = props.ctx$
  const target = props.target
  const model: Model = ctx$.model

  const entity = getModelPath(model, `main.${KIT}.entity`)

  // Per-entity generated test blocks.
  let blocks = ''
  each(entity, (e: any) => {
    const ns = e.name.charAt(0).toUpperCase() + e.name.slice(1)
    const listOp = (e.op || {}).list
    const createOp = (e.op || {}).create
    const removeOp = (e.op || {}).remove

    if (hasParamFreePoint(listOp)) {
      blocks += `    -- ${e.name}: list smoke
    (do
      let items ← ${ns}.list client (← emptyMap) (← emptyMap)
      match items with
      | .list lid => pass s!"${e.name}.list -> {(← listItems lid).size} items"
      | _ => fail "${e.name}.list did not return a list")
`
    }

    // Round-trip when create is param-free (creatable without an id); load and
    // remove then use the id returned by create.
    const loadOp = (e.op || {}).load
    if (hasParamFreePoint(createOp) && loadOp && removeOp) {
      const data = JSON.stringify(synthData(e.fields))
      blocks += `    -- ${e.name}: create / load / remove round-trip
    (do
      let d ← SdkJson.jsonRead ${JSON.stringify(data)}
      let created ← ${ns}.create client d (← emptyMap)
      let nid ← SdkRuntime.gpS created "id"
      if nid == "" then fail "${e.name}.create returned no id" else do
        let m ← newMap #[("id", .str nid)]
        let back ← ${ns}.load client m (← emptyMap)
        let bid ← SdkRuntime.gpS back "id"
        if bid == nid then pass s!"${e.name}.create/load round-trip (id={nid})"
        else fail s!"${e.name}.load mismatch: {bid} != {nid}"
        let _ ← ${ns}.remove client m (← emptyMap)
        pass s!"${e.name}.remove (id={nid})")
`
    }
  })

  Folder({ name: 'test' }, () => {
  File({ name: 'Runner.' + target.ext }, () => {
    Content(`-- ${model.const.Name} SDK test runner (generated by @voxgig/sdkgen).
-- Exercises the config-driven runtime against the local test server.
-- Override the base with the SDK_TEST_BASE env var.

import VoxgigStruct
import SdkJson
import SdkRuntime
import SdkClient

open VoxgigStruct

initialize npass : IO.Ref Nat ← IO.mkRef 0
initialize nfail : IO.Ref Nat ← IO.mkRef 0

def pass (msg : String) : SIO Unit := do
  npass.modify (· + 1)
  IO.println s!"ok   - {msg}"

def fail (msg : String) : SIO Unit := do
  nfail.modify (· + 1)
  IO.println s!"FAIL - {msg}"

def defaultBase : String := "http://localhost:8901"

def main : IO UInt32 := do
  let base := (← IO.getEnv "SDK_TEST_BASE").getD defaultBase
  let ctx ← mkCtx
  let go : SIO Unit := do
    let opts ← newMap #[("base", .str base)]
    let client ← Sdk.newSdk opts
${blocks}  go.run ctx
  let p ← npass.get
  let f ← nfail.get
  IO.println ""
  IO.println s!"PASS {p}  FAIL {f}"
  if f > 0 then return 1 else return 0
`)
  })
  })
})


export {
  Test
}
