import { test, describe } from 'node:test'
import { deepStrictEqual, strictEqual } from 'node:assert'

import {
  publisherInfo,
  securityContact,
  authorInfo,
  keywords,
  nonAffiliation,
} from '../dist/helpers/packageMeta.js'
import { ensureStdrep } from '../dist/helpers/stdrep.js'


function model(publisher?: any, rest?: any): any {
  return {
    name: 'demo',
    main: { kit: { ...(publisher ? { publisher } : {}), ...(rest || {}) } },
  }
}


describe('publisher', () => {

  test('an undeclared or empty publisher is Voxgig, with its url and contact', () => {
    const voxgig = {
      name: 'Voxgig', url: 'https://voxgig.com', security: 'security@voxgig.com',
    }
    deepStrictEqual(publisherInfo(model()), voxgig)
    deepStrictEqual(publisherInfo(model({ name: '', url: '', security: '' })), voxgig)
    strictEqual(securityContact(model()), 'to security@voxgig.com')
  })

  test('another publisher takes none of Voxgig\'s url or contact', () => {
    const acme = model({ name: 'Acme' })
    deepStrictEqual(publisherInfo(acme), { name: 'Acme', url: '', security: '' })
    strictEqual(securityContact(acme), 'privately to Acme')
    strictEqual(securityContact(model({ name: 'Acme', url: 'https://acme.example' })),
      'privately to Acme (https://acme.example)')
    strictEqual(securityContact(model({ name: 'Acme', security: 'sec@acme.example' })),
      'to sec@acme.example')
  })

  test('the publisher is the default author, and a declared author wins', () => {
    deepStrictEqual(authorInfo(model({ name: 'Acme', url: 'https://acme.example' }), 'ts'),
      { name: 'Acme', url: 'https://acme.example' })

    const declared = model({ name: 'Acme', url: 'https://acme.example' },
      { author: { name: 'Ada', url: '' } })
    deepStrictEqual(authorInfo(declared, 'ts'), { name: 'Ada', url: '' })

    deepStrictEqual(authorInfo(model(), 'ts'),
      { name: 'Voxgig', url: 'https://voxgig.com' })
  })

  test('only Voxgig is credited in keywords and the notice', () => {
    strictEqual(keywords(model())[0], 'voxgig')
    strictEqual(keywords(model({ name: 'Acme' })).includes('voxgig'), false)
    strictEqual(nonAffiliation(model({ name: 'Acme' })).includes('generated by Acme with'), true)
  })

  test('the template placeholder is the publisher name', () => {
    strictEqual(ensureStdrep({ model: model({ name: 'Acme' }) }).PROJECTPUBLISHER, 'Acme')
    strictEqual(ensureStdrep({ model: model() }).PROJECTPUBLISHER, 'Voxgig')
  })
})
