
import {
  cmp, each,
  File, Content,
} from '@voxgig/sdkgen'

import type {
  Model,
  ModelEntity,
} from '@voxgig/apidef'

import {
  KIT,
  getModelPath,
} from '@voxgig/apidef'


// Path to the AQL engine source. Local replace is used because the
// engine isn't yet published with a subdirectory tag (eng/vX.Y.Z).
// Once it's published, swap this for a `require` line with that
// version and delete the `replace`.
const AQL_ENG_LOCAL_PATH = '/home/richard/Projects/aql-lang/aql/eng/go'


const Main = cmp(function Main(props: any) {
  const { target } = props
  const { model } = props.ctx$

  const org = model.origin || 'voxgig-sdk'
  const sdkModule = `github.com/${org}/${model.name}-sdk/go`
  const cliModule = `github.com/${org}/${model.name}-sdk/go-cli`

  const entityMap: any = getModelPath(model, `main.${KIT}.entity`)

  // .gitignore — the binary lands at /<modulename>; ignore it.
  File({ name: '.gitignore' }, () => Content(`/${model.name}-cli
`))

  // go.mod — sibling SDK via relative replace; aql/eng via local replace.
  File({ name: 'go.mod' }, () => Content(`module ${cliModule}

go 1.20

require ${sdkModule} v0.0.0
require github.com/aql-lang/aql/eng v0.0.0

replace ${sdkModule} => ../go
replace github.com/aql-lang/aql/eng => ${AQL_ENG_LOCAL_PATH}
`))

  // main.go — argv-as-AQL-program plus a simple REPL.
  File({ name: 'main.go' }, () => Content(`// Command ${model.name}-cli is a CLI + REPL for the ${model.Name} SDK,
// built on the AQL engine. Positional args are joined into a single
// AQL expression and evaluated. With no args, falls into a REPL.
//
// Usage:
//
//   ${model.name}-cli list <entity>
//   ${model.name}-cli load <id> <entity>
//   ${model.name}-cli                    # REPL
//
// Generated by sdkgen go-cli target. Do not edit by hand.
package main

import (
\t"bufio"
\t"fmt"
\t"io"
\t"os"
\t"strings"

\t"github.com/aql-lang/aql/eng"
\t"github.com/aql-lang/aql/eng/parser"
\tsdk "${sdkModule}"
)

func main() {
\tos.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}

func run(args []string, in io.Reader, out, errOut io.Writer) int {
\tclient := sdk.New${model.const.Name}SDK(nil)

\tr, err := eng.NewRegistry()
\tif err != nil {
\t\tfmt.Fprintf(errOut, "registry: %v\\n", err)
\t\treturn 1
\t}
\tregisterSDKWords(r, client)
\tif err := r.Err(); err != nil {
\t\tfmt.Fprintf(errOut, "word registration: %v\\n", err)
\t\treturn 1
\t}
\tr.SetParseFunc(parser.Parse)
\tr.InitRootContext()
\tr.MarkReady()

\tif len(args) > 0 {
\t\treturn evalOnce(r, strings.Join(args, " "), out, errOut)
\t}
\trepl(r, in, out)
\treturn 0
}

func evalOnce(r *eng.Registry, src string, out, errOut io.Writer) int {
\tvalues, err := parser.Parse(src)
\tif err != nil {
\t\tfmt.Fprintf(errOut, "parse: %v\\n", err)
\t\treturn 1
\t}
\tresult, err := eng.NewTop(r).Run(values)
\tif err != nil {
\t\tfmt.Fprintf(errOut, "error: %v\\n", err)
\t\treturn 1
\t}
\tfor _, v := range result {
\t\tfmt.Fprintln(out, v.String())
\t}
\treturn 0
}

func repl(r *eng.Registry, in io.Reader, out io.Writer) {
\tscanner := bufio.NewScanner(in)
\tscanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
\tfor {
\t\tfmt.Fprint(out, "${model.name}> ")
\t\tif !scanner.Scan() {
\t\t\tfmt.Fprintln(out)
\t\t\treturn
\t\t}
\t\tline := strings.TrimSpace(scanner.Text())
\t\tif line == "" {
\t\t\tcontinue
\t\t}
\t\tswitch line {
\t\tcase ":quit", ":q", ":exit":
\t\t\treturn
\t\tcase ":help", ":h", ":?":
\t\t\tfmt.Fprintln(out, "commands: list / load / update <query?> <entity>")
\t\t\tfmt.Fprintln(out, "entities: ${Object.keys(entityMap).join(' ')}")
\t\t\tfmt.Fprintln(out, "meta:     :quit :help")
\t\t\tcontinue
\t\t}
\t\tvalues, err := parser.Parse(line)
\t\tif err != nil {
\t\t\tfmt.Fprintf(out, "  parse error: %v\\n", err)
\t\t\tcontinue
\t\t}
\t\tresult, err := eng.NewTop(r).Run(values)
\t\tif err != nil {
\t\t\tfmt.Fprintf(out, "  error: %v\\n", err)
\t\t\tcontinue
\t\t}
\t\tfor _, v := range result {
\t\t\tfmt.Fprintln(out, v.String())
\t\t}
\t}
}

`))

  // words.go — AQL native words list/load/update with overloaded sig,
  // entityFor dispatch table keyed by entity name (lowercase).
  File({ name: 'words.go' }, () => {
    Content(`// Generated by sdkgen go-cli target.
package main

import (
\t"fmt"
\t"strings"

\t"github.com/aql-lang/aql/eng"
\tsdk "${sdkModule}"
)

func registerSDKWords(r *eng.Registry, client *sdk.${model.const.Name}SDK) {
\tfor _, op := range []string{"list", "load", "update"} {
\t\top := op
\t\tsingle := eng.NativeSig{
\t\t\tArgs:      []*eng.Type{eng.TAtom},
\t\t\tQuoteArgs: map[int]bool{0: true},
\t\t\tHandler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
\t\t\t\treturn runOp(client, op, nil, args[0])
\t\t\t},
\t\t\tReturns: []*eng.Type{eng.TAny},
\t\t}
\t\tdual := eng.NativeSig{
\t\t\tArgs:      []*eng.Type{eng.TAny, eng.TAtom},
\t\t\tQuoteArgs: map[int]bool{1: true},
\t\t\tHandler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
\t\t\t\tq := args[0]
\t\t\t\treturn runOp(client, op, &q, args[1])
\t\t\t},
\t\t\tReturns: []*eng.Type{eng.TAny},
\t\t}
\t\tr.RegisterNativeFunc(eng.NativeFunc{
\t\t\tName:        op,
\t\t\tForwardArgs: true,
\t\t\tSignatures:  []eng.NativeSig{single, dual},
\t\t})
\t}
}

func runOp(client *sdk.${model.const.Name}SDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
\tentityName, err := eng.AsAtom(entityAtom)
\tif err != nil {
\t\treturn nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
\t}
\tent, err := entityFor(client, entityName)
\tif err != nil {
\t\treturn nil, fmt.Errorf("%s: %w", op, err)
\t}

\tvar arg map[string]any
\tif query != nil {
\t\targ, err = queryToMap(*query)
\t\tif err != nil {
\t\t\treturn nil, fmt.Errorf("%s: %w", op, err)
\t\t}
\t}

\tvar result any
\tswitch op {
\tcase "list":
\t\tresult, err = ent.List(arg, nil)
\tcase "load":
\t\tresult, err = ent.Load(arg, nil)
\tcase "update":
\t\tresult, err = ent.Update(arg, nil)
\tdefault:
\t\treturn nil, fmt.Errorf("unknown op %q", op)
\t}
\tif err != nil {
\t\treturn nil, err
\t}
\treturn []eng.Value{eng.FromNative(extractData(result))}, nil
}

`)

    // entityFor — switch over the entity list from the model.
    Content(`func entityFor(client *sdk.${model.const.Name}SDK, name string) (sdk.${model.const.Name}Entity, error) {
\tswitch strings.ToLower(name) {
`)
    each(entityMap, (entity: ModelEntity) => {
      const lowerName = entity.name.toLowerCase()
      // entity.Name is the PascalCase form sdkgen uses for Go methods.
      Content(`\tcase "${lowerName}":
\t\treturn client.${(entity as any).Name}(nil), nil
`)
    })
    Content(`\t}
\treturn nil, fmt.Errorf("unknown entity %q (try: ${Object.keys(entityMap).map(e => e.toLowerCase()).join(', ')})", name)
}

func queryToMap(v eng.Value) (map[string]any, error) {
\tif v.VType.Matches(eng.TMap) {
\t\tm, ok := eng.ToNative(v).(map[string]any)
\t\tif !ok {
\t\t\treturn nil, fmt.Errorf("query map could not be unwrapped")
\t\t}
\t\treturn m, nil
\t}
\tif v.VType.Matches(eng.TScalar) {
\t\treturn map[string]any{"id": eng.ToNative(v)}, nil
\t}
\treturn nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.VType)
}

func extractData(x any) any {
\tswitch v := x.(type) {
\tcase sdk.Entity:
\t\treturn extractData(v.Data())
\tcase []any:
\t\tout := make([]any, len(v))
\t\tfor i, e := range v {
\t\t\tout[i] = extractData(e)
\t\t}
\t\treturn out
\tcase map[string]any:
\t\tout := make(map[string]any, len(v))
\t\tfor k, vv := range v {
\t\t\tout[k] = extractData(vv)
\t\t}
\t\treturn out
\t}
\treturn x
}
`)
  })
})


export {
  Main
}
