
import * as Path from 'node:path'

import {
  cmp, each,
  File, Content, Fragment, Slot,
} from '@voxgig/sdkgen'

import type {
  ModelEntity,
} from '@voxgig/apidef'

import {
  KIT,
  getModelPath,
} from '@voxgig/apidef'


// Published aql/eng/go version. Tagged at aql-lang/aql under
// eng/go/v<X.Y.Z>. Bump here when adopting a newer engine.
const AQL_ENG_VERSION = 'v0.0.1'


const Main = cmp(function Main(props: any) {
  const { target } = props
  const { model } = props.ctx$

  const org = model.origin || 'voxgig-sdk'
  const sdkModule = `github.com/${org}/${model.name}-sdk/go`
  const cliModule = `github.com/${org}/${model.name}-sdk/go-cli`

  const entityMap: any = getModelPath(model, `main.${KIT}.entity`)
  const entityNames = Object.keys(entityMap).map(n => n.toLowerCase())

  const FRAGMENT = Path.normalize(__dirname + '/../../../src/cmp/go-cli/fragment')

  // .gitignore — the compiled binary lands at /<modulename>-cli; ignore it.
  File({ name: '.gitignore' }, () => Content(`/${model.name}-cli
`))

  // README.md — usage guide for the AQL-driven CLI.
  const entityList = entityNames.length > 0 ? entityNames.join(' ') : '(none)'
  const firstEntity = entityNames[0] || 'entity'
  File({ name: 'README.md' }, () => Content(`# ${model.name}-cli

AQL-driven CLI and REPL for the ${model.Name} SDK. Positional arguments are
joined into a single AQL expression and evaluated; with no arguments,
falls into an interactive REPL.

Built on \`github.com/aql-lang/aql/eng/go\` and the sibling Go SDK at \`../go\`.

## Build

\`\`\`sh
go build -o ${model.name}-cli ./...
\`\`\`

## Run

\`\`\`sh
# One-shot: arguments form a single AQL expression
./${model.name}-cli list ${firstEntity}
./${model.name}-cli load 1 ${firstEntity}
./${model.name}-cli load '{id:1}' ${firstEntity}

# REPL
./${model.name}-cli
\`\`\`

## Words

| Word     | Signatures                                   | Description                |
|----------|----------------------------------------------|----------------------------|
| \`list\`   | \`[entity]\` · \`[query entity]\`                | List records               |
| \`load\`   | \`[entity]\` · \`[query entity]\`                | Load a single record       |
| \`update\` | \`[entity]\` · \`[query entity]\`                | Update a record            |

\`query\` is either a Map (\`{id:1}\`) or a Scalar (\`1\`, treated as \`{id:1}\`).
\`entity\` is one of the SDK's entity names (auto-quoted as an atom).

## Entities

${entityList}

## REPL commands

- \`:quit\` / \`:q\` / \`:exit\` — exit the REPL
- \`:help\` / \`:h\` / \`:?\`     — show help

## Generated by

sdkgen \`go-cli\` target. See the target source under
\`.sdk/src/cmp/go-cli/\` in this repo, or upstream at
\`github.com/voxgig/sdkgen/project/.sdk/src/cmp/go-cli/\`.
`))

  // go.mod — sibling SDK via relative replace; aql/eng/go from the
  // public Go module proxy.
  File({ name: 'go.mod' }, () => Content(`module ${cliModule}

go 1.21

require ${sdkModule} v0.0.0
require github.com/aql-lang/aql/eng/go ${AQL_ENG_VERSION}

replace ${sdkModule} => ../go
`))

  // main.go — produced from fragment/main.fragment.go with two Slots
  // for the prompt label and the entity help line.
  File({ name: 'main.go' }, () => {
    Fragment(
      {
        from: Path.join(FRAGMENT, 'main.fragment.go'),
        replace: {
          ...props.ctx$.stdrep,
          GOMODULE: sdkModule,
        },
      },
      () => {
        Slot({ name: 'promptName' }, () => Content(model.name))
        Slot({ name: 'entityNamesSpaced' }, () => Content(entityNames.join(' ')))
      },
    )
  })

  // words.go — produced from fragment/words.fragment.go with a single
  // Slot that emits one `case "<name>":` per entity.
  File({ name: 'words.go' }, () => {
    Fragment(
      {
        from: Path.join(FRAGMENT, 'words.fragment.go'),
        replace: {
          ...props.ctx$.stdrep,
          GOMODULE: sdkModule,
        },
      },
      () => {
        Slot({ name: 'entityCases' }, () => {
          each(entityMap, (entity: ModelEntity) => {
            const lower = entity.name.toLowerCase()
            const pascal = (entity as any).Name
            Content(`\tcase "${lower}":
\t\treturn client.${pascal}(nil), nil
`)
          })
        })
      },
    )
  })
})


export {
  Main
}
