
import * as Path from 'node:path'

import {
  cmp,
  File, Content, Fragment,
} from '@voxgig/sdkgen'

import {
  getModelPath,
} from '@voxgig/apidef'

import { entityModule, ocamlString, ocamlVarName } from './utility_ocaml'
import { entityOp } from './EntityOperation_ocaml'


const Entity = cmp(function Entity(props: any) {
  const { model } = props.ctx$
  const { target, entity } = props

  const ff = Path.normalize(__dirname + '/../../../src/cmp/ocaml/fragment/')

  const opnames = Object.keys(entity.op || {})

  const ops = ['load', 'list', 'create', 'update', 'remove']
    .map((opname: string) => entityOp(opname, opnames.includes(opname), entity.name))
    .join('')

  File({ name: entityModule(entity.name) + '.' + target.ext }, () => {

    Content(`(* ${model.const.Name} SDK ${entity.Name} entity (generated by @voxgig/sdkgen).
 *
 * An entity is a mutable entity_obj record (see Sdk_types): its CRUD closures
 * drive the operation pipeline through run_op. Missing ops install a stub that
 * errors at call time so the record is always fully populated. *)

open Voxgig_struct
open Sdk_types
open Sdk_helpers
open Sdk_runtime

exception Op_return of value

`)

    // run_op — the operation pipeline runner. The (* #Stage-Hook *) marker
    // lines are the OCaml (* *)-comment hook form; jostraca's built-in
    // #Name-Tag replacement only matches //-comments, so match the (* *) form
    // explicitly and rewrite each to a feature_hook call.
    Fragment({
      from: ff + 'RunOp.fragment.ml',
      replace: {
        ...props.ctx$.stdrep,
        '/(?<indent>[ \\t]*)\\(\\*[ \\t]*#(?<name>[A-Za-z0-9]+)-Hook[ \\t]*\\*\\)[ \\t]*\\n?/':
          ({ name, indent }: any) => `${indent}feature_hook ctx "${name}";\n`,
      }
    })

    Content(`
let rec make (client : sdk_client) (entopts_in : value) : entity_obj =
  let entopts = match to_map entopts_in with Map _ as m -> m | _ -> empty_map () in
  (match getp entopts "active" with Bool false -> () | _ -> setp entopts "active" (Bool true));
  let utility = client.cl_utility in
  let root =
    match client.cl_rootctx with Some c -> c | None -> failwith "root context not initialised" in
  let ent = {
    e_name = "${ocamlString(entity.name)}";
    e_client = client;
    e_utility = utility;
    e_entopts = entopts;
    e_data = empty_map ();
    e_match = empty_map ();
    e_entctx = root;
    e_make = (fun () -> make client entopts);
    e_data_set = (fun _ -> ());
    e_data_get = (fun () -> empty_map ());
    e_match_set = (fun _ -> ());
    e_match_get = (fun () -> empty_map ());
    e_load = (fun _ _ -> Noval);
    e_list = (fun _ _ -> Noval);
    e_create = (fun _ _ -> Noval);
    e_update = (fun _ _ -> Noval);
    e_remove = (fun _ _ -> Noval);
    e_stream = (fun _ _ _ -> Seq.empty);
  } in
  let entctx = utility.u_make_context
      { (default_ctxspec ()) with cs_entity = Some ent; cs_entopts = Some entopts } (Some root) in
  ent.e_entctx <- entctx;
  utility.u_feature_hook entctx "PostConstructEntity";
  ent.e_data_set <- (fun args ->
      if not (is_nullish args) then begin
        ent.e_data <- (match to_map (clone args) with Map _ as m -> m | _ -> empty_map ());
        utility.u_feature_hook entctx "SetData"
      end);
  ent.e_data_get <- (fun () -> utility.u_feature_hook entctx "GetData"; clone ent.e_data);
  ent.e_match_set <- (fun args ->
      if not (is_nullish args) then begin
        ent.e_match <- (match to_map (clone args) with Map _ as m -> m | _ -> empty_map ());
        utility.u_feature_hook entctx "SetMatch"
      end);
  ent.e_match_get <- (fun () -> utility.u_feature_hook entctx "GetMatch"; clone ent.e_match);
  (* Streaming operation. Runs \`action\` (an op name, e.g. "list") through the
   * full pipeline and returns a lazy Seq over result items, so the streaming
   * feature's incremental output is reachable (a normal op call materialises
   * the whole result). When the streaming feature is active the result carries
   * a stream closure and this yields from it (honouring chunkSize); otherwise
   * it falls back to the materialised items, so stream always yields.
   * callopts parameterises the call: ctrl (per-call pipeline control), body (an
   * enumerable/list payload attached to the request for outbound streaming),
   * and signal (a 0-arity fn -> Bool; iteration stops when it returns true). *)
  ent.e_stream <- (fun action args callopts ->
      let callopts = match to_map callopts with Map _ as m -> m | _ -> empty_map () in
      let ctrl = match to_map (getp callopts "ctrl") with Map _ as m -> m | _ -> empty_map () in
      setp ctrl "stream" callopts;
      let reqmatch = match to_map args with Map _ as m -> m | _ -> empty_map () in
      let ctx = utility.u_make_context
          { (default_ctxspec ()) with
            cs_opname = Some action;
            cs_ctrl = Some ctrl;
            cs_match = Some ent.e_match; cs_data = Some ent.e_data;
            cs_reqmatch = Some reqmatch }
          (Some entctx) in
      let body = getp callopts "body" in
      (if not (is_nullish body) then begin
         let reqdata = match to_map ctx.c_reqdata with Map _ as m -> m | _ -> empty_map () in
         setp reqdata "body$" body;
         ctx.c_reqdata <- reqdata;
         scratch_set ctx "stream_out" body
       end);
      ignore (run_op ctx (fun () -> ()));
      let signal = getp callopts "signal" in
      let aborted () = match signal with Func _ -> call_json signal = Bool true | _ -> false in
      let raw = (match ctx.c_result with
          | Some result ->
            (match result.rt_stream with
             | Some fn -> fn ()
             | None -> (match result.rt_resdata with List r -> !r | v when is_nullish v -> [] | v -> [v]))
          | None -> []) in
      let rec seq_of l () = match l with
        | [] -> Seq.Nil
        | x :: rest -> if aborted () then Seq.Nil else Seq.Cons (x, seq_of rest) in
      seq_of raw);
  ignore run_op;
${ops}  ent
`)
  })
})


export {
  Entity
}
