
import {
  cmp, each,
  File, Content, Copy,
  entityClassName,
} from '@voxgig/sdkgen'


import type {
  ModelEntity
} from '@voxgig/apidef'


import {
  KIT,
  getModelPath
} from '@voxgig/apidef'


import { Package } from './Package_ocaml'
import { Config } from './Config_ocaml'
import { Gitignore } from './Gitignore_ocaml'
import { MainEntity } from './MainEntity_ocaml'
import { SdkError } from './SdkError_ocaml'


const Main = cmp(async function Main(props: any) {

  const { target } = props
  const { model } = props.ctx$

  const entity: Record<string, ModelEntity> = getModelPath(model, `main.${KIT}.entity`)

  Package({ target })

  Gitignore({})

  // Copy tm/ocaml verbatim with ProjectName replacement. The src/ subtree
  // only stages per-feature custom-source dirs (srcfeature: false, so unused),
  // excluded like the go/rust targets. Stray compiled artifacts are excluded
  // defensively.
  Copy({
    from: 'tm/' + target.name,
    exclude: [/src\//, /\.(cmi|cmo|cmx|cma|cmxa|o|a)$/, /a\.out$/, /run_sdk_test$/, /run_struct_corpus$/],
    replace: {
      ...props.ctx$.stdrep,
    }
  })

  // Generated API config + branded-error re-export.
  Config({ target })
  SdkError({ target })

  // sdk_client.ml — the client constructors, direct/prepare, and the
  // per-entity accessors (twin of the go root package + rust core/sdk.rs).
  File({ name: 'sdk_client.' + target.ext }, () => {

    Content(`(* ${model.const.Name} SDK client (generated by @voxgig/sdkgen).
 *
 * The SDK "object" is the runtime sdk_client record (see Sdk_types). These
 * constructors wire the embedded config + feature factory (Sdk_config) into
 * the API-agnostic client builders (Sdk_features.make_client_base / sdk_test).
 * Entity accessors return an entity_obj whose CRUD closures run the pipeline. *)

open Voxgig_struct
open Sdk_types
open Sdk_features

(* Construct a live client from options (Noval for defaults). *)
let make (options : value) : sdk_client =
  make_client_base
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    options

(* No-argument convenience constructor. *)
let make0 () : sdk_client = make Noval

(* Construct a client in test mode (in-memory mock transport). *)
let test () : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    Noval Noval

(* Test-mode client with explicit test / sdk options. *)
let test_with (testopts : value) (sdkopts : value) : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    testopts sdkopts

(* Low-level escape hatches (raw transport call / request preparation). *)
let direct (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.direct client fetchargs

let prepare (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.prepare client fetchargs
`)

    each(entity, (entity: ModelEntity) => {
      MainEntity({ target, entity })
    })
  })

})


export {
  Main
}
