
import {
  Content,
  File,
  cmp,
  packageVersion,
  authorInfo,
} from '@voxgig/sdkgen'


import { packageName } from './utility_ocaml'
import { secretsBuild } from './Config_ocaml'


// <name>.opam — opam package metadata (publish is declared pending in the
// model; the build itself is stock ocamlc via the Makefile and needs no opam
// packages). Twin of rust Cargo.toml, but the runtime is dependency-free so
// there is no depends list beyond the OCaml compiler.
//
// The secrets feature's build model is NOT emitted from here, unlike
// Package_rust's rustls dependency table: the Makefile reads the generated
// feature/secrets/feature.mk (Main_ocaml), which lists the vendored modules
// in dependency order and turns the OpenSSL binding on only when a plugin
// group needing a transport is active. What this manifest CAN state is the
// system dependency that binding introduces - `depexts`, opam's word for a
// distribution package - and it states it on exactly the same condition,
// read from the same helper, so the two cannot drift.
const Package = cmp(async function Package(props: any) {
  const ctx$ = props.ctx$
  const target = props.target
  const model = ctx$.model

  const secrets = secretsBuild(model, target)
  const depexts = null != secrets && secrets.tls
    ? `# The secrets feature's plugin groups (${secrets.tlsGroups.join(', ')}) bind
# OpenSSL through the vendored plugins/tls_stubs.c (-lssl -lcrypto), the
# one external dependency an ocaml SDK can have. Linked only because those
# groups are active - see feature/secrets/feature.mk.
depexts: [
  ["libssl-dev"] {os-family = "debian"}
  ["openssl-devel"] {os-family = "rhel"}
  ["openssl"] {os = "macos" & os-distribution = "homebrew"}
]
`
    : ''

  // WHO WROTE THIS PACKAGE. Per target, falling back to the model-wide value
  // and then to the publisher — so a manifest cannot go on naming Voxgig
  // while the model names someone else, which is exactly what the hardcoded
  // constant here did.
  const author = authorInfo(model, target.name)

  const pkg = packageName(model)

  File({ name: pkg + '.opam' }, () => {
    Content(`opam-version: "2.0"
name: "${pkg}"
version: "${packageVersion(model, target.name)}"
synopsis: "${model.const.Name} SDK for OCaml (generated by @voxgig/sdkgen)"
maintainer: "${author.name}"
authors: "${author.name}"
license: "MIT"
homepage: "https://voxgig.com"
bug-reports: "https://voxgig.com"
# The generated SDK is dependency-free: it compiles with the stock ocamlc
# (see the Makefile). No opam packages, no dune.
depends: [
  "ocaml" {>= "4.14"}
]
build: [
  [make "build"]
]
${depexts}`)
  })
})


export {
  Package
}
