
import {
  Content,
  File,
  cmp,
} from '@voxgig/sdkgen'


import { packageName } from './utility_ocaml'


// <name>.opam — opam package metadata (publish is declared pending in the
// model; the build itself is stock ocamlc via the Makefile and needs no opam
// packages). Twin of rust Cargo.toml, but the runtime is dependency-free so
// there is no depends list beyond the OCaml compiler.
const Package = cmp(async function Package(props: any) {
  const ctx$ = props.ctx$
  const model = ctx$.model

  const pkg = packageName(model)

  File({ name: pkg + '.opam' }, () => {
    Content(`opam-version: "2.0"
name: "${pkg}"
version: "0.0.1"
synopsis: "${model.const.Name} SDK for OCaml (generated by @voxgig/sdkgen)"
maintainer: "voxgig"
authors: "voxgig"
license: "MIT"
homepage: "https://voxgig.com"
bug-reports: "https://voxgig.com"
# The generated SDK is dependency-free: it compiles with the stock ocamlc
# (see the Makefile). No opam packages, no dune.
depends: [
  "ocaml" {>= "4.14"}
]
build: [
  [make "build"]
]
`)
  })
})


export {
  Package
}
