
import { cmp, Content, File } from '@voxgig/sdkgen'


// Emits test/readme_examples_test.ml — a structural gate over every ```ocaml
// fenced block in the three docs that ship ocaml examples:
//   - the root README.md (top-level, multi-language quick start)
//   - the per-language ocaml/README.md
//   - the per-language ocaml/REFERENCE.md
//
// DESIGN NOTE (mirrors ReadmeExamplesTest_rust): the py gate shells out to a
// python subprocess to COMPILE + EXECUTE every block. A faithful ocaml port
// would shell out to `ocamlc` against each extracted snippet — a large,
// environment-sensitive harness that cannot be authored safely without a build
// to validate it (and the generated SDK ships a dependency-free stock-ocamlc
// build, no doc-test tooling). This gate instead validates that every
// documented ocaml block is PRESENT and STRUCTURALLY well-formed (balanced
// delimiters, non-empty). It is a real, always-passing test that keeps the docs
// honest about block structure; upgrading it to a true compile gate (a temp
// project that `ocamlc`s each block against the generated SDK) is a follow-up.
// Missing docs are tolerated (a run may generate a subset of phases).
const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { target, ctx$: { model } } = props

  File({ name: 'readme_examples_test.' + target.ext }, () => {
    Content(`(* Structural gate over every \`\`\`ocaml block in the ${model.const.Name} SDK
 * docs (root README.md, ocaml/README.md, ocaml/REFERENCE.md). Generated by
 * @voxgig/sdkgen — do not edit by hand.
 *
 * Validates that each documented ocaml block is present, non-empty, and has
 * balanced delimiters. Missing docs are tolerated. See ReadmeExamplesTest_ocaml
 * for why this is a structural gate rather than a full compile harness. *)

open Testutil

let fence = "\`\`\`ocaml"
let close_fence = "\`\`\`"

let trim = String.trim

(* Read a whole file, or None when it is absent (a doc not generated). *)
let read_file (path : string) : string option =
  try Some (In_channel.with_open_text path In_channel.input_all)
  with Sys_error _ -> None

let split_lines (s : string) : string list = String.split_on_char '\\n' s

(* Extract the body of every \`\`\`ocaml ... \`\`\` fenced block from markdown. *)
let extract_ocaml_blocks (md : string) : string list =
  let blocks = ref [] in
  let cur = ref [] in
  let in_block = ref false in
  List.iter (fun line ->
      let t = trim line in
      if not !in_block then begin
        if t = fence then begin in_block := true; cur := [] end
      end
      else if t = close_fence then begin
        blocks := String.concat "\\n" (List.rev !cur) :: !blocks;
        in_block := false
      end
      else cur := line :: !cur)
    (split_lines md);
  List.rev !blocks

(* Balanced (), [], {} outside of string literals. Naive quote toggle: the
 * generated snippets never embed an escaped quote inside a string. *)
let is_balanced (block : string) : bool =
  let in_str = ref false in
  let depth = ref 0 in
  let ok = ref true in
  String.iter (fun c ->
      if c = '"' then in_str := not !in_str
      else if not !in_str then
        match c with
        | '(' | '[' | '{' -> incr depth
        | ')' | ']' | '}' -> decr depth; if !depth < 0 then ok := false
        | _ -> ())
    block;
  !ok && !depth = 0 && not !in_str

let docs = [
  ("root README", "../README.md");
  ("ocaml/README", "README.md");
  ("ocaml/REFERENCE", "REFERENCE.md");
]

let () =
  test "readme.ocaml_snippets_wellformed" (fun () ->
      let total = ref 0 in
      List.iter (fun (label, path) ->
          match read_file path with
          | None -> ()   (* doc not generated in this run — tolerate *)
          | Some src ->
            List.iteri (fun i block ->
                check (label ^ " block " ^ string_of_int (i + 1) ^ " non-empty")
                  (trim block <> "");
                check (label ^ " block " ^ string_of_int (i + 1) ^ " balanced delimiters")
                  (is_balanced block);
                incr total)
              (extract_ocaml_blocks src))
        docs;
      check "at least one ocaml code block across the docs" (!total > 0))
`)
  })
})


export {
  ReadmeExamplesTest
}
