
import { cmp, File, Content } from '@voxgig/sdkgen'


// Emits Tests/ProjectNameSDKTests/ReadmeExamplesTest.swift — a PRESENCE +
// STRUCTURE gate over every swift fenced block in the repository ROOT
// README.md, the per-language swift/README.md, AND swift/REFERENCE.md. It is a
// plain XCTestCase (no @testable import — it only reads the doc files off
// disk), resolved relative to the test file via #filePath.
//
// SCOPE NOTE (deliberate, documented): the Python/TS/Go equivalents EXECUTE and
// type-check every documented block. That is infeasible here — the generated
// Swift SDK compiles with SwiftPM only (no in-process Swift compiler wired into
// the test runtime), so a test cannot compile-and-run arbitrary doc snippets at
// test time. This gate therefore guarantees the weaker-but-real invariant that
// keeps the docs honest as the generator evolves:
//   1. PRESENCE: every scanned doc that exists holds at least one swift block
//      (nothing was dropped);
//   2. STRUCTURE: every swift block's braces / parens / brackets balance
//      (ignoring string literals and line comments), catching a truncated or
//      malformed generated snippet.
//
// The emitted Swift is written WITHOUT literal backticks (the fence marker is
// built at runtime as String(repeating: "\u{60}", count: 3)) so this TS
// template literal stays clean, and uses string concatenation instead of Swift
// interpolation to keep backslash-escaping in this template minimal.
const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { ctx$: { model } } = props

  const Name = model.const.Name

  File({ name: 'ReadmeExamplesTest.swift' }, () => {
    Content(`// ${Name} SDK — documentation swift-examples PRESENCE + STRUCTURE gate.
//
// GUARANTEE (see ReadmeExamplesTest_swift.ts for why this is a structure gate
// and not an execute gate): every swift example in the docs is accounted for.
// A dependency-free XCTestCase over every swift fenced code block in three
// documents:
//   - the repository ROOT README.md (one directory above the swift module),
//   - the per-language swift/README.md,
//   - the per-language swift/REFERENCE.md.
//
// Checks, PER DOCUMENT that exists:
//   1. PRESENCE: the doc holds at least one swift block.
//   2. STRUCTURE: every swift block's braces / parens / brackets balance, so a
//      truncated or malformed generated snippet fails loudly.
//
// GENERATED by @voxgig/sdkgen — do not edit by hand.

import XCTest
import Foundation

final class ReadmeExamplesTest: XCTestCase {
  private struct Doc { let label: String; let path: String }

  private let NL: Character = "\\n"

  // The triple-backtick fence, built at runtime so this source carries no
  // literal backticks.
  private var fence: String { String(repeating: "\\u{60}", count: 3) }

  // The three documents to scan, resolved relative to this test file.
  private func docs() -> [Doc] {
    let here = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent()   // ProjectNameSDKTests
      .deletingLastPathComponent()   // Tests
      .deletingLastPathComponent()   // swift (module dir)
    let project = here.deletingLastPathComponent()  // project (holds root README)
    return [
      Doc(label: "root README", path: project.appendingPathComponent("README.md").path),
      Doc(label: "swift README.md", path: here.appendingPathComponent("README.md").path),
      Doc(label: "swift REFERENCE.md", path: here.appendingPathComponent("REFERENCE.md").path),
    ]
  }

  // Extract every swift fenced block. Split on the triple-backtick fence:
  // odd-indexed segments are the inside of a fenced block (info string on the
  // first line, then the code). Only blocks whose info string is exactly
  // "swift" are returned.
  private func swiftBlocks(_ text: String) -> [String] {
    let parts = text.components(separatedBy: fence)
    var blocks: [String] = []
    var i = 1
    while i < parts.count {
      let seg = parts[i]
      let split = seg.split(separator: NL, maxSplits: 1, omittingEmptySubsequences: false)
      let first = split.first.map { String($0) } ?? ""
      let info = first.trimmingCharacters(in: .whitespaces)
      if info == "swift" {
        blocks.append(split.count > 1 ? String(split[1]) : "")
      }
      i += 2
    }
    return blocks
  }

  // True when every open/close delimiter balances, ignoring characters inside
  // string literals and line comments (a generated snippet never nests an
  // unbalanced delimiter outside those, and this catches truncation).
  private func balanced(_ block: String) -> Bool {
    var stack: [Character] = []
    var inString = false
    var escaped = false
    let chars = Array(block)
    var i = 0
    while i < chars.count {
      let ch = chars[i]
      if inString {
        if escaped { escaped = false }
        else if ch == "\\\\" { escaped = true }
        else if ch == "\\"" { inString = false }
        i += 1
        continue
      }
      if ch == "\\"" { inString = true; i += 1; continue }
      if ch == "/" && i + 1 < chars.count && chars[i + 1] == "/" {
        while i < chars.count && chars[i] != NL { i += 1 }
        continue
      }
      switch ch {
      case "(": stack.append(")")
      case "[": stack.append("]")
      case "{": stack.append("}")
      case ")", "]", "}":
        if stack.isEmpty || stack.removeLast() != ch { return false }
      default: break
      }
      i += 1
    }
    return stack.isEmpty && !inString
  }

  private func read(_ path: String) -> String? {
    return try? String(contentsOfFile: path, encoding: .utf8)
  }

  // PRESENCE: each doc that exists holds at least one swift block.
  func testDocExamplesPresent() {
    for doc in docs() {
      guard let text = read(doc.path) else { continue }
      let blocks = swiftBlocks(text)
      XCTAssertGreaterThan(blocks.count, 0,
        "expected at least one swift block in " + doc.label)
    }
  }

  // STRUCTURE: every swift block's delimiters balance.
  func testDocExamplesWellFormed() {
    var failures: [String] = []
    for doc in docs() {
      guard let text = read(doc.path) else { continue }
      let blocks = swiftBlocks(text)
      var balancedCount = 0
      for (i, b) in blocks.enumerated() {
        if balanced(b) { balancedCount += 1 }
        else { failures.append(doc.label + " swift block #" + String(i) + " has unbalanced delimiters") }
      }
      print("[readme-examples] " + doc.label + " swift blocks: total=" + String(blocks.count) + " balanced=" + String(balancedCount))
    }
    XCTAssertTrue(failures.isEmpty, failures.joined(separator: "; "))
  }
}
`)
  })
})


export {
  ReadmeExamplesTest
}
