
import {
  Content,
  File,
  cmp,
  configDefinition,
  configReprSetting,
  each,
  isAuthActive,
  isConfigData,
  resolveAuthIn,
  resolveAuthName,
  resolveAuthPrefix,
} from '@voxgig/sdkgen'


import {
  KIT,
  Model,
  getModelPath,
} from '@voxgig/apidef'


import {
  cljStringChunks,
  formatCljValue,
} from './utility_clojure'


import {
  extraFeatures,
  pluginRequires,
} from './featureextra_clojure'


// sdk/config.clj: make-config builds the embedded API model as a vendored
// struct value node (LinkedHashMap/ArrayList) via vs/jm and vs/jt. The whole
// config is assembled as a JSON-shaped object and rendered once through
// formatCljValue (byte-stable; each() sorted-key iteration + sorted map keys).
// N-feature-safe: an empty feature/entity map renders as (vs/jm).
const Config = cmp(async function Config(props: any) {
  const ctx$ = props.ctx$
  const target = props.target

  const model: Model = ctx$.model

  const { def: config, json: baseJson } = configDefinition(model, target.name)

  const authIn = resolveAuthIn(model)
  const authName = resolveAuthName(model)
  const configAuth = config?.options?.auth
  if (null != configAuth) {
    if ('header' !== authIn) { configAuth.in = authIn }
    if ('Authorization' !== authName) { configAuth.name = authName }
  }
  const configJson = JSON.stringify(config)
  assertHeaderIdentity(configJson, baseJson, authIn, authName)

  const asData = isConfigData(configJson, configReprSetting(model))

  const extra = extraFeatures(model, target)
  const { requires: plugreq, plugins: featplugins } = pluginRequires(model, target)

  const wireRequires =
    plugreq.map((r: any) => `\n            [${r.ns} :as ${r.alias}]`).join('') +
    extra.map((f: any) => `\n            [${f.ns} :as fx-${f.name}]`).join('')

  const wireBlock = `
(def feature-plugins
  {${Object.keys(featplugins).sort()
      .map((fname: string) =>
        `"${fname}" [${featplugins[fname].join(' ')}]`).join('\n   ')}})

(def feature-extra
  {${extra.map((f: any) =>
        `"${f.name}" (fn [] (${f.ns}/${f.ctor} (get feature-plugins "${f.name}")))`)
      .join('\n   ')}})
`

  File({ name: 'config.clj' }, () => {

    if (asData) {
      Content(`;; ${model.const.Name} SDK configuration (generated by @voxgig/sdkgen).
;;
;; THE API MODEL, EMBEDDED AS DATA (sdkgen rung L1). Emitted only above a size
;; threshold, or when main.kit.config.repr pins it: for a small model the
;; literal is smaller and far easier to read when debugging.
(ns sdk.config
  (:require [sdk.core :as core]${wireRequires}))

(def ^:private config-data
  (str ${cljStringChunks(configJson).map((c: string) => JSON.stringify(c)).join('\n       ')}))

(defn make-config []
  (core/json-parse config-data))
${wireBlock}`)
      return
    }

    Content(`;; ${model.const.Name} SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]${wireRequires}))

(defn make-config []
  ${formatCljValue(config, 1)})
${wireBlock}`)
  })
})


function assertHeaderIdentity(now: string, before: string, authIn: string, authName: string) {
  const defaults = 'header' === authIn && 'Authorization' === authName
  if (defaults && now !== before) {
    throw new Error('Config_clojure: the auth overlay changed a ' +
      'header/Authorization config, which must regenerate byte-identical')
  }
}


export {
  Config
}
