
import {
  cmp, each,
  File, Content, Copy, Folder,
} from '@voxgig/sdkgen'


import type {
  ModelEntity
} from '@voxgig/apidef'


import {
  KIT,
  getModelPath
} from '@voxgig/apidef'


import { Package } from './Package_clojure'
import { Config } from './Config_clojure'
import { Gitignore } from './Gitignore_clojure'
import { MainEntity } from './MainEntity_clojure'


const Main = cmp(async function Main(props: any) {

  const { target } = props
  const { model } = props.ctx$

  const entity: ModelEntity = getModelPath(model, `main.${KIT}.entity`)

  Package({ target })

  Gitignore({})

  // Copy tm/clojure verbatim (runtime under src/, the test suite under test/,
  // Makefile/LICENSE/VERSION). The feature-add scaffolding under src/feature
  // is excluded — the clojure target does not use per-feature custom source.
  Copy({
    from: 'tm/' + target.name,
    exclude: [/src\/feature\//],
    replace: {
      ...props.ctx$.stdrep,
    }
  })

  // Generated config namespace (src/sdk/config.clj).
  Folder({ name: 'src' }, () => {
    Folder({ name: 'sdk' }, () => {
      Config({ target })
    })
  })

  // Public API namespace (src/sdk/api.clj): entity accessors plus the
  // re-exported client constructors.
  Folder({ name: 'src' }, () => {
    Folder({ name: 'sdk' }, () => {
      File({ name: 'api.' + target.ext }, () => {

        let requires = ''
        each(entity, (e: any) => {
          requires += `\n            [sdk.entity.${e.name} :as e-${e.name}]`
        })

        Content(`;; ${model.const.Name} SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]${requires}))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def prepare client/prepare)
(def options-map client/options-map)
`)

        each(entity, (e: any) => {
          MainEntity({ target, entity: e })
        })
      })
    })
  })

})


export {
  Main
}
