
import {
  cmp, each,
  File, Content, Copy, Folder,
  pluginExcludes,
} from '@voxgig/sdkgen'


import type {
  ModelEntity
} from '@voxgig/apidef'


import {
  KIT,
  getModelPath
} from '@voxgig/apidef'


import { extraFeatures } from './featureextra_clojure'
import { Package } from './Package_clojure'
import { Config } from './Config_clojure'
import { Schema } from './Schema_clojure'
import { Gitignore } from './Gitignore_clojure'
import { MainEntity } from './MainEntity_clojure'
import { PrepareAuth } from './PrepareAuth_clojure'


const CONTAINED = ['secrets']


const Main = cmp(async function Main(props: any) {

  const { target } = props
  const { model } = props.ctx$

  const entity: ModelEntity = getModelPath(model, `main.${KIT}.entity`)

  Package({ target })

  Gitignore({})

  const featureGate = extraFeatures(model, target).map((f: any) => f.name)
  const containerExcludes = CONTAINED
    .filter((name: string) => !featureGate.includes(name))
    .flatMap((name: string) => [
      new RegExp('(^|/)feature/' + name + '/'),
      new RegExp('(^|/)test/sdk/test/feature/' + name + '\\.clj$'),
    ])

  Copy({
    from: 'tm/' + target.name,
    exclude: [/src\/feature\//, ...containerExcludes, ...pluginExcludes(model)],
    replace: {
      ...props.ctx$.stdrep,
    }
  })

  Folder({ name: 'src' }, () => {
    Folder({ name: 'sdk' }, () => {
      Config({ target })
      Schema({ target })
      PrepareAuth({ target })
    })
  })

  // Public API namespace (src/sdk/api.clj): entity accessors plus the
  // re-exported client constructors.
  Folder({ name: 'src' }, () => {
    Folder({ name: 'sdk' }, () => {
      File({ name: 'api.' + target.ext }, () => {

        let requires = ''
        each(entity, (e: any) => {
          requires += `\n            [sdk.entity.${e.name} :as e-${e.name}]`
        })

        Content(`;; ${model.const.Name} SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]${requires}))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def graphql client/graphql)
(def prepare client/prepare)
(def options-map client/options-map)
`)

        each(entity, (e: any) => {
          MainEntity({ target, entity: e })
        })
      })
    })
  })

})


export {
  Main
}
