
import {
  Content,
  File,
  cmp,
} from '@voxgig/sdkgen'


import type {
  Model,
} from '@voxgig/apidef'


import {
  extraFeatures,
} from './featureextra_clojure'


const Package = cmp(async function Package(props: any) {
  const ctx$ = props.ctx$
  const target = props.target
  const model: Model = ctx$.model

  const roots = ['src', ...extraFeatures(model, target).map((f: any) => f.path)]

  File({ name: 'deps.edn' }, () => {
    Content(`;; ${model.const.Name} SDK for Clojure (generated by @voxgig/sdkgen).
{:paths [${roots.map((r: string) => JSON.stringify(r)).join(' ')}]
 :deps {org.clojure/clojure {:mvn/version "1.12.5"}}
 :aliases
 {:test
  {:extra-paths ["test" "test/vendor/omni"]
   :main-opts ["-m" "sdk.test-runner"]}
  :test-compile
  {:extra-paths ["test" "test/vendor/omni"]
   :main-opts ["-e" "(require 'sdk.test-runner)(println :ok)"]}}}
`)
  })
})


export {
  Package
}
