
import {
  Content,
  File,
  cmp,
} from '@voxgig/sdkgen'


import type {
  Model,
} from '@voxgig/apidef'


// deps.edn — the tools.deps manifest. The vendored voxgig struct port needs no
// external dependency; the library itself only needs org.clojure/clojure. The
// tools.deps shim used to run the tests supports `-M:alias` reading :paths /
// :extra-paths / :main-opts, but NOT per-alias :extra-deps, so every dependency
// lives at the top-level :deps.
const Package = cmp(async function Package(props: any) {
  const ctx$ = props.ctx$
  const model: Model = ctx$.model

  File({ name: 'deps.edn' }, () => {
    Content(`;; ${model.const.Name} SDK for Clojure (generated by @voxgig/sdkgen).
{:paths ["src"]
 :deps {org.clojure/clojure {:mvn/version "1.12.5"}}
 :aliases
 {:test
  {:extra-paths ["test"]
   :main-opts ["-m" "sdk.test-runner"]}
  :test-compile
  {:extra-paths ["test"]
   :main-opts ["-e" "(require 'sdk.test-runner)(println :ok)"]}}}
`)
  })
})


export {
  Package
}
