import {
  Content,
  File,
  cmp,
  isHttpBasicAuth,
  resolveAuthIn,
  resolveAuthName,
  resolveAuthPrefix,
} from '@voxgig/sdkgen'


import {
  KIT,
  Model,
  getModelPath,
} from '@voxgig/apidef'


const PrepareAuth = cmp(async function PrepareAuth(props: any) {
  const { target } = props
  const model: Model = props.ctx$.model

  File({ name: 'prepare_auth.' + target.ext }, () => {
    Content(render({
      Name: model.const.Name,
      active: authSwitchedOn(model),
      where: resolveAuthIn(model),
      name: resolveAuthName(model),
      basic: isHttpBasicAuth(model),
      prefix: resolveAuthPrefix(model),
    }))
  })
})


type AuthSpec = {
  Name: string
  active: boolean
  where: string
  name: string
  basic: boolean
  prefix: string
}


function render(spec: AuthSpec): string {
  const head = `;; ${spec.Name} SDK: where the credential goes (generated by @voxgig/sdkgen).
;;
;; PART OF THE sdk.core NAMESPACE, not a namespace of its own: core.clj reads
;; this file with \`(load "prepare_auth")\` at the point u-prepare-auth used to
;; be defined, so oget / ctx-error / client-options-map are already in scope
;; and base-utility-map's \`:prepare-auth u-prepare-auth\` still resolves.
(in-ns 'sdk.core)

`

  if (!spec.active) return renderInactive(spec, head)

  if ('query' === spec.where) return renderQuery(spec, head)
  if ('cookie' === spec.where) return renderCookie(spec, head)

  return renderHeader(spec, head)
}


function headerName(name: string): string {
  return String(name).toLowerCase()
}


function headerAuthConst(spec: AuthSpec): string {
  return 'header' === spec.where ? headerName(spec.name) : 'authorization'
}


function renderHeader(spec: AuthSpec, head: string): string {
  return head + `(def HEADER-AUTH ${cljstr(headerName(spec.name))})
(def OPTION-APIKEY "apikey")
` + (spec.basic ? `(def OPTION-SECRET "secret")
` : '') + `(def NOT-FOUND "__NOTFOUND__")

(defn u-prepare-auth [ctx]
  (let [spec (oget ctx :spec)]
    (if (nil? spec) [nil (ctx-error ctx "auth_no_spec" "Expected context spec property to be defined.")]
        (let [headers (oget spec :headers)
              options (client-options-map (oget ctx :client))]
          (if (nil? (vs/getprop options "auth"))
            ;; Public APIs that need no auth omit the options.auth block entirely.
            (do (vs/delprop headers HEADER-AUTH) [spec nil])
            (let [apikey (vs/getprop options OPTION-APIKEY NOT-FOUND)]
${spec.basic ? basicBlock() : headerPlace(14)}
              [spec nil]))))))
`
}


function headerPlace(col: number): string {
  const p = ' '.repeat(col)
  return `${p}(if (or (nil? apikey) (and (string? apikey) (or (= apikey NOT-FOUND) (= apikey ""))))
${p}  (vs/delprop headers HEADER-AUTH)
${p}  (let [auth-prefix (or (vs/getpath options "auth.prefix") "")
${p}        apikey-val (if (string? apikey) apikey "")]
${p}    (.put ^java.util.Map headers HEADER-AUTH
${p}          (if (= auth-prefix "") apikey-val (str auth-prefix " " apikey-val)))))`
}


function basicBlock(): string {
  return `              ;; True HTTP Basic Auth needs TWO credentials, base64-joined - a
              ;; single token in the header (the branch below) can never
              ;; authenticate against an API that actually checks
              ;; \`Authorization: Basic base64(user:pass)\`.
              (if (= true (vs/getpath options "auth.basic"))
                (let [secret (vs/getprop options OPTION-SECRET NOT-FOUND)
                      missing? (fn [v] (or (nil? v)
                                           (and (string? v) (or (= v NOT-FOUND) (= v "")))))]
                  (if (or (missing? apikey) (missing? secret))
                    (vs/delprop headers HEADER-AUTH)
                    (let [auth-prefix (or (vs/getpath options "auth.prefix") "")
                          b64 (.encodeToString (java.util.Base64/getEncoder)
                                               (.getBytes ^String (str apikey ":" secret) "UTF-8"))]
                      (.put ^java.util.Map headers HEADER-AUTH
                            (if (= auth-prefix "") b64 (str auth-prefix " " b64))))))
${headerPlace(16)})`
}


function renderQuery(spec: AuthSpec, head: string): string {
  return head + `;; Retained for feature/secrets, whose re-auth writes an Authorization
;; header; this SDK's own credential is a query parameter (see QUERY-AUTH).
(def HEADER-AUTH ${cljstr(headerAuthConst(spec))})
(def QUERY-AUTH ${cljstr(spec.name)})
(def OPTION-APIKEY "apikey")
(def NOT-FOUND "__NOTFOUND__")

(defn u-prepare-auth [ctx]
  (let [spec (oget ctx :spec)]
    (if (nil? spec) [nil (ctx-error ctx "auth_no_spec" "Expected context spec property to be defined.")]
        (let [query (oget spec :query)
              options (client-options-map (oget ctx :client))]
          (if (nil? (vs/getprop options "auth"))
            ;; Public APIs that need no auth omit the options.auth block entirely.
            (do (vs/delprop query QUERY-AUTH) [spec nil])
            (let [apikey (vs/getprop options OPTION-APIKEY NOT-FOUND)]
              (if (or (nil? apikey) (and (string? apikey) (or (= apikey NOT-FOUND) (= apikey ""))))
                (vs/delprop query QUERY-AUTH)
                (let [apikey-val (if (string? apikey) apikey "")]
                  ;; NO PREFIX IN A QUERY STRING. \`?${spec.name}=Bearer%20abc\` is not a
                  ;; thing any API reads: the prefix is a header convention, so it is
                  ;; dropped here deliberately rather than silently concatenated.
                  (.put ^java.util.Map query QUERY-AUTH apikey-val)))
              [spec nil]))))))
`
}


function renderCookie(spec: AuthSpec, head: string): string {
  return head + `;; Retained for feature/secrets, whose re-auth writes an Authorization
;; header; this SDK's own credential is a cookie (see COOKIE-AUTH).
(def HEADER-AUTH ${cljstr(headerAuthConst(spec))})
(def HEADER-COOKIE "cookie")
(def COOKIE-AUTH ${cljstr(spec.name)})
(def OPTION-APIKEY "apikey")
(def NOT-FOUND "__NOTFOUND__")

;; The cookie header minus our own pair, every other cookie left untouched.
(defn- cookies-without-cred [headers]
  (let [existing (vs/getprop headers HEADER-COOKIE)]
    (if (or (not (string? existing)) (= "" existing))
      ""
      (str/join "; "
                (remove (fn [piece]
                          (or (= "" piece)
                              (= COOKIE-AUTH piece)
                              (str/starts-with? piece (str COOKIE-AUTH "="))))
                        (map str/trim (str/split existing #";")))))))

;; Set (a string) or remove (nil) our pair, leaving the rest in place.
(defn- apply-cookie! [headers value]
  (let [rest (cookies-without-cred headers)]
    (if (nil? value)
      (if (= "" rest)
        (vs/delprop headers HEADER-COOKIE)
        (.put ^java.util.Map headers HEADER-COOKIE rest))
      (let [pair (str COOKIE-AUTH "=" value)]
        (.put ^java.util.Map headers HEADER-COOKIE
              (if (= "" rest) pair (str rest "; " pair)))))))

(defn u-prepare-auth [ctx]
  (let [spec (oget ctx :spec)]
    (if (nil? spec) [nil (ctx-error ctx "auth_no_spec" "Expected context spec property to be defined.")]
        (let [headers (oget spec :headers)
              options (client-options-map (oget ctx :client))]
          (if (nil? (vs/getprop options "auth"))
            ;; Public APIs that need no auth omit the options.auth block entirely.
            (do (apply-cookie! headers nil) [spec nil])
            (let [apikey (vs/getprop options OPTION-APIKEY NOT-FOUND)]
              (if (or (nil? apikey) (and (string? apikey) (or (= apikey NOT-FOUND) (= apikey ""))))
                (apply-cookie! headers nil)
                ;; NO PREFIX IN A COOKIE either - a cookie carries a bare
                ;; \`name=value\` pair, not a header's scheme-prefixed credential.
                (apply-cookie! headers (if (string? apikey) apikey "")))
              [spec nil]))))))
`
}


// NO AUTH AT ALL — the PROJECT switched it off (see authSwitchedOn for why
// only an explicit switch counts). The SDK gets a u-prepare-auth that is
// honest about it rather than one that deletes a header nobody set. The
// function stays because core.clj's u-make-spec calls it unconditionally and
// base-utility-map binds it unconditionally.
function renderInactive(spec: AuthSpec, head: string): string {
  return head + `;; This SDK is configured with authentication off
;; (main.kit.config.auth.active: false), so there is no credential to place.
;; HEADER-AUTH remains part of sdk.core's public surface because
;; feature/secrets reads core/HEADER-AUTH.
(def HEADER-AUTH ${cljstr(headerAuthConst(spec))})
(def OPTION-APIKEY "apikey")
(def NOT-FOUND "__NOTFOUND__")

(defn u-prepare-auth [ctx]
  (let [spec (oget ctx :spec)]
    (if (nil? spec) [nil (ctx-error ctx "auth_no_spec" "Expected context spec property to be defined.")]
        [spec nil])))
`
}


function authSwitchedOn(model: any): boolean {
  const auth = getModelPath(model, `main.${KIT}.config.auth`,
    { only_active: false, required: false })
  return !(null != auth && false === auth.active)
}


function cljstr(s: string): string {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'
}


export {
  PrepareAuth
}
