import {
  cmp,
  each,
  File,
  Content,
  isAuthSuppressed,
  isHttpBasicAuth,
  resolveAuthIn,
  resolveAuthName,
} from '@voxgig/sdkgen'


// The canary sweep, the clojure port of TestClean_ts.ts: see that component.
const TestClean = cmp(function TestClean(props: any) {
  const { model } = props.ctx$
  const { target, entity } = props

  const auth = {
    suppressed: isAuthSuppressed(model),
    where: resolveAuthIn(model),
    name: 'header' === resolveAuthIn(model)
      ? resolveAuthName(model).toLowerCase() : resolveAuthName(model),
    basic: isHttpBasicAuth(model),
  }

  File({ name: 'clean.' + target.ext }, () => Content(render(model, entity, auth)))
})


const OP_ORDER: Record<string, number> = { list: 0, load: 1 }
const OPS = ['list', 'load', 'create', 'update', 'remove']


// The operations to try, list and load first: a required path parameter is
// what usually stops a candidate, and the read ops need none.
function candidates(entity: any[]): string {
  const rows: { rank: number, text: string }[] = []
  each(entity, (e: any) => {
    for (const op of Object.keys(e.op || {})) {
      if (!OPS.includes(op)) continue
      rows.push({
        rank: OP_ORDER[op] ?? 2,
        text: `   {:name "${e.name}.${op}"
    :accessor (fn [sdk] (api/${e.name} sdk nil))
    :op (fn [ent ctrl] (e-${e.name}/${op} ent (vs/jm) ctrl))}`,
      })
    }
  })
  rows.sort((a, b) => a.rank - b.rank)
  return rows.map((r) => r.text).join('\n')
}


function render(model: any, entity: any[], auth: {
  suppressed: boolean, where: string, name: string, basic: boolean
}): string {
  let requires = ''
  each(entity, (e: any) => {
    requires += `\n            [sdk.entity.${e.name} :as e-${e.name}]`
  })

  return `;; ${model.const.Name} SDK canary sweep (generated by @voxgig/sdkgen).
;;
;; Every credential slot holds a distinctive value, every diagnostic feature
;; this SDK ships is switched on with a capturing sink, a real operation runs
;; through every outcome, and every string that leaves the SDK is searched
;; for the canaries and their encoded forms. It also proves its own
;; sensitivity: with clean switched off the canary MUST show.
(ns sdk.test.clean
  (:require [sdk.api :as api]
            [sdk.core :as core]
            [sdk.test.feature :as feature]
            [sdk.testutil :as t]
            [voxgig.struct :as vs]
            [clojure.string :as str]${requires}))

;; Generated: the credential's wire placement is fixed when the SDK is built.
(def AUTH {:suppressed ${auth.suppressed} :where ${cljstr(auth.where)}
           :name ${cljstr(auth.name)} :basic ${auth.basic}})

(def CANARY {:apikey "CANARY-APIKEY-k9x2m7q4p1"
             :secret "CANARY-SECRET-w3e8r5t2y6"
             :header "CANARY-HEADER-z1x4c7v0b3"
             :value "CANARY-VALUE-n5m8b2v9c4"})

(def MASK "[redacted]")

(defn- b64 [^String s]
  (.encodeToString (java.util.Base64/getEncoder) (.getBytes s "UTF-8")))

;; Every form a canary can travel in.
(def FORMS
  (vec (concat (mapcat (fn [v] [v (b64 v) (vs/escurl v)]) (vals CANARY))
               [(b64 (str (:apikey CANARY) ":" (:secret CANARY)))])))

(defn- leaks [^String text] (filterv (fn [^String f] (.contains text f)) FORMS))

;; Header maps keep the caller's spelling; the assertion should not care.
(defn- header [m name]
  (when (instance? java.util.Map m)
    (some (fn [k] (when (= (str/lower-case (str k)) (str/lower-case (str name)))
                    (.get ^java.util.Map m k)))
          (vec (.keySet ^java.util.Map m)))))

;; Every default print and serialisation of a value, as a sink each.
(defn- forms [name val]
  (let [out (atom [])
        push (fn [kind f]
               (try (swap! out conj {:name (str name ":" kind) :text (str (f))})
                    (catch Throwable _ nil)))]
    (push "pr" #(pr-str val))
    (push "str" #(str val))
    (push "json" #(vs/jsonify val))
    (when (instance? Throwable val)
      (push "message" #(ex-message val))
      (push "data" #(pr-str (ex-data val)))
      (push "map" #(pr-str (Throwable->map val)))
      (push "sdk-pr" #(pr-str (core/ex->sdk val)))
      (push "sdk-json" #(vs/jsonify (core/err->data (core/ex->sdk val))))
      (push "stack" #(let [sw (java.io.StringWriter.)]
                       (.printStackTrace ^Throwable val (java.io.PrintWriter. sw))
                       (str sw))))
    @out))

;; Captures the serialised context from inside the pipeline: what a hook
;; author would hand to a logger.
(defn- capture-feature [sinks]
  (let [cap (fn [hook] (fn [ctx] (swap! sinks into (forms (str "ctx@" hook) ctx))))]
    (atom {:name "capture" :active true :version "0.0.1" :_options nil
           "init" (fn [_ctx _opts] nil)
           "PreRequest" (cap "PreRequest")
           "PreResponse" (cap "PreResponse")
           "PreUnexpected" (cap "PreUnexpected")})))

(defn- response [status data headers]
  (let [h (vs/jm "content-type" "application/json")]
    (doseq [[k v] headers] (.put ^java.util.Map h k v))
    (vs/jm "status" status "statusText" (if (< status 400) "OK" "ERR")
           "headers" h "body" (vs/jsonify data) "json" (fn [] data))))

(def SCENARIOS
  [{:name "ok"
    :respond (fn [_url _fd] [(response 200 (vs/jm "id" "i1" "name" "n1")
                                       {"x-session-token" "RESP-TOKEN-a1b2c3d4e5"}) nil])}
   {:name "notfound"
    :respond (fn [_url _fd] [(response 404 (vs/jm "error" "no such record") {}) nil])}
   {:name "server"
    :respond (fn [_url _fd] [(response 500 (vs/jm "error" "boom") {}) nil])}
   {:name "transport"
    :respond (fn [url _fd] [nil (core/make-error-obj "transport"
                                                     (str "socket hang up (URL was: \\"" url "\\")"))])}
   {:name "notjson"
    :respond (fn [_url _fd] [(vs/jm "status" 200 "statusText" "OK" "headers" (vs/jm)
                                    "body" "<html>"
                                    "json" (fn [] (throw (RuntimeException. "Unexpected token < in JSON")))) nil])}])

(defn- make-sdk [scenario sinks cleanopts]
  (let [capture (fn [name] (fn [rec] (swap! sinks into (forms name rec))))
        feature (vs/jm)
        on (fn [name & kvs] (when (feature/feature-present? name)
                              (.put ^java.util.Map feature name (apply vs/jm "active" true kvs))))]
    (on "log" "logger" (capture "log"))
    (on "debug" "onEntry" (capture "debug"))
    (on "audit" "sink" (capture "audit"))
    (on "telemetry" "exporter" (capture "telemetry"))
    (on "cost" "sink" (capture "cost"))
    (on "metrics")
    (on "clienttrack")
    (let [clean (vs/jm "values" (:value CANARY))]
      (doseq [[k v] (or cleanopts {})] (.put ^java.util.Map clean k v))
      (api/make-sdk (vs/jm "apikey" (:apikey CANARY) "secret" (:secret CANARY)
                           "headers" (vs/jm "X-Custom-Token" (:header CANARY))
                           "clean" clean
                           "feature" feature
                           "extend" (vs/jt (capture-feature sinks))
                           "utility" (vs/jm "fetcher" (fn [_fctx url fd] ((:respond scenario) url fd))))))))

;; The operations this SDK generated, read ops first.
(def CANDIDATES
  [
${candidates(entity)}
   ])

;; The first operation that completes against a plain 200 with no arguments.
(defn- usable-op []
  (let [plain (api/make-sdk (vs/jm "apikey" (:apikey CANARY)
                                   "utility" (vs/jm "fetcher" (fn [_ _ _] [(response 200 (vs/jm "id" "i1") {}) nil]))))]
    (some (fn [c] (try ((:op c) ((:accessor c) plain) (vs/jm)) c (catch Throwable _ nil)))
          CANDIDATES)))

(defn- drive [sdk target ctrl sinks]
  (let [ent ((:accessor target) sdk)
        [out err] (try [((:op target) ent ctrl) nil] (catch Throwable e [nil e]))
        explain (vs/getprop ctrl "explain")]
    (when err (swap! sinks into (forms "error" err)))
    (when (some? out) (swap! sinks into (forms "result" out)))
    (when (some? explain) (swap! sinks into (forms "explain" explain)))
    err))

(defn run [rec]
  (t/run-check rec "clean-no-credential-leaves-the-sdk"
    (fn []
      (let [target (usable-op)]
        (t/is-some target "no operation completes without arguments; nothing to sweep")
        (let [sinks (atom []) errors (atom {}) explains (atom {})]
          (doseq [scenario SCENARIOS
                  variant [{:name "throw" :ctrl (fn [] (vs/jm))}
                           {:name "explain" :ctrl (fn [] (vs/jm "explain" (vs/jm)))}
                           {:name "nothrow" :ctrl (fn [] (vs/jm "throw" false "explain" (vs/jm)))}]]
            (let [sdk (make-sdk scenario sinks nil)
                  ctrl ((:ctrl variant))
                  err (drive sdk target ctrl sinks)
                  key (str (:name scenario) "/" (:name variant))]
              (when err (swap! errors assoc key err))
              (when-let [ex (vs/getprop ctrl "explain")] (swap! explains assoc key ex))
              (swap! sinks into (forms "sdk" sdk))
              (swap! sinks conj {:name "sdk:slots" :text (pr-str (into {} sdk))})))
          (let [leaked (filterv (fn [s] (seq (leaks (:text s)))) @sinks)]
            (println (str "clean: swept " (count @sinks) " surface(s), " (count leaked) " leak(s)"))
            (t/is-eq (count leaked) 0
                     (str "credential leaked through: "
                          (str/join "; " (map (fn [s] (str (:name s) " [" (str/join ", " (leaks (:text s))) "]"))
                                              leaked)))))
          ;; The positive half: the slot the credential travelled in is
          ;; masked, and an unregistered token in a response header is masked
          ;; by name.
          (let [notfound (get @errors "notfound/throw")
                sdkerr (core/ex->sdk notfound)]
            (t/is-some notfound "the 404 scenario must throw")
            (t/is-some sdkerr "the 404 error is an SDK error")
            (t/is-eq (vs/getprop (:result sdkerr) "status") 404 "status 404")
            (let [spec (:spec sdkerr)]
              (when-not (:suppressed AUTH)
                (cond
                  (= "query" (:where AUTH))
                  (t/is-eq (header (vs/getprop spec "query") (:name AUTH)) MASK "query credential masked")
                  (= "cookie" (:where AUTH))
                  (t/is-true (str/includes? (str (header (vs/getprop spec "headers") "cookie")) MASK)
                             (str "cookie: " (header (vs/getprop spec "headers") "cookie")))
                  :else
                  (t/is-true (str/ends-with? (str (header (vs/getprop spec "headers") (:name AUTH))) MASK)
                             (str (:name AUTH) ": " (header (vs/getprop spec "headers") (:name AUTH))))))
              (t/is-eq (header (vs/getprop spec "headers") "x-custom-token") MASK "custom token header masked")))
          (let [explained (get @explains "ok/explain")
                result (vs/getprop explained "result")]
            (t/is-some result "the explain record should carry the result")
            (t/is-eq (header (vs/getprop result "headers") "x-session-token") MASK "response token masked"))))))

  (t/run-check rec "clean-the-sweep-can-see-a-leak"
    (fn []
      (let [target (usable-op)
            sinks (atom [])
            sdk (make-sdk (nth SCENARIOS 1) sinks {"active" false})
            err (drive sdk target (vs/jm) sinks)]
        (t/is-some target "no operation completes without arguments")
        (t/is-some err "the 404 scenario must throw")
        (t/is-true (some (fn [s] (seq (leaks (:text s)))) @sinks)
                   "with clean off, nothing showed the canary: the sweep is blind")
        (when-not (:suppressed AUTH)
          (let [text (pr-str (:spec (core/ex->sdk err)))]
            (t/is-true (or (str/includes? text (:apikey CANARY))
                           (str/includes? text (b64 (str (:apikey CANARY) ":" (:secret CANARY)))))
                       "the raw spec should carry the credential when clean is off"))))))
  nil)
`
}


function cljstr(s: string): string {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'
}


export {
  TestClean
}
