import {
  cmp,
  each,
  File,
  Content,
  isAuthSuppressed,
  isHttpBasicAuth,
  resolveAuthIn,
  resolveAuthName,
} from '@voxgig/sdkgen'


import {
  elixirString,
} from './utility_elixir'


// The canary sweep, the elixir port of TestClean_ts.ts: see that component.
const TestClean = cmp(function TestClean(props: any) {
  const { model } = props.ctx$
  const { entity } = props

  const auth = {
    suppressed: isAuthSuppressed(model),
    where: resolveAuthIn(model),
    name: 'header' === resolveAuthIn(model)
      ? resolveAuthName(model).toLowerCase() : resolveAuthName(model),
    basic: isHttpBasicAuth(model),
  }

  File({ name: 'clean_test.exs' }, () => Content(render(model, entity, auth)))
})


const OP_ORDER: Record<string, number> = { list: 0, load: 1 }
const OPS = ['list', 'load', 'create', 'update', 'remove']


// The operations to try, list and load first: a required path parameter is
// what usually stops a candidate, and the read ops need none.
function candidates(Name: string, entity: any[]): string {
  const rows: { rank: number, text: string }[] = []
  each(entity, (e: any) => {
    for (const op of Object.keys(e.op || {})) {
      if (!OPS.includes(op)) continue
      rows.push({
        rank: OP_ORDER[op] ?? 2,
        text: `      {${elixirString(e.name + '.' + op)}, fn sdk -> ${Name}.${e.name}(sdk) end,
       fn ent, ctrl -> ${Name}.Entity.${e.Name}.${op}(ent, S.jm([]), ctrl) end}`,
      })
    }
  })
  rows.sort((a, b) => a.rank - b.rank)
  return rows.map((r) => r.text).join(',\n')
}


function render(model: any, entity: any[], auth: {
  suppressed: boolean, where: string, name: string, basic: boolean
}): string {
  const Name = model.const.Name

  return `# ${Name} SDK canary sweep (generated by @voxgig/sdkgen).
#
# Every credential slot holds a distinctive value, every diagnostic feature
# this SDK ships is switched on with a capturing sink, a real operation runs
# through every outcome, and every string that leaves the SDK is searched for
# the canaries and their encoded forms. It also proves its own sensitivity:
# with clean switched off the canary MUST show.
#
# A struct node inspects as a handle, so the SDK's own records (the error's
# result and spec, the explain record, every sink record, the context's
# to_data) are also read through the struct JSON; a raw client, entity or
# context node is not, since that is a dump of the heap rather than a
# serialisation the SDK performs.

defmodule ${Name}.CleanTest do
  use ExUnit.Case

  alias Voxgig.Struct, as: S
  alias ${Name}.Helpers, as: H
  alias ${Name}.FeatureHarness, as: FH

  # Generated: the credential's wire placement is fixed when the SDK is built.
  @auth %{suppressed: ${auth.suppressed}, where: ${elixirString(auth.where)},
          name: ${elixirString(auth.name)}, basic: ${auth.basic}}

  @canary %{
    apikey: "CANARY-APIKEY-k9x2m7q4p1",
    secret: "CANARY-SECRET-w3e8r5t2y6",
    header: "CANARY-HEADER-z1x4c7v0b3",
    value: "CANARY-VALUE-n5m8b2v9c4"
  }

  @mask "[redacted]"

  # Every form a canary can travel in.
  defp forms_of do
    Enum.flat_map(Map.values(@canary), fn v -> [v, Base.encode64(v), S.escurl(v)] end) ++
      [Base.encode64(@canary.apikey <> ":" <> @canary.secret)]
  end

  defp leaks(text), do: Enum.filter(forms_of(), &String.contains?(text, &1))

  # Header maps keep the caller's spelling; the assertion should not care.
  defp header(m, name) do
    if S.ismap(m) do
      Enum.find_value(H.entries(m), fn {k, v} ->
        if String.downcase(to_string(k)) == String.downcase(name), do: v
      end)
    end
  end

  defp push(name, kind, f) do
    try do
      [%{name: name <> ":" <> kind, text: to_string(f.())}]
    rescue
      _ -> []
    catch
      _, _ -> []
    end
  end

  # Every default print of a value, as a sink each.
  defp forms(name, val) do
    push(name, "inspect", fn -> inspect(val, limit: :infinity, printable_limit: :infinity) end) ++
      push(name, "raw", fn -> inspect(val, structs: false, limit: :infinity, printable_limit: :infinity) end) ++
      if is_exception(val) do
        push(name, "message", fn -> Exception.message(val) end) ++
          push(name, "format", fn -> Exception.format(:error, val) end) ++
          push(name, "json", fn -> S.jsonify(val) end)
      else
        []
      end
  end

  # The SDK's own data, through the struct JSON as well.
  defp data_forms(name, node) do
    forms(name, node) ++
      push(name, "json", fn -> S.jsonify(node) end) ++
      push(name, "stringify", fn -> S.stringify(node) end)
  end

  defp error_forms(e) do
    forms("error", e) ++
      if match?(%${Name}.Error{}, e) do
        data_forms("error.result", e.result) ++ data_forms("error.spec", e.spec)
      else
        []
      end
  end

  defp result_forms(out) do
    cond do
      S.ismap(out) and S.getprop(out, "_client") != nil ->
        forms("result", out) ++ data_forms("result.data", S.getprop(out, "_data"))

      S.islist(out) ->
        forms("result", out)

      true ->
        data_forms("result", out)
    end
  end

  defp add(sinks, items), do: Enum.each(items, fn s -> S.setprop(sinks, S.size(sinks), s) end)
  defp sink_list(sinks), do: Enum.map(H.entries(sinks), &elem(&1, 1))

  # Captures the serialised context from inside the pipeline: what a hook
  # author would hand to a logger.
  defp capture_feature(sinks) do
    cap = fn hook ->
      fn ctx ->
        add(sinks, forms("ctx@" <> hook, ctx))
        add(sinks, data_forms("ctxdata@" <> hook, ${Name}.Context.to_data(ctx)))
        nil
      end
    end

    S.jm([
      "name", "capture", "version", "0.0.1", "active", true, "options", S.jm([]),
      "init", fn _ctx, _opts -> nil end,
      "PreRequest", cap.("PreRequest"),
      "PreResponse", cap.("PreResponse"),
      "PreUnexpected", cap.("PreUnexpected")
    ])
  end

  defp response(status, data, headers) do
    h = S.jm(["content-type", "application/json"])
    Enum.each(headers, fn {k, v} -> S.setprop(h, k, v) end)

    S.jm([
      "status", status,
      "statusText", if(status < 400, do: "OK", else: "ERR"),
      "headers", h,
      "body", S.jsonify(data),
      "json", fn -> data end
    ])
  end

  defp scenarios do
    [
      {"ok",
       fn _url, _fd ->
         {response(200, S.jm(["id", "i1", "name", "n1"]), [{"x-session-token", "RESP-TOKEN-a1b2c3d4e5"}]), nil}
       end},
      {"notfound", fn _url, _fd -> {response(404, S.jm(["error", "no such record"]), []), nil} end},
      {"server", fn _url, _fd -> {response(500, S.jm(["error", "boom"]), []), nil} end},
      {"transport",
       fn url, _fd ->
         {nil, ${Name}.Error.new("transport", "socket hang up (URL was: \\"" <> url <> "\\")")}
       end},
      {"notjson",
       fn _url, _fd ->
         {S.jm([
            "status", 200, "statusText", "OK", "headers", S.jm([]), "body", "<html>",
            "json", fn -> raise "Unexpected token < in JSON" end
          ]), nil}
       end}
    ]
  end

  defp make_sdk(respond, sinks, cleanopts) do
    capture = fn name -> fn rec -> add(sinks, data_forms(name, rec)) end end
    feature = S.jm([])

    on = fn name, kvs ->
      if FH.has_feature(name), do: S.setprop(feature, name, S.jm(["active", true] ++ kvs))
    end

    on.("log", ["logger", capture.("log")])
    on.("debug", ["onEntry", capture.("debug")])
    on.("audit", ["sink", capture.("audit")])
    on.("telemetry", ["exporter", capture.("telemetry")])
    on.("cost", ["sink", capture.("cost")])
    on.("metrics", [])
    on.("clienttrack", [])

    clean = S.jm(["values", @canary.value])
    Enum.each(cleanopts, fn {k, v} -> S.setprop(clean, k, v) end)

    ${Name}.new(
      S.jm([
        "apikey", @canary.apikey,
        "secret", @canary.secret,
        "headers", S.jm(["X-Custom-Token", @canary.header]),
        "clean", clean,
        "feature", feature,
        "extend", S.jt([capture_feature(sinks)]),
        "utility", S.jm(["fetcher", fn _ctx, url, fd -> respond.(url, fd) end])
      ])
    )
  end

  # The operations this SDK generated, read ops first.
  defp candidates do
    [
${candidates(Name, entity)}
    ]
  end

  # The first operation that completes against a plain 200 with no arguments.
  defp usable_op do
    plain =
      ${Name}.new(
        S.jm([
          "apikey", @canary.apikey,
          "utility", S.jm(["fetcher", fn _c, _u, _f -> {response(200, S.jm(["id", "i1"]), []), nil} end])
        ])
      )

    Enum.find(candidates(), fn {_name, acc, op} ->
      try do
        op.(acc.(plain), S.jm([]))
        true
      rescue
        _ -> false
      catch
        _, _ -> false
      end
    end)
  end

  defp drive(sdk, {_name, acc, op}, ctrl, sinks) do
    ent = acc.(sdk)

    {out, err} =
      try do
        {op.(ent, ctrl), nil}
      rescue
        e -> {nil, e}
      end

    if err != nil, do: add(sinks, error_forms(err))
    if out != nil, do: add(sinks, result_forms(out))
    explain = S.getprop(ctrl, "explain")
    if explain != nil, do: add(sinks, data_forms("explain", explain))
    err
  end

  test "no credential leaves the SDK in any form" do
    target = usable_op()
    assert target != nil, "no operation completes without arguments; nothing to sweep"

    sinks = S.jt([])

    variants = [
      {"throw", fn -> S.jm([]) end},
      {"explain", fn -> S.jm(["explain", S.jm([])]) end},
      {"nothrow", fn -> S.jm(["throw", false, "explain", S.jm([])]) end}
    ]

    {errors, explains} =
      Enum.reduce(scenarios(), {%{}, %{}}, fn {sname, respond}, acc ->
        Enum.reduce(variants, acc, fn {vname, mkctrl}, {errors, explains} ->
          sdk = make_sdk(respond, sinks, [])
          ctrl = mkctrl.()
          err = drive(sdk, target, ctrl, sinks)
          add(sinks, forms("sdk", sdk))
          key = sname <> "/" <> vname
          errors = if err != nil, do: Map.put(errors, key, err), else: errors
          ex = S.getprop(ctrl, "explain")
          explains = if ex != nil, do: Map.put(explains, key, ex), else: explains
          {errors, explains}
        end)
      end)

    all = sink_list(sinks)
    leaked = Enum.filter(all, fn s -> leaks(s.text) != [] end)

    IO.puts("clean: swept #{length(all)} surface(s), #{length(leaked)} leak(s)")

    assert leaked == [],
           "credential leaked through: " <>
             Enum.map_join(leaked, "; ", fn s -> s.name <> " [" <> Enum.join(leaks(s.text), ", ") <> "]" end)

    # The positive half: the slot the credential travelled in is masked, and
    # an unregistered token in a response header is masked by name.
    notfound = errors["notfound/throw"]
    assert notfound != nil, "the 404 scenario must throw"
    assert match?(%${Name}.Error{}, notfound), "the 404 error is an SDK error"
    assert ${Name}.Error.status(notfound) == 404
    spec = notfound.spec

    unless @auth.suppressed do
      case @auth.where do
        "query" ->
          assert header(S.getprop(spec, "query"), @auth.name) == @mask

        "cookie" ->
          assert String.contains?(to_string(header(S.getprop(spec, "headers"), "cookie")), @mask)

        _ ->
          assert String.ends_with?(to_string(header(S.getprop(spec, "headers"), @auth.name)), @mask)
      end
    end

    assert header(S.getprop(spec, "headers"), "x-custom-token") == @mask

    explained = explains["ok/explain"]
    result = if explained != nil, do: S.getprop(explained, "result"), else: nil
    assert S.ismap(result), "the explain record should carry the result"
    assert header(S.getprop(result, "headers"), "x-session-token") == @mask
  end

  test "the sweep can see a leak: clean switched off shows the credential" do
    target = usable_op()
    assert target != nil

    sinks = S.jt([])
    [_ok, {_name, notfound} | _] = scenarios()
    sdk = make_sdk(notfound, sinks, [{"active", false}])
    err = drive(sdk, target, S.jm([]), sinks)
    assert err != nil

    assert Enum.any?(sink_list(sinks), fn s -> leaks(s.text) != [] end),
           "with clean off, nothing showed the canary: the sweep is blind"

    unless @auth.suppressed do
      text = S.jsonify(err.spec)

      assert String.contains?(text, @canary.apikey) or
               String.contains?(text, Base.encode64(@canary.apikey <> ":" <> @canary.secret)),
             "the raw spec should carry the credential when clean is off"
    end
  end
end
`
}


export {
  TestClean
}
