
import { cmp, names, Content, File } from 'jostraca'

import {
  activeTargets,
  activeFeatures,
  activeEntities,
  projectName,
  workflowSection,
  featureSection,
  customiseSection,
  aontuSection,
  claudePointer,
  langCmd,
} from './AgentGuideContent'


// Top-level agent guide for a generated SDK project. Emitted once at the
// project root (no enclosing Folder), alongside README.md/Makefile. Teaches a
// coding agent how to operate the whole project: regenerate, add features,
// customise the model/templates, and read the aontu model language.
const AgentGuideTop = cmp(function AgentGuideTop(props: any) {
  const { ctx$ } = props
  const { model } = ctx$

  if (model.name && !model.Name) names(model, model.name)

  const Name = projectName(model)
  const targets = activeTargets(model)
  const features = activeFeatures(model)
  const entities = activeEntities(model)

  File({ name: 'AGENTS.md' }, () => {
    Content(`# ${Name} SDK — Agent Guide

This is a **generated** multi-language SDK project. The client libraries in
each language directory are produced by [@voxgig/sdkgen](https://github.com/voxgig/sdkgen)
from an API model; the generator, model, templates, and components all live in
\`.sdk/\`. Treat the language directories as build output — change the model,
a template, or a component and regenerate.

There are companion guides deeper in the tree: one per language
(\`<lang>/AGENTS.md\`) and one per feature
(\`<lang>/src/feature/<name>/AGENTS.md\`).

## Project map

`)

    // Targets
    if (0 < targets.length) {
      Content(`**Targets** (${targets.length}):

| Target | Directory | Build guide |
| --- | --- | --- |
`)
      targets.forEach((t: any) => {
        const note = langCmd(t.name).note ? ' — ' + langCmd(t.name).note : ''
        Content(`| \`${t.name}\` | \`${t.name}/\`${note} | [\`${t.name}/AGENTS.md\`](./${t.name}/AGENTS.md) |
`)
      })
      Content(`
`)
    }

    // Features
    if (0 < features.length) {
      Content(`**Features** (${features.length}): `)
      Content(features.map((f: any) => `\`${f.name}\``).join(', ') + `.

Each feature is generated into every SDK target — as a directory
\`<lang>/src/feature/<name>/\` (ts/js) or a flat file in the \`<lang>/feature/\`
package (other languages). Each target's guide documents its features.

`)
    }

    // Entities
    if (0 < entities.length) {
      Content(`**Entities** (${entities.length}): `)
      Content(entities.map((e: any) => `\`${e.Name || e.name}\``).join(', ') + `.

`)
    }

    // Station paragraph (station design §9.4), only when the model
    // carries the feature: an agent working on this repo should know
    // the runtime story without leaving AGENTS.md.
    if (features.some((f: any) => 'station' === f.name)) {
      Content(`**Station**: this SDK is a
[voxgig/station](https://github.com/voxgig/station) plugin (the
\`station\` feature, off by default). Bound to an open \`Station\`,
the credential is resolved by sekreto under the plugin's secret name
and injected at the transport seam — \`options()\` and
\`prepare()\` output hold only a placeholder, so both are safe to
inspect and log. \`station.tap(...)\`/\`station.events()\` show live
traffic; \`station.plugins()\` lists descriptors. See the "Use with
Station" README section and \`src/feature/station/\` (or the
target's feature container) for the generated adapter.

`)
    }

    Content(workflowSection())
    Content(featureSection())
    Content(customiseSection())
    Content(aontuSection())

    Content(`## Where things live

\`\`\`
.sdk/
  model/          the model: target/, feature/, and index .aon files
  src/cmp/<lang>/  components — TypeScript that generates API-specific source
  tm/<lang>/       templates — verbatim source copied with placeholders
  dist/            compiled components (npm run build)
<lang>/           generated SDK for each target (build output)
README.md         human-facing overview
Makefile          per-target deploy recipes
\`\`\`

---

Generated by [@voxgig/sdkgen](https://github.com/voxgig/sdkgen). Regenerate
with \`cd .sdk && npm run generate\`.
`)
  })

  File({ name: 'CLAUDE.md' }, () => {
    Content(claudePointer(`${Name} SDK`))
  })

  ctx$.log?.info?.({ point: 'generate-agentguide-top', note: 'name:' + Name })
})


export {
  AgentGuideTop
}
