import { cmp, each, Content, File } from 'jostraca'

import {
  KIT,
  getModelPath
} from '../types'


// Per-target `aql vault exec` credential recipes, mirroring the header
// documentation of each target's publish Makefile (project/.sdk/tm/<t>/
// Makefile). The alias Make variables let a deployer point at their own
// vault aliases without editing the generated file:
//   make deploy-ts NPM_ALIAS=work:npm
// Targets without an entry fall back to github-only (tag push is the
// common denominator of every publish recipe).
const VAULT_RECIPE: Record<string, string> = {
  ts: '--for=npm=$(NPM_ALIAS) --for=github=$(GITHUB_ALIAS)',
  js: '--for=npm=$(NPM_ALIAS) --for=github=$(GITHUB_ALIAS)',
  go: '--for=github=$(GITHUB_ALIAS)',
  py: '--for=pypi=$(PYPI_ALIAS) --for=github=$(GITHUB_ALIAS)',
  php: '--for=github=$(GITHUB_ALIAS)',
  rb: '--for=gem=$(GEM_ALIAS) --for=github=$(GITHUB_ALIAS)',
  // luarocks has no aql --for preset: map aliases to env vars directly.
  lua: "'$(LUAROCKS_ALIAS)=LUAROCKS_API_KEY,$(GITHUB_ALIAS)=GITHUB_TOKEN'",
}

const DEFAULT_RECIPE = '--for=github=$(GITHUB_ALIAS)'


// Generate the SDK root deployment Makefile. Deploying a target runs that
// target's `make publish` (build + test + registry upload + version tag)
// with credentials injected at exec time by the aql key vault — never on
// disk or argv. Follows the voxgig/struct root Makefile conventions:
// per-target deploy targets, deliberately no all-targets real deploy
// (each upload is irreversible), and an everything-at-once DRY run that
// leans on `aql vault exec --dry-run` filler-token cooperation in each
// publish recipe.
const Deploy = cmp(function Deploy(props: any) {
  const { ctx$ } = props
  const { model } = ctx$

  const targetMap = getModelPath(model, `main.${KIT}.target`) || {}
  const targets: string[] = []
  each(targetMap, (t: any) => { targets.push(t.name) })

  if (0 === targets.length) {
    return
  }

  File({ name: 'Makefile' }, () => {
    Content(makeDeployMakefile(model, targets))
  })

  ctx$.log.info({ point: 'generate-deploy', note: 'targets: ' + targets.join(',') })
})


function makeDeployMakefile(model: any, targets: string[]): string {
  const deployRules = targets.map((t) => {
    const recipe = VAULT_RECIPE[t] || DEFAULT_RECIPE
    return `
deploy-${t}:
\taql vault exec ${recipe} -- $(MAKE) -C ${t} publish

deploy-dry-${t}:
\taql vault exec --dry-run ${recipe} -- $(MAKE) -C ${t} publish
`
  }).join('')

  return `# ${model.Name} SDK deployment. GENERATED by @voxgig/sdkgen — regenerated
# on every \`npm run generate\` in .sdk/; change the model, not this file.
#
# Deploying a target publishes its package to that ecosystem's registry
# and pushes a <target>/vX.Y.Z tag (see <target>/Makefile publish).
# Credentials are injected at exec time by the aql key vault
# (https://github.com/aql-lang/aql) — never stored on disk or passed on
# the command line.
#
#   make deploy               list per-target deploy commands
#   make deploy-<target>      deploy ONE target (no deploy-all: each
#                             registry upload is irreversible)
#   make deploy-dry           rehearse EVERY target: aql --dry-run
#                             injects a filler token that each publish
#                             recipe detects, so build + test run in full
#                             but nothing is uploaded and no tag is cut
#
# Vault aliases (override per invocation, e.g. make deploy-ts NPM_ALIAS=work:npm):

SHELL := /bin/bash

NPM_ALIAS ?= npm
GITHUB_ALIAS ?= github
PYPI_ALIAS ?= pypi
GEM_ALIAS ?= gem
LUAROCKS_ALIAS ?= luarocks

TARGETS := ${targets.join(' ')}

.PHONY: deploy deploy-dry \\
  $(addprefix deploy-,$(TARGETS)) $(addprefix deploy-dry-,$(TARGETS))

deploy:
\t@echo "Deployment is per-target — pick one (each upload is irreversible):"
\t@echo "  make deploy-<target>    targets: $(TARGETS)"
\t@echo "Rehearse everything safely first: make deploy-dry"

deploy-dry: $(addprefix deploy-dry-,$(TARGETS))
\t@echo "deploy-dry: all targets rehearsed OK ($(TARGETS))"
${deployRules}`
}


export {
  Deploy
}
