import { cmp, each, Content, File } from 'jostraca'

import { packageVersion } from '../helpers/packageMeta'

import {
  KIT,
  getModelPath
} from '../types'


const Deploy = cmp(function Deploy(props: any) {
  const { ctx$ } = props
  const { model } = ctx$

  const targetMap = getModelPath(model, `main.${KIT}.target`) || {}
  const targets: any[] = []
  each(targetMap, (t: any) => {
    if (false !== t.active) targets.push(t)
  })

  if (0 === targets.length) {
    return
  }

  File({ name: 'Makefile' }, () => {
    Content(makeDeployMakefile(model, targets))
  })

  ctx$.log.info({
    point: 'generate-deploy',
    note: 'targets: ' + targets.map((t: any) =>
      t.name + (registryOf(t) ? (':' + registryOf(t).name + (regIsActive(registryOf(t)) ? '' : '(publish pending)')) : ':tag-only')
    ).join(',')
  })
})


function registryOf(t: any): any | undefined {
  const reg = t.publish?.registry
  return (reg && '' !== (reg.name || '')) ? reg : undefined
}


// A registry is active (package really uploaded) when its tri-state
// `state === 'active'`. The legacy boolean `active: true` is honoured as a
// back-compat alias. Anything else — 'pending' (the default), 'inactive' —
// means a deploy publishes the git tag only.
function regIsActive(reg: any): boolean {
  if (null == reg) return false
  if (true === reg.active) return true
  return 'active' === reg.state
}


function aliasVarName(name: string): string {
  return name.toUpperCase().replace(/[^A-Z0-9]+/g, '_') + '_ALIAS'
}


// The boru vault exec argument string for a target: `--for=<recipe>=<alias>`
// flags where a preset recipe exists, or a raw `'alias=ENV_VAR,...'`
// mapping when any credential lacks a preset (e.g. luarocks). The github
// token for the tag push is always included.
function vaultExecArgs(t: any): string {
  const tagVault = t.publish?.tag?.vault || {}
  const ghRecipe = tagVault.recipe || 'github'
  const ghVar = aliasVarName(ghRecipe)
  const reg = registryOf(t)
  const regVault = reg?.vault || {}
  const regVar = reg ? aliasVarName(reg.name) : ''

  if (reg && '' === (regVault.recipe || '') && '' !== (regVault.env || '')) {
    return `'$(${regVar})=${regVault.env},$(${ghVar})=GITHUB_TOKEN'`
  }

  const flags = []
  if (reg && '' !== (regVault.recipe || '')) {
    flags.push(`--for=${regVault.recipe}=$(${regVar})`)
  }
  flags.push(`--for=${ghRecipe}=$(${ghVar})`)
  return flags.join(' ')
}


function makeDeployMakefile(model: any, targets: any[]): string {
  const aliasVars = new Map<string, string>()
  for (const t of targets) {
    const tagVault = t.publish?.tag?.vault || {}
    const ghRecipe = tagVault.recipe || 'github'
    if (!aliasVars.has(aliasVarName(ghRecipe))) {
      aliasVars.set(aliasVarName(ghRecipe), tagVault.alias || ghRecipe)
    }
    const reg = registryOf(t)
    if (reg && !aliasVars.has(aliasVarName(reg.name))) {
      aliasVars.set(aliasVarName(reg.name), reg.vault?.alias || reg.name)
    }
  }

  const summary = targets.map((t: any) => {
    const reg = registryOf(t)
    const state = reg
      ? `${reg.name} (${regIsActive(reg) ? 'ACTIVE' : 'publish pending: deploy publishes the git tag only'}) ${reg.url || ''}`.trim()
      : 'tag-only'
    return `#   ${t.name.padEnd(8)} ${state}`
  }).join('\n')

  const deployRules = targets.map((t: any) => {
    const reg = registryOf(t)
    const tagVault = t.publish?.tag?.vault || {}
    const ghRecipe = tagVault.recipe || 'github'
    const ghArgs = `--for=${ghRecipe}=$(${aliasVarName(ghRecipe)})`
    const args = vaultExecArgs(t)

    const via = t.publish?.tag?.via || 'port'

    if (!reg && 'root' === via) {
      return `
deploy-${t.name}:
\t@echo "deploy-${t.name}: tag-only port — publishing the git tag."
\tboru vault exec ${ghArgs} -- $(MAKE) tag-push-${t.name}

deploy-dry-${t.name}:
\tboru vault exec --dry-run ${ghArgs} -- $(MAKE) tag-push-${t.name}
${tagPushRecipe(t.name, packageVersion(model, t.name), 'tag-only port')}
`
    }

    if (reg && !regIsActive(reg)) {
      return `
deploy-${t.name}:
\t@echo "deploy-${t.name}: ${reg.name} publication is pending — publishing the git tag only."
\tboru vault exec ${ghArgs} -- $(MAKE) tag-push-${t.name}

deploy-dry-${t.name}:
\tboru vault exec --dry-run ${ghArgs} -- $(MAKE) tag-push-${t.name}
${tagPushRecipe(t.name, packageVersion(model, t.name), reg.name + ' publication pending — tag-only deploy')}
`
    }

    return `
deploy-${t.name}:
\tboru vault exec ${args} -- $(MAKE) -C ${t.name} publish

deploy-dry-${t.name}:
\tboru vault exec --dry-run ${args} -- $(MAKE) -C ${t.name} publish
`
  }).join('')

  const varLines = Array.from(aliasVars.entries())
    .map(([v, def]) => `${v} ?= ${def}`).join('\n')

  return `# ${model.Name} SDK deployment. GENERATED by @voxgig/sdkgen — regenerated
# on every \`npm run generate\` in .sdk/; publication details live in the
# model (.sdk/model/target/<target>.aontu, \`publish\` section).
#
# Every port gets a git release tag <target>/vX.Y.Z. Ports with an ACTIVE
# registry also publish a package there. Credentials are injected at exec
# time by the boru key vault (https://github.com/boru-lang/boru) — never
# stored on disk or passed on the command line.
#
# Publication state (from the model):
${summary}
#
#   make deploy               list per-target deploy commands
#   make deploy-<target>      deploy ONE target (no deploy-all: each
#                             registry upload is irreversible); while a
#                             registry is pending this publishes the
#                             port's git tag only
#   make deploy-dry           rehearse EVERY target: boru --dry-run
#                             injects a filler token that each publish
#                             recipe detects, so build + test run in full
#                             but nothing is uploaded and no tag is cut
#
# Vault aliases (override per invocation, e.g. make deploy-ts NPM_ALIAS=work:npm):

SHELL := /bin/bash

${varLines}

BORU_DRY_RUN_FILLER := BORU-DRY-RUN-FILLER-NOT-A-REAL-SECRET

TARGETS := ${targets.map((t: any) => t.name).join(' ')}

.PHONY: deploy deploy-dry \\
  $(addprefix deploy-,$(TARGETS)) $(addprefix deploy-dry-,$(TARGETS)) \\
  $(addprefix tag-push-,$(TARGETS))

deploy:
\t@echo "Deployment is per-target — pick one (each upload is irreversible):"
\t@echo "  make deploy-<target>    targets: $(TARGETS)"
\t@echo "Registry state is set in the model (.sdk/model/target/<t>.aontu):"
${targets.map((t: any) => {
    const reg = registryOf(t)
    const state = reg ? `${reg.name} ${regIsActive(reg) ? 'ACTIVE' : 'publish pending (deploy = git tag only)'}` : 'tag-only'
    return `\t@echo "  deploy-${t.name.padEnd(8)} ${state}"`
  }).join('\n')}
\t@echo "Rehearse everything safely first: make deploy-dry"

deploy-dry: $(addprefix deploy-dry-,$(TARGETS))
\t@echo "deploy-dry: all targets rehearsed OK ($(TARGETS))"
${deployRules}`
}



// The root-level tag creation + push recipe for a target: boru --dry-run
// filler cooperation, idempotent tag creation, token-authenticated https
// push (works from an ssh-remote clone without ssh keys).
function tagPushRecipe(name: string, version: string, note: string): string {
  // The version is embedded in both Make and shell syntax.
  if (!/^[0-9A-Za-z][0-9A-Za-z.+-]*$/.test(version)) {
    throw new Error('Deploy: invalid publish.version for target "' + name + '": ' + JSON.stringify(version))
  }

  return `
tag-push-${name}:
\t@set -e; tag="${name}/v${version}"; \\
\ttoken="\$\${GITHUB_TOKEN:-$$GH_TOKEN}"; \\
\tif [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \\
\t  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \\
\tif [ -z "$$token" ]; then echo "tag-push-${name}: no GITHUB_TOKEN in env — run via make deploy-${name} (boru vault exec)"; exit 1; fi; \\
\tif git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \\
\t  echo "tag $$tag already exists — pushing existing tag"; \\
\telse git tag -a "$$tag" -m "Release $$tag"; fi; \\
\turl=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \\
\thdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\\n')"; \\
\tgit -c http.extraheader="$$hdr" push "$$url" "$$tag"; \\
\techo "pushed $$tag (${note})"`
}

export {
  Deploy
}
