import { cmp, Content, File } from 'jostraca'

import { SECURITY_EMAIL, apiName, repoInfo } from '../helpers/packageMeta'


// Root SECURITY.md: a responsible-disclosure policy pointing at the Voxgig
// security contact, with the generated / unofficial disclosure inline.
const Security = cmp(function Security(props: any) {
  const { ctx$ } = props
  const { model } = ctx$

  const { issuesUrl } = repoInfo(model)

  File({ name: 'SECURITY.md' }, () => {
    Content(`# Security Policy

## Reporting a vulnerability

Please report security issues to ${SECURITY_EMAIL}.

Do not open public GitHub issues for suspected vulnerabilities. We aim to
acknowledge reports within 3 business days.

For non-security bugs, use the issue tracker: ${issuesUrl}

## Scope

This policy applies to the generated Voxgig SDK packages published from this
repository (npm, PyPI, Packagist, RubyGems, LuaRocks, and the Go module).

This is an unofficial SDK for the ${apiName(model)} public API, generated by
Voxgig. It is not affiliated with, endorsed by, or sponsored by the upstream
API provider.
`)
  })
})


export {
  Security
}
