import { cmp, Content, File } from 'jostraca'

import {
  apiName, isDefaultPublisher, publisherInfo, repoInfo, securityContact,
} from '../helpers/packageMeta'


const Security = cmp(function Security(props: any) {
  const { ctx$ } = props
  const { model } = ctx$

  const { issuesUrl } = repoInfo(model)
  const publisher = publisherInfo(model)

  // Voxgig's own response commitment, which another publisher has not made.
  const promise = isDefaultPublisher(model) ?
    ' We aim to\nacknowledge reports within 3 business days.' : ''

  File({ name: 'SECURITY.md' }, () => {
    Content(`# Security Policy

## Reporting a vulnerability

Please report security issues ${securityContact(model)}.

Do not open public GitHub issues for suspected vulnerabilities.${promise}

For non-security bugs, use the issue tracker: ${issuesUrl}

## Scope

This policy applies to the generated ${publisher.name} SDK packages published from this
repository (npm, PyPI, Packagist, RubyGems, LuaRocks, and the Go module).

This is an unofficial SDK for the ${apiName(model)} public API, generated by
${publisher.name}. It is not affiliated with, endorsed by, or sponsored by the upstream
API provider.
`)
  })
})


export {
  Security
}
