;; ProjectName SDK EntityName entity (generated by @voxgig/sdkgen).
(ns sdk.entity.entityname
  (:refer-clojure :exclude [load list remove update])
  (:require [sdk.core :as core]
            [voxgig.struct :as vs]))

(declare new-entity)

(defn- ensure-entopts [entopts]
  (let [e (if (vs/ismap entopts) entopts (vs/jm))]
    (when (nil? (vs/getprop e "active")) (.put ^java.util.Map e "active" true))
    e))

(defn- ent-data-set [ent args]
  (when args
    (reset! (:_data ent) (let [m (core/to-map (vs/clone args))] (if m m (vs/jm))))
    (core/feature-hook (:_entctx ent) "SetData")))

(defn- ent-data-get [ent]
  (core/feature-hook (:_entctx ent) "GetData")
  (vs/clone (deref (:_data ent))))

(defn- ent-match-set [ent args]
  (when args
    (reset! (:_match ent) (let [m (core/to-map (vs/clone args))] (if m m (vs/jm))))
    (core/feature-hook (:_entctx ent) "SetMatch")))

(defn- ent-match-get [ent]
  (core/feature-hook (:_entctx ent) "GetMatch")
  (vs/clone (deref (:_match ent))))

(defn- new-entity [client entopts]
  (let [entopts (ensure-entopts entopts)
        utility (core/get-utility client)
        data (atom (vs/jm))
        match (atom (vs/jm))
        entctx (core/make-context (vs/jm "entopts" entopts) (core/client-root-ctx client))
        ent {:_name "entityname" :_client client :_utility utility :_entopts entopts
             :_data data :_match match :_entctx entctx
             :get-name (fn [] "entityname")
             :make (fn [] (new-entity client (vs/clone entopts)))}
        ent (assoc ent
                   :data-set (fn [args] (ent-data-set ent args))
                   :data-get (fn [] (ent-data-get ent))
                   :match-set (fn [args] (ent-match-set ent args))
                   :match-get (fn [] (ent-match-get ent)))]
    (core/oset! entctx :entity ent)
    (core/feature-hook entctx "PostConstructEntity")
    ent))

;; Canonical facade: (EntityName client data) accessor delegates here.
(defn make [client data] (new-entity client data))

;; The operation pipeline runner. Feature hooks fire at each stage; a stage
;; error is surfaced via make-error (which raises, or returns the bare result
;; when throwing is disabled). The hook marker lines below are rewritten to
;; (core/feature-hook ctx "<Stage>") by the component's hook regex — a `;`
;; comment form, since jostraca's built-in tag replacement only matches `//`.
(defn- run-op [ctx post-done]
  (try
    ; #PrePoint-Hook
    (let [[point err] ((core/uget ctx :make-point) ctx)]
      (core/out-set! ctx "point" point)
      (if err
        ((core/uget ctx :make-error) ctx err)
        (do
          ; #PreSpec-Hook
          (let [[spec err] ((core/uget ctx :make-spec) ctx)]
            (core/out-set! ctx "spec" spec)
            (if err
              ((core/uget ctx :make-error) ctx err)
              (do
                ; #PreRequest-Hook
                (let [[resp err] ((core/uget ctx :make-request) ctx)]
                  (core/out-set! ctx "request" resp)
                  (if err
                    ((core/uget ctx :make-error) ctx err)
                    (do
                      ; #PreResponse-Hook
                      (let [[resp2 err] ((core/uget ctx :make-response) ctx)]
                        (core/out-set! ctx "response" resp2)
                        (if err
                          ((core/uget ctx :make-error) ctx err)
                          (do
                            ; #PreResult-Hook
                            (let [[result err] ((core/uget ctx :make-result) ctx)]
                              (core/out-set! ctx "result" result)
                              (if err
                                ((core/uget ctx :make-error) ctx err)
                                (do
                                  ; #PreDone-Hook
                                  (post-done)
                                  ((core/uget ctx :done) ctx))))))))))))))))
    (catch Throwable operr
      ; #PreUnexpected-Hook
      (throw operr))))

; #LoadOp

; #ListOp

; #CreateOp

; #UpdateOp

; #RemoveOp
